import type { Lang } from './i18n'

// OTOMATIK URETILDI (gen-i18n.mjs) — satir-ici UI metinleri, Ingilizce anahtarli.
export const UI: Record<string, Partial<Record<Lang, string>>> = {
  "Code": {
    "tr": "Kod",
    "es": "Código",
    "fr": "Code",
    "de": "Code",
    "pt": "Código",
    "ru": "Код",
    "zh": "代码",
    "ja": "コード",
    "ar": "الكود"
  },
  "Tree": {
    "tr": "Ağaç",
    "es": "Árbol",
    "fr": "Arborescence",
    "de": "Baum",
    "pt": "Árvore",
    "ru": "Дерево",
    "zh": "目录树",
    "ja": "ツリー",
    "ar": "الشجرة"
  },
  "History": {
    "tr": "Geçmiş",
    "es": "Historial",
    "fr": "Historique",
    "de": "Verlauf",
    "pt": "Histórico",
    "ru": "История",
    "zh": "历史",
    "ja": "履歴",
    "ar": "السجل"
  },
  "Engine": {
    "tr": "Motor",
    "es": "Motor",
    "fr": "Moteur",
    "de": "Engine",
    "pt": "Motor",
    "ru": "Движок",
    "zh": "引擎",
    "ja": "エンジン",
    "ar": "المحرّك"
  },
  "Docs": {
    "tr": "Belgeler",
    "es": "Documentos",
    "fr": "Docs",
    "de": "Docs",
    "pt": "Documentos",
    "ru": "Документы",
    "zh": "文档",
    "ja": "ドキュメント",
    "ar": "المستندات"
  },
  "Export error": {
    "tr": "Dışa aktarma hatası",
    "es": "Error de exportación",
    "fr": "Erreur d'exportation",
    "de": "Exportfehler",
    "pt": "Erro de exportação",
    "ru": "Ошибка экспорта",
    "zh": "导出错误",
    "ja": "エクスポートエラー",
    "ar": "خطأ في التصدير"
  },
  "Scan report added to chat": {
    "tr": "Tarama raporu sohbete eklendi",
    "es": "Informe de escaneo añadido al chat",
    "fr": "Rapport d'analyse ajouté à la discussion",
    "de": "Scan-Bericht zum Chat hinzugefügt",
    "pt": "Relatório de análise adicionado ao chat",
    "ru": "Отчёт о сканировании добавлен в чат",
    "zh": "扫描报告已添加到对话",
    "ja": "スキャンレポートをチャットに追加しました",
    "ar": "أُضيف تقرير الفحص إلى المحادثة"
  },
  "Dev server stopped": {
    "tr": "Dev sunucusu durduruldu",
    "es": "Servidor dev detenido",
    "fr": "Serveur de dev arrêté",
    "de": "Dev-Server gestoppt",
    "pt": "Servidor dev parado",
    "ru": "Dev-сервер остановлен",
    "zh": "开发服务器已停止",
    "ja": "開発サーバーを停止しました",
    "ar": "أُوقِف خادم التطوير"
  },
  "Preparing project (npm install + dev server)…": {
    "tr": "Proje hazırlanıyor (npm install + dev sunucusu)…",
    "es": "Preparando proyecto (npm install + servidor dev)…",
    "fr": "Préparation du projet (npm install + serveur de dev)…",
    "de": "Projekt wird vorbereitet (npm install + Dev-Server)…",
    "pt": "Preparando projeto (npm install + servidor dev)…",
    "ru": "Подготовка проекта (npm install + dev-сервер)…",
    "zh": "正在准备项目（npm install + 开发服务器）…",
    "ja": "プロジェクトを準備中（npm install + 開発サーバー）…",
    "ar": "جارٍ تجهيز المشروع (npm install + خادم التطوير)…"
  },
  "Running: ": {
    "tr": "Çalışıyor: ",
    "es": "Ejecutando: ",
    "fr": "En cours : ",
    "de": "Läuft: ",
    "pt": "Executando: ",
    "ru": "Выполняется: ",
    "zh": "正在运行：",
    "ja": "実行中： ",
    "ar": "قيد التشغيل: "
  },
  "Failed to start": {
    "tr": "Başlatılamadı",
    "es": "No se pudo iniciar",
    "fr": "Échec du démarrage",
    "de": "Start fehlgeschlagen",
    "pt": "Falha ao iniciar",
    "ru": "Не удалось запустить",
    "zh": "启动失败",
    "ja": "起動に失敗しました",
    "ar": "فشل البدء"
  },
  "Live scan on — no findings": {
    "tr": "Canlı tarama açık — bulgu yok",
    "es": "Escaneo en vivo activo — sin hallazgos",
    "fr": "Analyse en direct activée — aucun résultat",
    "de": "Live-Scan aktiv — keine Funde",
    "pt": "Análise ao vivo ativada — nenhuma ocorrência",
    "ru": "Живое сканирование включено — находок нет",
    "zh": "实时扫描已开启 — 无发现",
    "ja": "ライブスキャン中 — 検出なし",
    "ar": "الفحص المباشر مفعّل — لا نتائج"
  },
  "Live scan: scan in the background as you type (never edits files)": {
    "tr": "Canlı tarama: sen yazarken arka planda tara (dosya değiştirmez)",
    "es": "Escaneo en vivo: analiza en segundo plano mientras escribes (nunca edita archivos)",
    "fr": "Analyse en direct : analyse en arrière-plan pendant la frappe (ne modifie jamais les fichiers)",
    "de": "Live-Scan: im Hintergrund scannen, während du tippst (ändert nie Dateien)",
    "pt": "Análise ao vivo: analisa em segundo plano enquanto você digita (nunca edita arquivos)",
    "ru": "Живое сканирование: проверяет в фоне, пока вы печатаете (файлы не меняет)",
    "zh": "实时扫描：在你输入时于后台扫描（绝不修改文件）",
    "ja": "ライブスキャン：入力中にバックグラウンドでスキャン（ファイルは変更しません）",
    "ar": "الفحص المباشر: يفحص في الخلفية أثناء كتابتك (لا يعدّل الملفات أبدًا)"
  },
  "Live": {
    "tr": "Canlı",
    "es": "En vivo",
    "fr": "En direct",
    "de": "Live",
    "pt": "Ao vivo",
    "ru": "Живое",
    "zh": "实时",
    "ja": "ライブ",
    "ar": "مباشر"
  },
  "Scan without running: find faulty code, repair deterministically": {
    "tr": "Projeyi çalıştırmadan tara: hatalı kodu bul, bulunanı modelsiz onar",
    "es": "Escanear sin ejecutar: encuentra código defectuoso y repáralo de forma determinista",
    "fr": "Analyser sans exécuter : trouve le code défectueux, le répare de façon déterministe",
    "de": "Ohne Ausführen scannen: fehlerhaften Code finden, deterministisch reparieren",
    "pt": "Analisar sem executar: encontra código com defeito e repara de forma determinística",
    "ru": "Сканировать без запуска: найти ошибочный код, исправить детерминированно",
    "zh": "无需运行即可扫描：找出问题代码，确定性修复",
    "ja": "実行せずにスキャン：不具合のあるコードを見つけ、確定的に修復",
    "ar": "افحص دون تشغيل: اعثر على الكود المعطوب وأصلحه بشكل حتمي"
  },
  "Scan": {
    "tr": "Tara",
    "es": "Escanear",
    "fr": "Analyser",
    "de": "Scannen",
    "pt": "Analisar",
    "ru": "Сканировать",
    "zh": "扫描",
    "ja": "スキャン",
    "ar": "فحص"
  },
  "Stop dev server": {
    "tr": "Dev sunucusunu durdur",
    "es": "Detener servidor dev",
    "fr": "Arrêter le serveur de dev",
    "de": "Dev-Server stoppen",
    "pt": "Parar servidor dev",
    "ru": "Остановить dev-сервер",
    "zh": "停止开发服务器",
    "ja": "開発サーバーを停止",
    "ar": "إيقاف خادم التطوير"
  },
  "Run project on localhost": {
    "tr": "Projeyi localhost'ta çalıştır",
    "es": "Ejecutar proyecto en localhost",
    "fr": "Exécuter le projet sur localhost",
    "de": "Projekt auf localhost ausführen",
    "pt": "Executar projeto no localhost",
    "ru": "Запустить проект на localhost",
    "zh": "在 localhost 上运行项目",
    "ja": "localhostでプロジェクトを実行",
    "ar": "تشغيل المشروع على localhost"
  },
  "Stop": {
    "tr": "Durdur",
    "es": "Detener",
    "fr": "Arrêter",
    "de": "Stopp",
    "pt": "Parar",
    "ru": "Стоп",
    "zh": "停止",
    "ja": "停止",
    "ar": "إيقاف"
  },
  "Run": {
    "tr": "Çalıştır",
    "es": "Ejecutar",
    "fr": "Exécuter",
    "de": "Ausführen",
    "pt": "Executar",
    "ru": "Запустить",
    "zh": "运行",
    "ja": "実行",
    "ar": "تشغيل"
  },
  "Search files…": {
    "tr": "Dosyalarda ara…",
    "es": "Buscar archivos…",
    "fr": "Rechercher des fichiers…",
    "de": "Dateien durchsuchen…",
    "pt": "Buscar arquivos…",
    "ru": "Поиск файлов…",
    "zh": "搜索文件…",
    "ja": "ファイルを検索…",
    "ar": "بحث في الملفات…"
  },
  "No matches": {
    "tr": "Eşleşme yok",
    "es": "Sin coincidencias",
    "fr": "Aucune correspondance",
    "de": "Keine Treffer",
    "pt": "Nenhuma correspondência",
    "ru": "Совпадений нет",
    "zh": "无匹配项",
    "ja": "一致なし",
    "ar": "لا توجد تطابقات"
  },
  "ready": {
    "tr": "hazır",
    "es": "listo",
    "fr": "prêt",
    "de": "bereit",
    "pt": "pronto",
    "ru": "готово",
    "zh": "就绪",
    "ja": "準備完了",
    "ar": "جاهز"
  },
  "NEW": {
    "tr": "YENİ",
    "es": "NUEVO",
    "fr": "NOUV.",
    "de": "NEU",
    "pt": "NOVO",
    "ru": "НОВОЕ",
    "zh": "新",
    "ja": "NEW",
    "ar": "جديد"
  },
  "s": {
    "tr": "sn",
    "es": "s",
    "fr": "s",
    "de": "s",
    "pt": "s",
    "ru": "с",
    "zh": "秒",
    "ja": "秒",
    "ar": "ث"
  },
  "m": {
    "tr": "dk",
    "es": "min",
    "fr": "min",
    "de": "m",
    "pt": "min",
    "ru": "м",
    "zh": "分",
    "ja": "分",
    "ar": "د"
  },
  "h": {
    "tr": "sa",
    "es": "h",
    "fr": "h",
    "de": "h",
    "pt": "h",
    "ru": "ч",
    "zh": "时",
    "ja": "時間",
    "ar": "س"
  },
  "Describe an image…": {
    "tr": "Bir görsel tarif et…",
    "es": "Describe una imagen…",
    "fr": "Décrivez une image…",
    "de": "Beschreibe ein Bild…",
    "pt": "Descreva uma imagem…",
    "ru": "Опишите изображение…",
    "zh": "描述一张图片…",
    "ja": "画像を説明…",
    "ar": "صِف صورة…"
  },
  "Tasks": {
    "tr": "Görevler",
    "es": "Tareas",
    "fr": "Tâches",
    "de": "Aufgaben",
    "pt": "Tarefas",
    "ru": "Задачи",
    "zh": "任务",
    "ja": "タスク",
    "ar": "المهام"
  },
  "queued": {
    "tr": "sırada",
    "es": "en cola",
    "fr": "en file",
    "de": "in Warteschlange",
    "pt": "na fila",
    "ru": "в очереди",
    "zh": "排队中",
    "ja": "待機中",
    "ar": "في الطابور"
  },
  "running": {
    "tr": "koşuyor",
    "es": "en curso",
    "fr": "en cours",
    "de": "läuft",
    "pt": "executando",
    "ru": "выполняется",
    "zh": "运行中",
    "ja": "実行中",
    "ar": "قيد التشغيل"
  },
  "⚠ review": {
    "tr": "⚠ incele",
    "es": "⚠ revisar",
    "fr": "⚠ à examiner",
    "de": "⚠ prüfen",
    "pt": "⚠ revisar",
    "ru": "⚠ проверить",
    "zh": "⚠ 待查",
    "ja": "⚠ 要確認",
    "ar": "⚠ مراجعة"
  },
  "failed": {
    "tr": "başarısız",
    "es": "fallida",
    "fr": "échoué",
    "de": "fehlgeschlagen",
    "pt": "falhou",
    "ru": "ошибка",
    "zh": "失败",
    "ja": "失敗",
    "ar": "فشل"
  },
  "cancelled": {
    "tr": "iptal",
    "es": "cancelada",
    "fr": "annulé",
    "de": "abgebrochen",
    "pt": "cancelado",
    "ru": "отменено",
    "zh": "已取消",
    "ja": "キャンセル済み",
    "ar": "أُلغي"
  },
  "Cancel": {
    "tr": "İptal",
    "es": "Cancelar",
    "fr": "Annuler",
    "de": "Abbrechen",
    "pt": "Cancelar",
    "ru": "Отмена",
    "zh": "取消",
    "ja": "キャンセル",
    "ar": "إلغاء"
  },
  "Review": {
    "tr": "İncele",
    "es": "Revisar",
    "fr": "Examiner",
    "de": "Prüfen",
    "pt": "Revisar",
    "ru": "Проверить",
    "zh": "查看",
    "ja": "確認",
    "ar": "مراجعة"
  },
  "queued ": {
    "tr": "sırada ",
    "es": "en cola ",
    "fr": "en file ",
    "de": "in Warteschlange ",
    "pt": "na fila ",
    "ru": "в очереди ",
    "zh": "排队中 ",
    "ja": "待機中 ",
    "ar": "في الطابور "
  },
  "running ": {
    "tr": "koşuyor ",
    "es": "en curso ",
    "fr": "en cours ",
    "de": "läuft ",
    "pt": "executando ",
    "ru": "выполняется ",
    "zh": "运行中 ",
    "ja": "実行中 ",
    "ar": "قيد التشغيل "
  },
  "Clear finished": {
    "tr": "Bitmişleri temizle",
    "es": "Limpiar terminadas",
    "fr": "Effacer les terminées",
    "de": "Fertige löschen",
    "pt": "Limpar concluídas",
    "ru": "Очистить завершённые",
    "zh": "清除已完成",
    "ja": "完了分をクリア",
    "ar": "مسح المكتملة"
  },
  "Attach reference image": {
    "tr": "Referans görsel ekle",
    "es": "Adjuntar imagen de referencia",
    "fr": "Joindre une image de référence",
    "de": "Referenzbild anhängen",
    "pt": "Anexar imagem de referência",
    "ru": "Прикрепить референсное изображение",
    "zh": "附加参考图片",
    "ja": "参照画像を添付",
    "ar": "إرفاق صورة مرجعية"
  },
  "Modern landing page with clean animations and Tailwind.": {
    "tr": "Temiz animasyonlar ve Tailwind ile modern landing page.",
    "es": "Landing page moderna con animaciones limpias y Tailwind.",
    "fr": "Landing page moderne avec animations épurées et Tailwind.",
    "de": "Moderne Landing Page mit sauberen Animationen und Tailwind.",
    "pt": "Landing page moderna com animações elegantes e Tailwind.",
    "ru": "Современный лендинг с плавными анимациями и Tailwind.",
    "zh": "简洁动画、Tailwind 打造的现代落地页。",
    "ja": "クリーンなアニメーションとTailwindを使ったモダンなランディングページ。",
    "ar": "صفحة هبوط عصرية برسوم متحركة أنيقة وTailwind."
  },
  "Clean management dashboard with cards, charts, and filters.": {
    "tr": "Kartlar, grafikler ve filtrelerle temiz yönetim paneli.",
    "es": "Dashboard de gestión limpio con tarjetas, gráficos y filtros.",
    "fr": "Dashboard de gestion épuré avec cartes, graphiques et filtres.",
    "de": "Übersichtliches Management-Dashboard mit Karten, Diagrammen und Filtern.",
    "pt": "Dashboard de gestão limpo com cards, gráficos e filtros.",
    "ru": "Аккуратный дашборд управления с карточками, графиками и фильтрами.",
    "zh": "含卡片、图表和筛选器的简洁管理仪表盘。",
    "ja": "カード、チャート、フィルター付きのすっきりした管理ダッシュボード。",
    "ar": "لوحة إدارة أنيقة ببطاقات ورسوم بيانية ومرشّحات."
  },
  "Aesthetic portfolio showcasing CV and projects.": {
    "tr": "CV ve projelerini sergileyen estetik web sitesi.",
    "es": "Portafolio estético que muestra tu CV y proyectos.",
    "fr": "Portfolio esthétique présentant CV et projets.",
    "de": "Ästhetisches Portfolio, das Lebenslauf und Projekte präsentiert.",
    "pt": "Portfólio estético exibindo currículo e projetos.",
    "ru": "Эстетичное портфолио с резюме и проектами.",
    "zh": "展示简历与项目的美观作品集。",
    "ja": "職務経歴とプロジェクトを見せる洗練されたポートフォリオ。",
    "ar": "معرض أعمال جمالي يعرض السيرة الذاتية والمشاريع."
  },
  "Modern login page with animations and form validation.": {
    "tr": "Animasyonlu ve doğrulamalı modern giriş arayüzü.",
    "es": "Página de inicio de sesión moderna con animaciones y validación de formulario.",
    "fr": "Page de connexion moderne avec animations et validation de formulaire.",
    "de": "Moderne Login-Seite mit Animationen und Formularvalidierung.",
    "pt": "Página de login moderna com animações e validação de formulário.",
    "ru": "Современная страница входа с анимациями и валидацией формы.",
    "zh": "带动画和表单校验的现代登录页。",
    "ja": "アニメーションとフォームバリデーション付きのモダンなログインページ。",
    "ar": "صفحة تسجيل دخول عصرية برسوم متحركة والتحقق من النموذج."
  },
  "Design a modern, minimalist technology landing page with light/dark support using React and Tailwind CSS. Add nice animations and responsive design.": {
    "tr": "React ve Tailwind CSS kullanarak modern, minimalist ve karanlık mod destekli bir teknoloji landing page tasarla. Harika animasyonlar ve responsive tasarım olsun.",
    "es": "Diseña una landing page de tecnología moderna y minimalista con soporte claro/oscuro usando React y Tailwind CSS. Añade buenas animaciones y diseño responsivo.",
    "fr": "Conçois une landing page techno moderne et minimaliste avec prise en charge clair/sombre en React et Tailwind CSS. Ajoute de belles animations et un design responsive.",
    "de": "Gestalte eine moderne, minimalistische Technologie-Landing-Page mit Hell-/Dunkel-Unterstützung mit React und Tailwind CSS. Füge schöne Animationen und responsives Design hinzu.",
    "pt": "Crie uma landing page de tecnologia moderna e minimalista com suporte a tema claro/escuro usando React e Tailwind CSS. Adicione animações bonitas e design responsivo.",
    "ru": "Создай современный минималистичный технологический лендинг с поддержкой светлой/тёмной темы на React и Tailwind CSS. Добавь красивые анимации и адаптивный дизайн.",
    "zh": "用 React 和 Tailwind CSS 设计一个现代、极简、支持浅色/深色的科技落地页。加入精美动画和响应式设计。",
    "ja": "ReactとTailwind CSSを使い、ライト/ダーク対応のモダンでミニマルなテクノロジー系ランディングページをデザインして。素敵なアニメーションとレスポンシブデザインを加えて。",
    "ar": "صمّم صفحة هبوط تقنية عصرية بسيطة بدعم للوضعين الفاتح/الداكن باستخدام React وTailwind CSS. أضف رسومًا متحركة أنيقة وتصميمًا متجاوبًا."
  },
  "Design a clean data management dashboard interface with cards, filters, and mock data.": {
    "tr": "Güzel kartlar, filtre kontrolleri ve mock veri içeren temiz bir veri yönetim paneli (dashboard) arayüzü tasarla.",
    "es": "Diseña una interfaz de dashboard de gestión de datos limpia con tarjetas, filtros y datos de prueba.",
    "fr": "Conçois une interface de dashboard de gestion de données épurée avec cartes, filtres et données fictives.",
    "de": "Gestalte eine übersichtliche Dashboard-Oberfläche zur Datenverwaltung mit Karten, Filtern und Beispieldaten.",
    "pt": "Crie uma interface de dashboard de gestão de dados limpa com cards, filtros e dados fictícios.",
    "ru": "Создай аккуратный интерфейс дашборда управления данными с карточками, фильтрами и тестовыми данными.",
    "zh": "设计一个简洁的数据管理仪表盘界面，包含卡片、筛选器和模拟数据。",
    "ja": "カード、フィルター、モックデータを備えたすっきりしたデータ管理ダッシュボード画面をデザインして。",
    "ar": "صمّم واجهة لوحة إدارة بيانات أنيقة ببطاقات ومرشّحات وبيانات وهمية."
  },
  "Design a sleek personal portfolio page showcasing works, skills, and a contact form.": {
    "tr": "Çalışmalarımı, yeteneklerimi ve iletişim formunu içeren şık ve modern bir kişisel portfolyo sayfası tasarla.",
    "es": "Diseña una página de portafolio personal elegante que muestre trabajos, habilidades y un formulario de contacto.",
    "fr": "Conçois une page de portfolio personnel élégante présentant travaux, compétences et un formulaire de contact.",
    "de": "Gestalte eine elegante persönliche Portfolio-Seite, die Arbeiten, Fähigkeiten und ein Kontaktformular präsentiert.",
    "pt": "Crie uma página de portfólio pessoal elegante exibindo trabalhos, habilidades e um formulário de contato.",
    "ru": "Создай элегантную страницу личного портфолио с работами, навыками и формой обратной связи.",
    "zh": "设计一个精致的个人作品集页面，展示作品、技能和联系表单。",
    "ja": "作品、スキル、お問い合わせフォームを見せる洗練されたパーソナルポートフォリオページをデザインして。",
    "ar": "صمّم صفحة معرض أعمال شخصي أنيقة تعرض الأعمال والمهارات ونموذج تواصل."
  },
  "Design a sleek login screen with social auth integration and input validation utilizing a glassmorphism style.": {
    "tr": "Sosyal medya girişleri ve form doğrulaması bulunan, cam morumsu (glassmorphism) efektli şık bir Login ekranı tasarla.",
    "es": "Diseña una pantalla de inicio de sesión elegante con integración de autenticación social y validación de entradas, usando un estilo glassmorphism.",
    "fr": "Conçois un écran de connexion élégant avec authentification sociale et validation des champs, dans un style glassmorphism.",
    "de": "Gestalte einen eleganten Login-Screen mit Social-Auth-Integration und Eingabevalidierung im Glassmorphism-Stil.",
    "pt": "Crie uma tela de login elegante com integração de autenticação social e validação de entrada, usando estilo glassmorphism.",
    "ru": "Создай стильный экран входа с интеграцией входа через соцсети и валидацией полей в стиле glassmorphism.",
    "zh": "设计一个精致的登录界面，集成社交登录和输入校验，采用毛玻璃（glassmorphism）风格。",
    "ja": "ソーシャル認証連携と入力バリデーションを備え、グラスモーフィズムのスタイルを活かした洗練されたログイン画面をデザインして。",
    "ar": "صمّم شاشة تسجيل دخول أنيقة بتكامل مصادقة اجتماعية والتحقق من الإدخال بأسلوب glassmorphism."
  },
  "en-US": {
    "tr": "tr-TR",
    "es": "es-ES",
    "fr": "fr-FR",
    "de": "de-DE",
    "pt": "pt-BR",
    "ru": "ru-RU",
    "zh": "zh-CN",
    "ja": "ja-JP",
    "ar": "ar-SA"
  },
  "Remember this? ": {
    "tr": "Bunu hatırla? ",
    "es": "¿Recordar esto? ",
    "fr": "S'en souvenir ? ",
    "de": "Das merken? ",
    "pt": "Lembrar disso? ",
    "ru": "Запомнить это? ",
    "zh": "记住这个？ ",
    "ja": "これを覚えておく？ ",
    "ar": "أتتذكر هذا؟ "
  },
  "Approve": {
    "tr": "Onayla",
    "es": "Aprobar",
    "fr": "Approuver",
    "de": "Genehmigen",
    "pt": "Aprovar",
    "ru": "Одобрить",
    "zh": "批准",
    "ja": "承認",
    "ar": "موافقة"
  },
  "Dismiss": {
    "tr": "Yoksay",
    "es": "Descartar",
    "fr": "Ignorer",
    "de": "Verwerfen",
    "pt": "Descartar",
    "ru": "Пропустить",
    "zh": "忽略",
    "ja": "却下",
    "ar": "تجاهل"
  },
  "comment(s) queued": {
    "tr": "yorum sırada",
    "es": "comentario(s) en cola",
    "fr": "commentaire(s) en file",
    "de": "Kommentar(e) in Warteschlange",
    "pt": "comentário(s) na fila",
    "ru": "комментариев в очереди",
    "zh": "条评论已排队",
    "ja": "件のコメントが待機中",
    "ar": "تعليق(ات) في الطابور"
  },
  "attaches to the next turn": {
    "tr": "sonraki tura iliştirilecek",
    "es": "se adjunta al siguiente turno",
    "fr": "sera joint au prochain tour",
    "de": "wird an den nächsten Durchlauf angehängt",
    "pt": "anexa-se ao próximo turno",
    "ru": "прикрепится к следующему ходу",
    "zh": "将附加到下一轮",
    "ja": "次のターンに添付されます",
    "ar": "يُرفق بالدور التالي"
  },
  "Apply now": {
    "tr": "Şimdi uygula",
    "es": "Aplicar ahora",
    "fr": "Appliquer maintenant",
    "de": "Jetzt anwenden",
    "pt": "Aplicar agora",
    "ru": "Применить сейчас",
    "zh": "立即应用",
    "ja": "今すぐ適用",
    "ar": "طبّق الآن"
  },
  "Discard comments": {
    "tr": "Yorumları sil",
    "es": "Descartar comentarios",
    "fr": "Supprimer les commentaires",
    "de": "Kommentare verwerfen",
    "pt": "Descartar comentários",
    "ru": "Удалить комментарии",
    "zh": "丢弃评论",
    "ja": "コメントを破棄",
    "ar": "تجاهل التعليقات"
  },
  "will be analyzed with your message": {
    "tr": "mesajla birlikte analiz edilecek",
    "es": "se analizará junto con tu mensaje",
    "fr": "sera analysé avec votre message",
    "de": "wird mit deiner Nachricht analysiert",
    "pt": "será analisado junto com sua mensagem",
    "ru": "будет проанализировано вместе с вашим сообщением",
    "zh": "将与你的消息一起分析",
    "ja": "メッセージと一緒に分析されます",
    "ar": "سيُحلَّل مع رسالتك"
  },
  "turn running — Enter queues your text as a TASK": {
    "tr": "tur koşuyor — Enter yazdığını GÖREV olarak kuyruğa ekler",
    "es": "turno en curso — Enter pone tu texto en cola como TAREA",
    "fr": "tour en cours — Entrée met votre texte en file comme TÂCHE",
    "de": "Durchlauf läuft — Enter stellt deinen Text als AUFGABE in die Warteschlange",
    "pt": "turno em execução — Enter enfileira seu texto como TAREFA",
    "ru": "ход выполняется — Enter добавит текст как ЗАДАЧУ",
    "zh": "本轮运行中 — 按 Enter 将你的文本作为任务排队",
    "ja": "ターン実行中 — Enterで入力内容をタスクとしてキューに追加",
    "ar": "الدور قيد التشغيل — يضع Enter نصك في الطابور كمهمة"
  },
  "Search for models": {
    "tr": "Arama yapın",
    "es": "Buscar modelos",
    "fr": "Rechercher des modèles",
    "de": "Nach Modellen suchen",
    "pt": "Buscar modelos",
    "ru": "Поиск моделей",
    "zh": "搜索模型",
    "ja": "モデルを検索",
    "ar": "ابحث عن نماذج"
  },
  "downloads": {
    "tr": "indirme",
    "es": "descargas",
    "fr": "téléchargements",
    "de": "Downloads",
    "pt": "downloads",
    "ru": "загрузок",
    "zh": "下载量",
    "ja": "ダウンロード数",
    "ar": "تنزيلات"
  },
  "No downloaded models yet": {
    "tr": "Henüz indirilen model yok",
    "es": "Aún no hay modelos descargados",
    "fr": "Aucun modèle téléchargé",
    "de": "Noch keine heruntergeladenen Modelle",
    "pt": "Nenhum modelo baixado ainda",
    "ru": "Скачанных моделей пока нет",
    "zh": "尚无已下载的模型",
    "ja": "ダウンロード済みのモデルはまだありません",
    "ar": "لا توجد نماذج مُنزَّلة بعد"
  },
  "why asking: ": {
    "tr": "neden soruluyor: ",
    "es": "por qué se pregunta: ",
    "fr": "raison de la demande : ",
    "de": "warum gefragt: ",
    "pt": "por que perguntar: ",
    "ru": "почему спрашиваю: ",
    "zh": "询问原因： ",
    "ja": "確認理由： ",
    "ar": "سبب السؤال: "
  },
  "General": {
    "tr": "Genel",
    "es": "General",
    "fr": "Général",
    "de": "Allgemein",
    "pt": "Geral",
    "ru": "Общие",
    "zh": "通用",
    "ja": "一般",
    "ar": "عام"
  },
  "Providers": {
    "tr": "Sağlayıcılar",
    "es": "Proveedores",
    "fr": "Fournisseurs",
    "de": "Anbieter",
    "pt": "Provedores",
    "ru": "Провайдеры",
    "zh": "提供方",
    "ja": "プロバイダー",
    "ar": "المزوّدون"
  },
  "Models": {
    "tr": "Modeller",
    "es": "Modelos",
    "fr": "Modèles",
    "de": "Modelle",
    "pt": "Modelos",
    "ru": "Модели",
    "zh": "模型",
    "ja": "モデル",
    "ar": "النماذج"
  },
  "Trust & Permissions": {
    "tr": "Güven & İzinler",
    "es": "Confianza y permisos",
    "fr": "Confiance & Autorisations",
    "de": "Vertrauen & Berechtigungen",
    "pt": "Confiança e permissões",
    "ru": "Доверие и разрешения",
    "zh": "信任与权限",
    "ja": "信頼と権限",
    "ar": "الثقة والأذونات"
  },
  "Prompt & Rules": {
    "tr": "Prompt & Kurallar",
    "es": "Prompt y reglas",
    "fr": "Prompt & Règles",
    "de": "Prompt & Regeln",
    "pt": "Prompt e regras",
    "ru": "Промпт и правила",
    "zh": "提示词与规则",
    "ja": "プロンプトとルール",
    "ar": "الموجّه والقواعد"
  },
  "Knowledge": {
    "tr": "Bilgi Tabanı",
    "es": "Conocimiento",
    "fr": "Connaissances",
    "de": "Wissen",
    "pt": "Conhecimento",
    "ru": "База знаний",
    "zh": "知识库",
    "ja": "ナレッジ",
    "ar": "قاعدة المعرفة"
  },
  "Tools": {
    "tr": "Araçlar",
    "es": "Herramientas",
    "fr": "Outils",
    "de": "Werkzeuge",
    "pt": "Ferramentas",
    "ru": "Инструменты",
    "zh": "工具",
    "ja": "ツール",
    "ar": "الأدوات"
  },
  "Commands": {
    "tr": "Komutlar",
    "es": "Comandos",
    "fr": "Commandes",
    "de": "Befehle",
    "pt": "Comandos",
    "ru": "Команды",
    "zh": "命令",
    "ja": "コマンド",
    "ar": "الأوامر"
  },
  "Appearance": {
    "tr": "Görünüm",
    "es": "Apariencia",
    "fr": "Apparence",
    "de": "Erscheinungsbild",
    "pt": "Aparência",
    "ru": "Внешний вид",
    "zh": "外观",
    "ja": "外観",
    "ar": "المظهر"
  },
  "Theme": {
    "tr": "Tema",
    "es": "Tema",
    "fr": "Thème",
    "de": "Design",
    "pt": "Tema",
    "ru": "Тема",
    "zh": "主题",
    "ja": "テーマ",
    "ar": "السمة"
  },
  "Light": {
    "tr": "Açık",
    "es": "Claro",
    "fr": "Clair",
    "de": "Hell",
    "pt": "Claro",
    "ru": "Светлая",
    "zh": "浅色",
    "ja": "ライト",
    "ar": "فاتح"
  },
  "Dark": {
    "tr": "Koyu",
    "es": "Oscuro",
    "fr": "Sombre",
    "de": "Dunkel",
    "pt": "Escuro",
    "ru": "Тёмная",
    "zh": "深色",
    "ja": "ダーク",
    "ar": "داكن"
  },
  "Language": {
    "tr": "Dil",
    "es": "Idioma",
    "fr": "Langue",
    "de": "Sprache",
    "pt": "Idioma",
    "ru": "Язык",
    "zh": "语言",
    "ja": "言語",
    "ar": "اللغة"
  },
  "text-ink-dim hover:text-ink-mut": {
    "tr": "bg-ink-card text-ink-text shadow-sm",
    "es": "text-ink-dim hover:text-ink-mut",
    "fr": "text-ink-dim hover:text-ink-mut",
    "de": "text-ink-dim hover:text-ink-mut",
    "pt": "text-ink-dim hover:text-ink-mut",
    "ru": "text-ink-dim hover:text-ink-mut",
    "zh": "text-ink-dim hover:text-ink-mut",
    "ja": "bg-ink-card text-ink-text shadow-sm",
    "ar": "text-ink-dim hover:text-ink-mut"
  },
  "Interface Size": {
    "tr": "Arayüz Boyutu",
    "es": "Tamaño de interfaz",
    "fr": "Taille de l'interface",
    "de": "Oberflächengröße",
    "pt": "Tamanho da interface",
    "ru": "Размер интерфейса",
    "zh": "界面大小",
    "ja": "インターフェースのサイズ",
    "ar": "حجم الواجهة"
  },
  "Enlarge if text and the whole UI (sidebar, chat, tabs) feel too small. Shortcut: Ctrl with + / − / 0.": {
    "tr": "Yazılar ve tüm arayüz (sidebar, sohbet, sekmeler) küçük geliyorsa büyüt. Kısayol: Ctrl ile + / − / 0.",
    "es": "Amplía si el texto y toda la interfaz (barra lateral, chat, pestañas) se ven demasiado pequeños. Atajo: Ctrl con + / − / 0.",
    "fr": "Agrandissez si le texte et toute l'interface (barre latérale, discussion, onglets) semblent trop petits. Raccourci : Ctrl avec + / − / 0.",
    "de": "Vergrößern, wenn Text und die gesamte Oberfläche (Seitenleiste, Chat, Tabs) zu klein wirken. Kürzel: Strg mit + / − / 0.",
    "pt": "Aumente se o texto e toda a interface (barra lateral, chat, abas) parecerem pequenos demais. Atalho: Ctrl com + / − / 0.",
    "ru": "Увеличьте, если текст и весь интерфейс (боковая панель, чат, вкладки) кажутся мелкими. Горячие клавиши: Ctrl с + / − / 0.",
    "zh": "若文字和整个界面（侧栏、对话、标签页）显得太小，可放大。快捷键：Ctrl 加 + / − / 0。",
    "ja": "文字やUI全体（サイドバー、チャット、タブ）が小さすぎると感じたら拡大してください。ショートカット：Ctrl と + / − / 0。",
    "ar": "كبّر إذا بدا النص وكامل الواجهة (الشريط الجانبي، المحادثة، الألسنة) صغيرًا جدًا. الاختصار: Ctrl مع + / − / 0."
  },
  "Smaller (Ctrl −)": {
    "tr": "Küçült (Ctrl −)",
    "es": "Reducir (Ctrl −)",
    "fr": "Réduire (Ctrl −)",
    "de": "Kleiner (Strg −)",
    "pt": "Menor (Ctrl −)",
    "ru": "Меньше (Ctrl −)",
    "zh": "缩小（Ctrl −）",
    "ja": "小さく（Ctrl −）",
    "ar": "أصغر (Ctrl −)"
  },
  "Larger (Ctrl +)": {
    "tr": "Büyüt (Ctrl +)",
    "es": "Ampliar (Ctrl +)",
    "fr": "Agrandir (Ctrl +)",
    "de": "Größer (Strg +)",
    "pt": "Maior (Ctrl +)",
    "ru": "Больше (Ctrl +)",
    "zh": "放大（Ctrl +）",
    "ja": "大きく（Ctrl +）",
    "ar": "أكبر (Ctrl +)"
  },
  "Ask before sending to the API (confirm with \"fix api\")": {
    "tr": "API'ye göndermeden önce sor (\"düzelt api\" ile onayla)",
    "es": "Preguntar antes de enviar a la API (confirma con \"fix api\")",
    "fr": "Demander avant l'envoi à l'API (confirmer avec « fix api »)",
    "de": "Vor dem Senden an die API fragen (mit \"fix api\" bestätigen)",
    "pt": "Perguntar antes de enviar para a API (confirme com \"fix api\")",
    "ru": "Спрашивать перед отправкой в API (подтвердить командой \"fix api\")",
    "zh": "发送到 API 前询问（用“fix api”确认）",
    "ja": "APIに送信する前に確認する（「fix api」で承認）",
    "ar": "اسأل قبل الإرسال إلى API (أكّد بكتابة \"fix api\")"
  },
  "What the agent may execute. Hard denies (root-path deletion, sudo, pipe-to-shell) never run in ANY tier.": {
    "tr": "Ajanın komut çalıştırma yetkisi. Koşulsuz yasaklar (kök yolu silme, sudo, boru-ile-kabuk) HİÇBİR kipte çalışmaz.",
    "es": "Lo que el agente puede ejecutar. Los bloqueos absolutos (borrado de ruta raíz, sudo, pipe-a-shell) nunca se ejecutan en NINGÚN nivel.",
    "fr": "Ce que l'agent peut exécuter. Les interdictions strictes (suppression de chemin racine, sudo, pipe-vers-shell) ne s'exécutent dans AUCUN niveau.",
    "de": "Was der Agent ausführen darf. Absolute Verbote (Löschen von Root-Pfaden, sudo, Pipe-to-Shell) laufen in KEINER Stufe.",
    "pt": "O que o agente pode executar. Bloqueios rígidos (exclusão de caminho raiz, sudo, pipe-para-shell) nunca são executados em NENHUM nível.",
    "ru": "Что агент может выполнять. Жёсткие запреты (удаление корневого пути, sudo, pipe-to-shell) не работают НИ в одном режиме.",
    "zh": "智能体可执行的操作。硬性禁止项（删除根路径、sudo、管道到 shell）在任何等级下都不会运行。",
    "ja": "エージェントが実行できる範囲。絶対拒否（ルートパスの削除、sudo、パイプ経由のシェル実行）はどのティアでも実行されません。",
    "ar": "ما يُسمح للوكيل بتنفيذه. المنع القاطع (حذف المسار الجذري، sudo، التوجيه إلى الطرفية) لا يعمل أبدًا في أي مستوى."
  },
  "Read Only": {
    "tr": "Salt Okunur",
    "es": "Solo lectura",
    "fr": "Lecture seule",
    "de": "Nur Lesen",
    "pt": "Somente leitura",
    "ru": "Только чтение",
    "zh": "只读",
    "ja": "読み取り専用",
    "ar": "قراءة فقط"
  },
  "no command/download runs — the agent only proposes": {
    "tr": "hiçbir komut/indirme çalışmaz — ajan yalnız önerir",
    "es": "no se ejecuta ningún comando/descarga — el agente solo propone",
    "fr": "aucune commande/téléchargement ne s'exécute — l'agent se contente de proposer",
    "de": "kein Befehl/Download läuft — der Agent schlägt nur vor",
    "pt": "nenhum comando/download é executado — o agente apenas propõe",
    "ru": "команды/загрузки не выполняются — агент только предлагает",
    "zh": "不运行任何命令/下载 — 智能体仅提出建议",
    "ja": "コマンドやダウンロードは実行されず、エージェントは提案のみ",
    "ar": "لا يُنفَّذ أي أمر/تنزيل — يكتفي الوكيل بالاقتراح"
  },
  "Auto (recommended)": {
    "tr": "Otomatik (önerilen)",
    "es": "Automático (recomendado)",
    "fr": "Auto (recommandé)",
    "de": "Auto (empfohlen)",
    "pt": "Automático (recomendado)",
    "ru": "Авто (рекомендуется)",
    "zh": "自动（推荐）",
    "ja": "自動（推奨）",
    "ar": "تلقائي (موصى به)"
  },
  "safe in-workspace commands run free; everything at the boundary asks": {
    "tr": "çalışma alanı içi güvenli komutlar serbest; sınırda olan her şey sorulur",
    "es": "los comandos seguros dentro del espacio de trabajo se ejecutan libremente; todo lo que esté en el límite se pregunta",
    "fr": "les commandes sûres dans l'espace de travail passent librement ; tout ce qui touche la limite est soumis à confirmation",
    "de": "sichere Befehle im Arbeitsbereich laufen frei; alles an der Grenze wird nachgefragt",
    "pt": "comandos seguros dentro do espaço de trabalho rodam livremente; tudo que está no limite é perguntado",
    "ru": "безопасные команды внутри рабочей области выполняются свободно; всё на границе — по запросу",
    "zh": "工作区内的安全命令自由运行；边界上的一切都会询问",
    "ja": "ワークスペース内の安全なコマンドは自由に実行、境界にあるものはすべて確認",
    "ar": "تُنفَّذ الأوامر الآمنة داخل مساحة العمل بحرية؛ وكل ما على الحدود يُستأذن فيه"
  },
  "Full Access": {
    "tr": "Tam Erişim",
    "es": "Acceso total",
    "fr": "Accès complet",
    "de": "Vollzugriff",
    "pt": "Acesso total",
    "ru": "Полный доступ",
    "zh": "完全访问",
    "ja": "フルアクセス",
    "ar": "وصول كامل"
  },
  "boundary items run unasked — hard denies still never run": {
    "tr": "sınırdakiler de onaysız koşar — koşulsuz yasaklar yine çalışmaz",
    "es": "los elementos del límite se ejecutan sin preguntar — los bloqueos absolutos siguen sin ejecutarse nunca",
    "fr": "les éléments à la limite s'exécutent sans demande — les interdictions strictes restent bloquées",
    "de": "Grenzfälle laufen ohne Nachfrage — absolute Verbote laufen weiterhin nie",
    "pt": "itens no limite rodam sem perguntar — bloqueios rígidos ainda nunca são executados",
    "ru": "граничные действия выполняются без запроса — жёсткие запреты всё равно не работают",
    "zh": "边界项无需询问即运行 — 硬性禁止项仍绝不运行",
    "ja": "境界の項目も確認なしで実行 — 絶対拒否は依然として実行されません",
    "ar": "تُنفَّذ العناصر الحدّية دون سؤال — أما المنع القاطع فلا يعمل أبدًا"
  },
  "Allow list (one prefix per line)": {
    "tr": "İzin listesi (satır başına önek)",
    "es": "Lista de permitidos (un prefijo por línea)",
    "fr": "Liste d'autorisation (un préfixe par ligne)",
    "de": "Erlaubnisliste (ein Präfix pro Zeile)",
    "pt": "Lista de permissões (um prefixo por linha)",
    "ru": "Список разрешённых (один префикс на строку)",
    "zh": "允许列表（每行一个前缀）",
    "ja": "許可リスト（1行に1プレフィックス）",
    "ar": "قائمة السماح (بادئة واحدة لكل سطر)"
  },
  "Deny list (blocks in every tier)": {
    "tr": "Yasak listesi (her kipte engel)",
    "es": "Lista de bloqueados (bloquea en todos los niveles)",
    "fr": "Liste d'interdiction (bloque à tous les niveaux)",
    "de": "Verbotsliste (blockiert in jeder Stufe)",
    "pt": "Lista de bloqueios (bloqueia em todos os níveis)",
    "ru": "Список запрещённых (блокирует во всех режимах)",
    "zh": "拒绝列表（在所有等级下阻止）",
    "ja": "拒否リスト（すべてのティアでブロック）",
    "ar": "قائمة المنع (تحظر في كل مستوى)"
  },
  "Engine Scorecard": {
    "tr": "Motor Karnesi",
    "es": "Boletín del motor",
    "fr": "Bulletin du moteur",
    "de": "Engine-Zeugnis",
    "pt": "Boletim do motor",
    "ru": "Табель движка",
    "zh": "引擎成绩单",
    "ja": "エンジンスコアカード",
    "ar": "بطاقة أداء المحرّك"
  },
  "The Debug Engine's real field performance on this device (from repair telemetry).": {
    "tr": "Debug Engine'in bu cihazdaki gerçek saha performansı (onarım telemetrisinden).",
    "es": "Rendimiento real del Debug Engine en este dispositivo (según la telemetría de reparaciones).",
    "fr": "Performances réelles du Debug Engine sur cet appareil (d'après la télémétrie de réparation).",
    "de": "Die reale Praxisleistung der Debug-Engine auf diesem Gerät (aus der Reparatur-Telemetrie).",
    "pt": "O desempenho real do Debug Engine neste dispositivo (a partir da telemetria de reparos).",
    "ru": "Реальная полевая производительность Debug Engine на этом устройстве (по телеметрии ремонта).",
    "zh": "Debug 引擎在本设备上的真实实战表现（来自修复遥测数据）。",
    "ja": "このデバイスでのDebug Engineの実際のフィールド性能（修復テレメトリより）。",
    "ar": "الأداء الميداني الحقيقي لمحرّك التصحيح على هذا الجهاز (من قياسات الإصلاح)."
  },
  "Total repair events": {
    "tr": "Toplam onarım olayı",
    "es": "Total de eventos de reparación",
    "fr": "Total des événements de réparation",
    "de": "Reparaturereignisse insgesamt",
    "pt": "Total de eventos de reparo",
    "ru": "Всего событий ремонта",
    "zh": "修复事件总数",
    "ja": "修復イベント合計",
    "ar": "إجمالي أحداث الإصلاح"
  },
  "Model-free repair hit rate (rung 0)": {
    "tr": "Modelsiz onarım isabeti (Kat 0)",
    "es": "Tasa de acierto de reparación sin modelo (nivel 0)",
    "fr": "Taux de réparation sans modèle (niveau 0)",
    "de": "Trefferquote modellfreie Reparatur (Stufe 0)",
    "pt": "Taxa de acerto de reparos sem modelo (nível 0)",
    "ru": "Доля попаданий ремонта без модели (уровень 0)",
    "zh": "无模型修复命中率（第 0 级）",
    "ja": "モデル不使用での修復成功率（rung 0）",
    "ar": "معدّل نجاح الإصلاح دون نموذج (المستوى 0)"
  },
  "Repro verification rate": {
    "tr": "Repro doğrulama oranı",
    "es": "Tasa de verificación de reproducción",
    "fr": "Taux de vérification par repro",
    "de": "Repro-Verifizierungsrate",
    "pt": "Taxa de verificação de repro",
    "ru": "Доля подтверждения репро",
    "zh": "复现验证率",
    "ja": "再現検証率",
    "ar": "معدّل التحقق من إعادة الإنتاج"
  },
  "Behavior test pass": {
    "tr": "Davranış testi geçme",
    "es": "Pruebas de comportamiento superadas",
    "fr": "Réussite des tests de comportement",
    "de": "Verhaltenstest bestanden",
    "pt": "Aprovação em teste de comportamento",
    "ru": "Прохождение теста поведения",
    "zh": "行为测试通过",
    "ja": "動作テスト合格",
    "ar": "نجاح اختبار السلوك"
  },
  "No telemetry yet — this fills as the engine works.": {
    "tr": "Henüz telemetri yok — motor çalıştıkça burası dolacak.",
    "es": "Aún no hay telemetría — se irá llenando a medida que el motor trabaje.",
    "fr": "Aucune télémétrie — se remplira à mesure que le moteur travaille.",
    "de": "Noch keine Telemetrie — füllt sich, während die Engine arbeitet.",
    "pt": "Nenhuma telemetria ainda — isto se preenche à medida que o motor trabalha.",
    "ru": "Телеметрии пока нет — заполнится по мере работы движка.",
    "zh": "暂无遥测数据 — 引擎运行时此处会填充。",
    "ja": "テレメトリはまだありません — エンジンが動作するにつれてここが埋まります。",
    "ar": "لا توجد قياسات بعد — يمتلئ هذا كلما عمل المحرّك."
  },
  "GPU Acceleration (Experimental)": {
    "tr": "GPU Hızlandırması (Deneysel)",
    "es": "Aceleración por GPU (experimental)",
    "fr": "Accélération GPU (expérimental)",
    "de": "GPU-Beschleunigung (experimentell)",
    "pt": "Aceleração por GPU (Experimental)",
    "ru": "Ускорение GPU (экспериментально)",
    "zh": "GPU 加速（实验性）",
    "ja": "GPUアクセラレーション（実験的）",
    "ar": "تسريع بمعالج الرسومات (تجريبي)"
  },
  "Uses graphics card (CUDA/Vulkan) for model operations. Keep disabled if you experience app crashes or errors during load.": {
    "tr": "Model işlemlerinde ekran kartını (CUDA/Vulkan) kullanır. Eğer uygulama açılırken çöküyorsa veya hata alıyorsanız kapalı tutun.",
    "es": "Usa la tarjeta gráfica (CUDA/Vulkan) para las operaciones del modelo. Mantenla desactivada si la app se cierra o da errores durante la carga.",
    "fr": "Utilise la carte graphique (CUDA/Vulkan) pour les opérations du modèle. Laissez désactivé si l'app plante ou renvoie des erreurs au chargement.",
    "de": "Nutzt die Grafikkarte (CUDA/Vulkan) für Modelloperationen. Deaktiviert lassen, falls die App beim Laden abstürzt oder Fehler auftreten.",
    "pt": "Usa a placa de vídeo (CUDA/Vulkan) para as operações do modelo. Mantenha desativado se a aplicação travar ou apresentar erros durante o carregamento.",
    "ru": "Использует видеокарту (CUDA/Vulkan) для операций модели. Оставьте выключенным, если приложение вылетает или выдаёт ошибки при загрузке.",
    "zh": "在模型运算中使用显卡（CUDA/Vulkan）。若加载时出现应用崩溃或错误，请保持关闭。",
    "ja": "モデル処理にグラフィックカード（CUDA/Vulkan）を使用します。読み込み中にアプリがクラッシュしたりエラーが出る場合は無効のままにしてください。",
    "ar": "يستخدم بطاقة الرسومات (CUDA/Vulkan) لعمليات النموذج. أبقِه معطّلًا إذا واجهت أعطالًا أو أخطاء أثناء التحميل."
  },
  "GPU Layers": {
    "tr": "GPU Katmanları",
    "es": "Capas de GPU",
    "fr": "Couches GPU",
    "de": "GPU-Layer",
    "pt": "Camadas da GPU",
    "ru": "Слои GPU",
    "zh": "GPU 层数",
    "ja": "GPUレイヤー",
    "ar": "طبقات GPU"
  },
  "Auto": {
    "tr": "Otomatik",
    "es": "Automático",
    "fr": "Auto",
    "de": "Auto",
    "pt": "Automático",
    "ru": "Авто",
    "zh": "自动",
    "ja": "自動",
    "ar": "تلقائي"
  },
  "How many model layers to offload to the GPU. Auto measures free VRAM and offloads as many layers as fit — partial speedup even on small cards. Takes effect on the next model load.": {
    "tr": "Modelin kaç katmanı ekran kartına yüklensin? Otomatik: boş VRAM ölçülür, sığan kadar katman GPU’ya verilir — küçük kartlarda bile kısmi hızlanma sağlar. Yeni model yüklemesinde geçerli olur.",
    "es": "Cuántas capas del modelo descargar a la GPU. Automático mide la VRAM libre y descarga tantas capas como quepan — aceleración parcial incluso en tarjetas pequeñas. Se aplica en la próxima carga del modelo.",
    "fr": "Nombre de couches du modèle à décharger sur le GPU. Auto mesure la VRAM libre et décharge autant de couches que possible — accélération partielle même sur les petites cartes. Prend effet au prochain chargement du modèle.",
    "de": "Wie viele Modell-Layer auf die GPU ausgelagert werden. Auto misst den freien VRAM und lagert so viele Layer aus, wie passen — teilweise Beschleunigung selbst auf kleinen Karten. Wird beim nächsten Laden des Modells wirksam.",
    "pt": "Quantas camadas do modelo descarregar na GPU. O modo Automático mede a VRAM livre e descarrega quantas camadas couberem — aceleração parcial mesmo em placas pequenas. Aplica-se no próximo carregamento do modelo.",
    "ru": "Сколько слоёв модели выгрузить на GPU. Авто измеряет свободную VRAM и выгружает столько слоёв, сколько поместится — частичное ускорение даже на слабых картах. Применяется при следующей загрузке модели.",
    "zh": "将多少个模型层卸载到 GPU。自动模式会测量空闲显存并尽量卸载 — 即便小显卡也能部分加速。下次加载模型时生效。",
    "ja": "モデルのレイヤーをいくつGPUにオフロードするか。自動：空きVRAMを計測し、収まるだけのレイヤーをオフロード — 小さなカードでも部分的に高速化します。次回のモデル読み込み時に反映されます。",
    "ar": "عدد طبقات النموذج التي تُنقل إلى GPU. يقيس الوضع التلقائي ذاكرة VRAM المتاحة وينقل ما يتّسع من الطبقات — تسريع جزئي حتى على البطاقات الصغيرة. يسري عند تحميل النموذج التالي."
  },
  "Local Vision Model (analysis)": {
    "tr": "Yerel Görsel Modeli (analiz)",
    "es": "Modelo de visión local (análisis)",
    "fr": "Modèle de vision local (analyse)",
    "de": "Lokales Vision-Modell (Analyse)",
    "pt": "Modelo de visão local (análise)",
    "ru": "Локальная модель зрения (анализ)",
    "zh": "本地视觉模型（分析）",
    "ja": "ローカルビジョンモデル（分析）",
    "ar": "نموذج الرؤية المحلي (التحليل)"
  },
  "The model that analyzes attached images LOCALLY (local-model only; on an API model the image goes straight to the API). Not fixed to Qwen — any VL GGUF you download (model + mmproj) shows up here. Auto: the largest installed model that fits RAM.": {
    "tr": "İliştirilen görselleri YEREL olarak analiz eden model (yalnız yerel modelde; API modelinde görsel doğrudan API’ye gider). Qwen’e sabit değil — indirdiğin herhangi bir VL GGUF (model + mmproj) burada çıkar. Oto: RAM’e sığan en büyük yüklü model.",
    "es": "El modelo que analiza las imágenes adjuntas LOCALMENTE (solo con modelo local; con un modelo de API la imagen va directa a la API). No está fijado a Qwen — cualquier VL GGUF que descargues (modelo + mmproj) aparece aquí. Automático: el modelo instalado más grande que quepa en la RAM.",
    "fr": "Le modèle qui analyse LOCALEMENT les images jointes (modèle local uniquement ; sur un modèle API, l'image va directement à l'API). Non limité à Qwen — tout GGUF VL téléchargé (modèle + mmproj) apparaît ici. Auto : le plus grand modèle installé tenant en RAM.",
    "de": "Das Modell, das angehängte Bilder LOKAL analysiert (nur beim lokalen Modell; bei einem API-Modell geht das Bild direkt an die API). Nicht auf Qwen festgelegt — jedes von dir heruntergeladene VL-GGUF (Modell + mmproj) erscheint hier. Auto: das größte installierte Modell, das in den RAM passt.",
    "pt": "O modelo que analisa imagens anexadas LOCALMENTE (apenas no modelo local; em um modelo de API a imagem vai direto para a API). Não está fixo no Qwen — qualquer GGUF de VL que você baixe (modelo + mmproj) aparece aqui. Automático: o maior modelo instalado que couber na RAM.",
    "ru": "Модель, анализирующая прикреплённые изображения ЛОКАЛЬНО (только для локальной модели; на API-модели изображение идёт прямо в API). Не привязана к Qwen — любой скачанный VL GGUF (модель + mmproj) появится здесь. Авто: крупнейшая установленная модель, помещающаяся в RAM.",
    "zh": "在本地分析所附图片的模型（仅本地模型；使用 API 模型时图片会直接发送到 API）。不限于 Qwen — 你下载的任何 VL GGUF（模型 + mmproj）都会显示在此。自动：内存能容纳的最大已安装模型。",
    "ja": "添付画像をローカルで分析するモデル（ローカルモデルのみ。APIモデルでは画像は直接APIに送られます）。Qwenに固定されておらず、ダウンロードした任意のVL GGUF（モデル + mmproj）がここに表示されます。自動：RAMに収まる最大のインストール済みモデル。",
    "ar": "النموذج الذي يحلّل الصور المرفقة محليًا (في النموذج المحلي فقط؛ أما في نموذج API فتذهب الصورة مباشرةً إلى API). ليس مقيّدًا بـQwen — أي VL GGUF تُنزّله (النموذج + mmproj) يظهر هنا. تلقائي: أكبر نموذج مثبَّت يتّسع في الذاكرة."
  },
  "Auto (largest that fits RAM)": {
    "tr": "Otomatik (RAM’e sığan en büyük)",
    "es": "Automático (el más grande que quepa en la RAM)",
    "fr": "Auto (le plus grand tenant en RAM)",
    "de": "Auto (größtes, das in den RAM passt)",
    "pt": "Automático (o maior que couber na RAM)",
    "ru": "Авто (крупнейшая, что помещается в RAM)",
    "zh": "自动（内存能容纳的最大者）",
    "ja": "自動（RAMに収まる最大のもの）",
    "ar": "تلقائي (الأكبر الذي يتّسع في الذاكرة)"
  },
  "No installed vision model found. A device-appropriate Qwen-VL downloads on first image analysis; or drop your own VL GGUF (model + mmproj) into the models folder.": {
    "tr": "Yüklü görsel modeli bulunamadı. İlk görsel analizinde cihazına uygun bir Qwen-VL otomatik iner; ya da models klasörüne kendi VL GGUF’unu (model + mmproj) koy.",
    "es": "No se encontró ningún modelo de visión instalado. Un Qwen-VL adecuado para tu dispositivo se descarga en el primer análisis de imagen; o coloca tu propio VL GGUF (modelo + mmproj) en la carpeta de modelos.",
    "fr": "Aucun modèle de vision installé. Un Qwen-VL adapté à l'appareil se télécharge lors de la première analyse d'image ; ou déposez votre propre GGUF VL (modèle + mmproj) dans le dossier des modèles.",
    "de": "Kein installiertes Vision-Modell gefunden. Bei der ersten Bildanalyse wird ein gerätepassendes Qwen-VL heruntergeladen; oder leg dein eigenes VL-GGUF (Modell + mmproj) in den Modellordner.",
    "pt": "Nenhum modelo de visão instalado encontrado. Um Qwen-VL adequado ao dispositivo é baixado na primeira análise de imagem; ou coloque seu próprio GGUF de VL (modelo + mmproj) na pasta de modelos.",
    "ru": "Установленная модель зрения не найдена. Подходящая устройству Qwen-VL скачается при первом анализе изображения; или поместите свой VL GGUF (модель + mmproj) в папку моделей.",
    "zh": "未找到已安装的视觉模型。首次图片分析时会自动下载适配设备的 Qwen-VL；或将你自己的 VL GGUF（模型 + mmproj）放入 models 文件夹。",
    "ja": "インストール済みのビジョンモデルが見つかりません。最初の画像分析時にデバイスに適したQwen-VLが自動でダウンロードされます。または独自のVL GGUF（モデル + mmproj）をmodelsフォルダーに配置してください。",
    "ar": "لم يُعثر على نموذج رؤية مثبّت. يُنزَّل Qwen-VL مناسب لجهازك عند أول تحليل صورة؛ أو ضع نموذج VL GGUF خاصًا بك (النموذج + mmproj) في مجلد النماذج."
  },
  "Global Rules": {
    "tr": "Global Kurallar",
    "es": "Reglas globales",
    "fr": "Règles globales",
    "de": "Globale Regeln",
    "pt": "Regras globais",
    "ru": "Глобальные правила",
    "zh": "全局规则",
    "ja": "グローバルルール",
    "ar": "القواعد العامة"
  },
  "Preferences that apply to EVERY project. On conflict the nearer (project) rule wins.": {
    "tr": "HER projede geçerli tercihler. Proje kuralıyla çelişirse yakın olan (proje) kazanır.",
    "es": "Preferencias que se aplican a TODOS los proyectos. En caso de conflicto, gana la regla más cercana (la del proyecto).",
    "fr": "Préférences appliquées à TOUS les projets. En cas de conflit, la règle la plus proche (projet) l'emporte.",
    "de": "Vorgaben, die für JEDES Projekt gelten. Bei Konflikt gewinnt die nähere (Projekt-)Regel.",
    "pt": "Preferências que se aplicam a TODOS os projetos. Em caso de conflito, a regra mais próxima (do projeto) prevalece.",
    "ru": "Предпочтения, применяемые к КАЖДОМУ проекту. При конфликте побеждает более близкое (проектное) правило.",
    "zh": "适用于每个项目的偏好。冲突时，更近的（项目）规则优先。",
    "ja": "すべてのプロジェクトに適用される設定。競合した場合はより近い（プロジェクトの）ルールが優先されます。",
    "ar": "تفضيلات تنطبق على كل مشروع. عند التعارض تفوز القاعدة الأقرب (قاعدة المشروع)."
  },
  "e.g. Always Turkish comments; never skip a11y labels": {
    "tr": "ör. Her zaman Türkçe yorum satırları; erişilebilirlik etiketlerini atlama",
    "es": "p. ej. Comentarios siempre en español; nunca omitas etiquetas de accesibilidad",
    "fr": "ex. Toujours des commentaires en français ; ne jamais omettre les libellés d'accessibilité",
    "de": "z. B. Kommentare immer auf Deutsch; a11y-Labels nie weglassen",
    "pt": "ex.: Sempre comentários em português; nunca omitir rótulos de acessibilidade",
    "ru": "напр.: Всегда комментарии на русском; никогда не пропускай метки доступности",
    "zh": "例如：注释始终用中文；切勿省略无障碍标签",
    "ja": "例：コメントは常に日本語で；アクセシビリティラベルを省略しない",
    "ar": "مثال: تعليقات بالعربية دائمًا؛ لا تتجاوز تسميات الوصول (a11y)"
  },
  "Project Knowledge Base": {
    "tr": "Proje Bilgi Tabanı",
    "es": "Base de conocimiento del proyecto",
    "fr": "Base de connaissances du projet",
    "de": "Projekt-Wissensbasis",
    "pt": "Base de conhecimento do projeto",
    "ru": "База знаний проекта",
    "zh": "项目知识库",
    "ja": "プロジェクトナレッジベース",
    "ar": "قاعدة معرفة المشروع"
  },
  "The engine records what it PROVED here (repair patterns, verified fixes, your review comments) and summarizes them into every turn. Refuted items retire automatically; delete any by hand.": {
    "tr": "Motor bu projede kanıtla öğrendiklerini buraya yazar (onarım kalıpları, doğrulanmış düzeltmeler, senin inceleme yorumların) ve her turun başına özetler. Yanlışlanan madde otomatik emekli olur; istediğini elle de silebilirsin.",
    "es": "El motor registra aquí lo que ha DEMOSTRADO (patrones de reparación, correcciones verificadas, tus comentarios de revisión) y los resume en cada turno. Los elementos refutados se retiran automáticamente; puedes eliminar cualquiera a mano.",
    "fr": "Le moteur consigne ici ce qu'il a PROUVÉ (schémas de réparation, correctifs vérifiés, vos commentaires d'examen) et les résume à chaque tour. Les éléments réfutés se retirent automatiquement ; supprimez-en manuellement au besoin.",
    "de": "Die Engine hält fest, was sie hier BEWIESEN hat (Reparaturmuster, verifizierte Fixes, deine Prüfkommentare) und fasst es in jeden Durchlauf ein. Widerlegte Einträge werden automatisch ausgemustert; einzelne kannst du von Hand löschen.",
    "pt": "O motor registra aqui o que COMPROVOU (padrões de reparo, correções verificadas, seus comentários de revisão) e os resume em cada turno. Itens refutados se aposentam automaticamente; exclua qualquer um manualmente.",
    "ru": "Движок записывает сюда то, что ДОКАЗАЛ (шаблоны ремонта, подтверждённые исправления, ваши комментарии из проверок) и включает это в каждый ход. Опровергнутые пункты выбывают автоматически; любой можно удалить вручную.",
    "zh": "引擎会把在此已验证的内容记录下来（修复模式、已验证的修复、你的评审评论），并在每一轮开头汇总。被推翻的条目会自动退役；也可手动删除任意条目。",
    "ja": "エンジンがこのプロジェクトで実証したこと（修復パターン、検証済みの修正、あなたのレビューコメント）をここに記録し、毎ターンの冒頭に要約します。反証された項目は自動的に引退します。手動で削除することもできます。",
    "ar": "يسجّل المحرّك هنا ما أثبته (أنماط الإصلاح، الإصلاحات المتحقَّق منها، تعليقات مراجعتك) ويلخّصها في كل دور. تتقاعد العناصر المدحوضة تلقائيًا؛ ويمكنك حذف أي عنصر يدويًا."
  },
  "No items yet — fills as the engine repairs and you comment.": {
    "tr": "Henüz madde yok — motor onardıkça ve sen yorumladıkça dolacak.",
    "es": "Aún no hay elementos — se llena a medida que el motor repara y tú comentas.",
    "fr": "Aucun élément — se remplit à mesure que le moteur répare et que vous commentez.",
    "de": "Noch keine Einträge — füllt sich, während die Engine repariert und du kommentierst.",
    "pt": "Nenhum item ainda — preenche-se à medida que o motor repara e você comenta.",
    "ru": "Пунктов пока нет — заполнится по мере ремонта движком и ваших комментариев.",
    "zh": "暂无条目 — 随引擎修复与你的评论逐渐填充。",
    "ja": "項目はまだありません — エンジンが修復し、あなたがコメントするにつれて埋まります。",
    "ar": "لا توجد عناصر بعد — يمتلئ كلما أصلح المحرّك وعلّقتَ أنت."
  },
  "Delete item": {
    "tr": "Maddeyi sil",
    "es": "Eliminar elemento",
    "fr": "Supprimer l'élément",
    "de": "Eintrag löschen",
    "pt": "Excluir item",
    "ru": "Удалить пункт",
    "zh": "删除条目",
    "ja": "項目を削除",
    "ar": "حذف العنصر"
  },
  "System": {
    "tr": "Sistem",
    "es": "Sistema",
    "fr": "Système",
    "de": "System",
    "pt": "Sistema",
    "ru": "Система",
    "zh": "系统",
    "ja": "システム",
    "ar": "النظام"
  },
  "Notify when a long run finishes (if backgrounded)": {
    "tr": "Uzun koşu bitince bildir (pencere arka plandaysa)",
    "es": "Notificar cuando termine una ejecución larga (si está en segundo plano)",
    "fr": "Notifier à la fin d'une exécution longue (si en arrière-plan)",
    "de": "Benachrichtigen, wenn ein langer Durchlauf endet (bei Fenster im Hintergrund)",
    "pt": "Notificar quando uma execução longa terminar (se em segundo plano)",
    "ru": "Уведомлять, когда завершится долгий запуск (если окно свёрнуто)",
    "zh": "长任务完成时通知（若窗口在后台）",
    "ja": "長い処理が完了したら通知（バックグラウンド時）",
    "ar": "أبلغني عند انتهاء عملية طويلة (إن كانت في الخلفية)"
  },
  "Keep the machine awake during runs": {
    "tr": "Koşarken makinenin uyumasını engelle",
    "es": "Mantener el equipo activo durante las ejecuciones",
    "fr": "Empêcher la mise en veille de la machine pendant les exécutions",
    "de": "Gerät während der Durchläufe wach halten",
    "pt": "Manter a máquina ativa durante as execuções",
    "ru": "Не давать компьютеру засыпать во время запусков",
    "zh": "运行期间保持机器唤醒",
    "ja": "処理中はマシンをスリープさせない",
    "ar": "أبقِ الجهاز مستيقظًا أثناء عمليات التشغيل"
  },
  "project": {
    "tr": "proje",
    "es": "proyecto",
    "fr": "projet",
    "de": "Projekt",
    "pt": "projeto",
    "ru": "проект",
    "zh": "项目",
    "ja": "プロジェクト",
    "ar": "مشروع"
  },
  "Untitled": {
    "tr": "Adsız",
    "es": "Sin título",
    "fr": "Sans titre",
    "de": "Ohne Titel",
    "pt": "Sem título",
    "ru": "Без названия",
    "zh": "未命名",
    "ja": "無題",
    "ar": "بلا عنوان"
  },
  "Open Project": {
    "tr": "Proje Aç",
    "es": "Abrir proyecto",
    "fr": "Ouvrir un projet",
    "de": "Projekt öffnen",
    "pt": "Abrir projeto",
    "ru": "Открыть проект",
    "zh": "打开项目",
    "ja": "プロジェクトを開く",
    "ar": "فتح مشروع"
  },
  "Projects": {
    "tr": "Projeler",
    "es": "Proyectos",
    "fr": "Projets",
    "de": "Projekte",
    "pt": "Projetos",
    "ru": "Проекты",
    "zh": "项目",
    "ja": "プロジェクト",
    "ar": "المشاريع"
  },
  "No projects yet": {
    "tr": "Henüz proje yok",
    "es": "Aún no hay proyectos",
    "fr": "Aucun projet",
    "de": "Noch keine Projekte",
    "pt": "Nenhum projeto ainda",
    "ru": "Проектов пока нет",
    "zh": "暂无项目",
    "ja": "プロジェクトはまだありません",
    "ar": "لا توجد مشاريع بعد"
  },
  "linked": {
    "tr": "bagli",
    "es": "vinculado",
    "fr": "lié",
    "de": "verknüpft",
    "pt": "vinculado",
    "ru": "связано",
    "zh": "已关联",
    "ja": "リンク済み",
    "ar": "مرتبط"
  },
  "New session in this project": {
    "tr": "Bu projede yeni oturum",
    "es": "Nueva sesión en este proyecto",
    "fr": "Nouvelle session dans ce projet",
    "de": "Neue Sitzung in diesem Projekt",
    "pt": "Nova sessão neste projeto",
    "ru": "Новая сессия в этом проекте",
    "zh": "在此项目中新建会话",
    "ja": "このプロジェクトで新規セッション",
    "ar": "جلسة جديدة في هذا المشروع"
  },
  "No sessions": {
    "tr": "Oturum yok",
    "es": "Sin sesiones",
    "fr": "Aucune session",
    "de": "Keine Sitzungen",
    "pt": "Sem sessões",
    "ru": "Сессий нет",
    "zh": "无会话",
    "ja": "セッションなし",
    "ar": "لا توجد جلسات"
  },
  "New session": {
    "tr": "Yeni oturum",
    "es": "Nueva sesión",
    "fr": "Nouvelle session",
    "de": "Neue Sitzung",
    "pt": "Nova sessão",
    "ru": "Новая сессия",
    "zh": "新建会话",
    "ja": "新規セッション",
    "ar": "جلسة جديدة"
  },
  "Drag to resize": {
    "tr": "Sürükle: bölümleri boyutlandır",
    "es": "Arrastra para redimensionar",
    "fr": "Glisser pour redimensionner",
    "de": "Ziehen zum Anpassen der Größe",
    "pt": "Arraste para redimensionar",
    "ru": "Потяните, чтобы изменить размер",
    "zh": "拖动以调整大小",
    "ja": "ドラッグしてサイズ変更",
    "ar": "اسحب لتغيير الحجم"
  },
  "Command palette": {
    "tr": "Komut paleti",
    "es": "Paleta de comandos",
    "fr": "Palette de commandes",
    "de": "Befehlspalette",
    "pt": "Paleta de comandos",
    "ru": "Палитра команд",
    "zh": "命令面板",
    "ja": "コマンドパレット",
    "ar": "لوحة الأوامر"
  },
  "Measured on this device (Mini-benchmark)": {
    "tr": "Bu cihazda ölçüldü (Mini-test)",
    "es": "Medido en este dispositivo (mini-benchmark)",
    "fr": "Mesuré sur cet appareil (Mini-benchmark)",
    "de": "Auf diesem Gerät gemessen (Mini-Benchmark)",
    "pt": "Medido neste dispositivo (Mini-benchmark)",
    "ru": "Измерено на этом устройстве (мини-тест)",
    "zh": "已在本设备上测量（迷你基准测试）",
    "ja": "このデバイスで計測（ミニベンチマーク）",
    "ar": "قِيس على هذا الجهاز (اختبار مصغّر)"
  }
}
