import type { Lang } from './i18n'

// OTOMATIK URETILDI (gen-i18n.mjs) — satir-ici UI metinleri, Ingilizce anahtarli.
export const UI: Record<string, Partial<Record<Lang, string>>> = {
  "Speed": {
    "tr": "Hız", "es": "Velocidad", "fr": "Vitesse", "de": "Geschwindigkeit",
    "pt": "Velocidade", "ru": "Скорость", "zh": "速度", "ja": "速度", "ar": "السرعة"
  },
  "First token": {
    "tr": "İlk token", "es": "Primer token", "fr": "Premier jeton", "de": "Erstes Token",
    "pt": "Primeiro token", "ru": "Первый токен", "zh": "首个 token", "ja": "最初のトークン", "ar": "الرمز الأول"
  },
  "Turbo accepted": {
    "tr": "Turbo kabul", "es": "Turbo aceptado", "fr": "Turbo accepté", "de": "Turbo akzeptiert",
    "pt": "Turbo aceito", "ru": "Турбо принято", "zh": "Turbo 采纳", "ja": "Turbo 採用", "ar": "قبول تيربو"
  },
  "Turbo active": {
    "tr": "Turbo aktif", "es": "Turbo activo", "fr": "Turbo actif", "de": "Turbo aktiv",
    "pt": "Turbo ativo", "ru": "Турбо активен", "zh": "Turbo 已启用", "ja": "Turbo 有効", "ar": "تيربو مُفعّل"
  },
  "Turbo is on, but this model's metadata couldn't be read to verify draft compatibility — auto-disabled to be safe.": {
    "tr": "Turbo açık ama bu modelin metadata'sı okunup draft uyumu doğrulanamadı — güvenli olsun diye otomatik kapatıldı.",
    "es": "Turbo está activado, pero no se pudieron leer los metadatos de este modelo para verificar la compatibilidad del borrador — desactivado automáticamente por seguridad.",
    "fr": "Turbo est activé, mais les métadonnées de ce modèle n'ont pas pu être lues pour vérifier la compatibilité du brouillon — désactivé automatiquement par sécurité.",
    "de": "Turbo ist an, aber die Metadaten dieses Modells konnten nicht gelesen werden, um die Entwurfs-Kompatibilität zu prüfen — sicherheitshalber automatisch deaktiviert.",
    "pt": "O Turbo está ligado, mas não foi possível ler os metadados deste modelo para verificar a compatibilidade do rascunho — desativado automaticamente por segurança.",
    "ru": "Турбо включён, но метаданные этой модели не удалось прочитать для проверки совместимости черновика — автоматически отключён для безопасности.",
    "zh": "Turbo 已开启，但无法读取此模型的元数据来验证草稿兼容性——为安全起见已自动禁用。",
    "ja": "Turbo は有効ですが、このモデルのメタデータを読み取ってドラフト互換性を確認できませんでした — 安全のため自動的に無効化しました。",
    "ar": "تيربو مُفعّل، لكن تعذّر قراءة بيانات هذا النموذج الوصفية للتحقق من توافق المسودة — تم تعطيله تلقائيًا للأمان."
  },
  "Turbo is on, but the available draft model is incompatible with this model (different vocabulary/tokenizer) — auto-disabled to avoid a broken load.": {
    "tr": "Turbo açık ama eldeki draft modeli bu modelle uyumsuz (farklı sözcük dağarcığı/tokenizer) — bozuk yükleme olmasın diye otomatik kapatıldı.",
    "es": "Turbo está activado, pero el modelo borrador disponible es incompatible con este modelo (vocabulario/tokenizador distinto) — desactivado automáticamente para evitar una carga rota.",
    "fr": "Turbo est activé, mais le modèle brouillon disponible est incompatible avec ce modèle (vocabulaire/tokenizer différent) — désactivé automatiquement pour éviter un chargement cassé.",
    "de": "Turbo ist an, aber das verfügbare Entwurfsmodell ist mit diesem Modell inkompatibel (anderes Vokabular/Tokenizer) — automatisch deaktiviert, um einen fehlerhaften Ladevorgang zu vermeiden.",
    "pt": "O Turbo está ligado, mas o modelo de rascunho disponível é incompatível com este modelo (vocabulário/tokenizador diferente) — desativado automaticamente para evitar um carregamento quebrado.",
    "ru": "Турбо включён, но доступная черновая модель несовместима с этой моделью (другой словарь/токенизатор) — автоматически отключён во избежание сбоя загрузки.",
    "zh": "Turbo 已开启，但可用的草稿模型与此模型不兼容（词表/分词器不同）——已自动禁用以避免加载失败。",
    "ja": "Turbo は有効ですが、利用可能なドラフトモデルはこのモデルと互換性がありません（語彙/トークナイザーが異なる）— 読み込み失敗を避けるため自動的に無効化しました。",
    "ar": "تيربو مُفعّل، لكن نموذج المسودة المتاح غير متوافق مع هذا النموذج (مفردات/مُجزّئ مختلف) — تم تعطيله تلقائيًا لتجنّب تحميل معطوب."
  },
  "Verified": {
    "tr": "Doğrulandı", "es": "Verificado", "fr": "Vérifié", "de": "Verifiziert",
    "pt": "Verificado", "ru": "Проверено", "zh": "已验证", "ja": "検証済み", "ar": "تم التحقق"
  },
  "Failed": {
    "tr": "Başarısız", "es": "Falló", "fr": "Échec", "de": "Fehlgeschlagen",
    "pt": "Falhou", "ru": "Не пройдено", "zh": "失败", "ja": "失敗", "ar": "فشل"
  },
  "Unverified": {
    "tr": "Doğrulanamadı", "es": "No verificado", "fr": "Non vérifié", "de": "Nicht verifiziert",
    "pt": "Não verificado", "ru": "Не проверено", "zh": "未验证", "ja": "未検証", "ar": "لم يتم التحقق"
  },
  "Verification": {
    "tr": "Doğrulama", "es": "Verificación", "fr": "Vérification", "de": "Verifizierung",
    "pt": "Verificação", "ru": "Проверка", "zh": "验证", "ja": "検証", "ar": "التحقق"
  },
  "Recurring prompts — enqueued when due, run when the engine is free. Only while the app is open (local-first, no hidden daemon).": {
    "tr": "Yinelenen istemler — zamanı gelince kuyruğa alınır, motor boşta olunca çalışır. Yalnızca uygulama açıkken (local-first, gizli daemon yok).",
    "es": "Prompts recurrentes — se ponen en cola cuando toca y se ejecutan cuando el motor está libre. Solo mientras la app esté abierta (local-first, sin daemon oculto).",
    "fr": "Prompts récurrents — mis en file à échéance, exécutés quand le moteur est libre. Uniquement lorsque l'application est ouverte (local-first, sans daemon caché).",
    "de": "Wiederkehrende Prompts — bei Fälligkeit eingereiht, ausgeführt, sobald die Engine frei ist. Nur bei geöffneter App (local-first, kein versteckter daemon).",
    "pt": "Prompts recorrentes — colocados na fila quando chega a hora, executados quando o motor está livre. Apenas enquanto a aplicação estiver aberta (local-first, sem daemon oculto).",
    "ru": "Повторяющиеся запросы — ставятся в очередь по расписанию и выполняются, когда движок свободен. Только пока приложение открыто (local-first, без скрытого daemon).",
    "zh": "定期提示词 —— 到期时进入队列，引擎空闲时运行。仅在应用打开期间有效（local-first，无隐藏 daemon）。",
    "ja": "繰り返し実行するプロンプト — 予定時刻にキューへ追加され、エンジンが空いたときに実行されます。アプリが開いている間のみ動作します（local-first、隠れた daemon はありません）。",
    "ar": "مطالبات متكررة — تُضاف إلى الطابور عند حلول موعدها، وتُنفَّذ عندما يكون المحرك متاحًا. فقط أثناء فتح التطبيق (local-first، بلا daemon خفي)."
  },
  "Expose the local model to tools like Continue/Cline/Aider. 127.0.0.1 only — data never leaves the machine (local-first). A model must be loaded.": {
    "tr": "Yerel modeli Continue/Cline/Aider gibi araçlara sun. Yalnızca 127.0.0.1 — veri makineden asla çıkmaz (local-first). Bir modelin yüklü olması gerekir.",
    "es": "Expón el modelo local a herramientas como Continue/Cline/Aider. Solo 127.0.0.1 — los datos nunca salen de la máquina (local-first). Debe haber un modelo cargado.",
    "fr": "Exposez le modèle local à des outils comme Continue/Cline/Aider. 127.0.0.1 uniquement — les données ne quittent jamais la machine (local-first). Un modèle doit être chargé.",
    "de": "Stellt das lokale Modell für Tools wie Continue/Cline/Aider bereit. Nur 127.0.0.1 — Daten verlassen den Rechner nie (local-first). Ein Modell muss geladen sein.",
    "pt": "Expõe o modelo local a ferramentas como Continue/Cline/Aider. Apenas 127.0.0.1 — os dados nunca saem da máquina (local-first). Tem de haver um modelo carregado.",
    "ru": "Открывает локальную модель для инструментов вроде Continue/Cline/Aider. Только 127.0.0.1 — данные не покидают машину (local-first). Модель должна быть загружена.",
    "zh": "将本地模型开放给 Continue/Cline/Aider 等工具。仅限 127.0.0.1 —— 数据绝不离开本机（local-first）。必须已加载一个模型。",
    "ja": "ローカルモデルを Continue/Cline/Aider などのツールに公開します。127.0.0.1 のみ — データがマシンの外に出ることはありません（local-first）。モデルが読み込まれている必要があります。",
    "ar": "اعرض النموذج المحلي لأدوات مثل Continue/Cline/Aider. عبر 127.0.0.1 فقط — لا تغادر البيانات الجهاز أبدًا (local-first). يجب تحميل نموذج."
  },
  "Add local stdio MCP servers — their tools are offered to the agent ([MCP] directive) and calls pass through the trust layer. Local process only; no remote/HTTP (local-first).": {
    "tr": "Yerel stdio MCP sunucuları ekle — araçları ajana sunulur ([MCP] direktifi) ve çağrılar güven katmanından geçer. Yalnızca yerel süreç; uzak/HTTP yok (local-first).",
    "es": "Añade servidores MCP stdio locales — sus herramientas se ofrecen al agente (directiva [MCP]) y las llamadas pasan por la capa de confianza. Solo proceso local; sin remoto/HTTP (local-first).",
    "fr": "Ajoutez des serveurs MCP stdio locaux — leurs outils sont proposés à l'agent (directive [MCP]) et les appels passent par la couche de confiance. Processus local uniquement ; pas de distant/HTTP (local-first).",
    "de": "Lokale stdio-MCP-Server hinzufügen — ihre Tools werden dem Agenten angeboten ([MCP]-Direktive) und Aufrufe durchlaufen die Trust-Schicht. Nur lokaler Prozess; kein Remote/HTTP (local-first).",
    "pt": "Adicione servidores MCP stdio locais — as suas ferramentas são disponibilizadas ao agente (diretiva [MCP]) e as chamadas passam pela camada de confiança. Apenas processo local; sem acesso remoto/HTTP (local-first).",
    "ru": "Добавляйте локальные stdio-серверы MCP — их инструменты предлагаются агенту (директива [MCP]), а вызовы проходят через слой доверия. Только локальный процесс; без удалённых/HTTP (local-first).",
    "zh": "添加本地 stdio MCP 服务器 —— 其工具会提供给智能体（[MCP] 指令），调用会经过信任层。仅限本地进程；不支持远程/HTTP（local-first）。",
    "ja": "ローカルの stdio MCP サーバーを追加します — それらのツールはエージェントに提供され（[MCP] ディレクティブ）、呼び出しはトラストレイヤーを通過します。ローカルプロセスのみで、リモートや HTTP はありません（local-first）。",
    "ar": "أضِف خوادم MCP محلية عبر stdio — تُتاح أدواتها للوكيل (توجيه [MCP]) وتمر الاستدعاءات عبر طبقة الثقة. عمليات محلية فقط؛ بلا اتصال بعيد/HTTP (local-first)."
  },
  "MCP Tool Servers": {
    "tr": "MCP Araç Sunucuları",
    "es": "Servidores de herramientas MCP",
    "fr": "Serveurs d'outils MCP",
    "de": "MCP-Tool-Server",
    "pt": "Servidores de ferramentas MCP",
    "ru": "Серверы инструментов MCP",
    "zh": "MCP 工具服务器",
    "ja": "MCP ツールサーバー",
    "ar": "خوادم أدوات MCP"
  },
  "tools": {
    "tr": "araçlar",
    "es": "herramientas",
    "fr": "outils",
    "de": "Tools",
    "pt": "ferramentas",
    "ru": "инструменты",
    "zh": "工具",
    "ja": "ツール",
    "ar": "أدوات"
  },
  "Reload": {
    "tr": "Yeniden Yükle",
    "es": "Recargar",
    "fr": "Recharger",
    "de": "Neu laden",
    "pt": "Recarregar",
    "ru": "Перезагрузить",
    "zh": "重新加载",
    "ja": "再読み込み",
    "ar": "إعادة تحميل"
  },
  "Enabled": {
    "tr": "Etkin",
    "es": "Activado",
    "fr": "Activé",
    "de": "Aktiviert",
    "pt": "Ativado",
    "ru": "Включено",
    "zh": "已启用",
    "ja": "有効",
    "ar": "مُفعّل"
  },
  "Remove": {
    "tr": "Kaldır",
    "es": "Quitar",
    "fr": "Retirer",
    "de": "Entfernen",
    "pt": "Remover",
    "ru": "Удалить",
    "zh": "移除",
    "ja": "削除",
    "ar": "إزالة"
  },
  "name (e.g. filesystem)": {
    "tr": "ad (örn. filesystem)",
    "es": "nombre (p. ej. filesystem)",
    "fr": "nom (ex. filesystem)",
    "de": "Name (z. B. filesystem)",
    "pt": "nome (ex.: filesystem)",
    "ru": "имя (напр. filesystem)",
    "zh": "名称（如 filesystem）",
    "ja": "名前（例: filesystem）",
    "ar": "الاسم (مثل filesystem)"
  },
  "command (e.g. npx)": {
    "tr": "komut (örn. npx)",
    "es": "comando (p. ej. npx)",
    "fr": "commande (ex. npx)",
    "de": "Befehl (z. B. npx)",
    "pt": "comando (ex.: npx)",
    "ru": "команда (напр. npx)",
    "zh": "命令（如 npx）",
    "ja": "コマンド（例: npx）",
    "ar": "الأمر (مثل npx)"
  },
  "args (space-separated)": {
    "tr": "argümanlar (boşlukla ayrılmış)",
    "es": "argumentos (separados por espacios)",
    "fr": "args (séparés par des espaces)",
    "de": "Argumente (durch Leerzeichen getrennt)",
    "pt": "argumentos (separados por espaços)",
    "ru": "аргументы (через пробел)",
    "zh": "参数（空格分隔）",
    "ja": "引数（スペース区切り）",
    "ar": "الوسائط (مفصولة بمسافات)"
  },
  "Add server": {
    "tr": "Sunucu ekle",
    "es": "Añadir servidor",
    "fr": "Ajouter un serveur",
    "de": "Server hinzufügen",
    "pt": "Adicionar servidor",
    "ru": "Добавить сервер",
    "zh": "添加服务器",
    "ja": "サーバーを追加",
    "ar": "إضافة خادم"
  },
  "Serve Engine (OpenAI-compatible)": {
    "tr": "Motoru Sun (OpenAI uyumlu)",
    "es": "Servir motor (compatible con OpenAI)",
    "fr": "Exposer le moteur (compatible OpenAI)",
    "de": "Engine bereitstellen (OpenAI-kompatibel)",
    "pt": "Servir motor (compatível com OpenAI)",
    "ru": "Запустить движок (совместимо с OpenAI)",
    "zh": "提供引擎服务（OpenAI 兼容）",
    "ja": "エンジンを公開（OpenAI 互換）",
    "ar": "تقديم المحرك (متوافق مع OpenAI)"
  },
  "Copy": {
    "tr": "Kopyala",
    "es": "Copiar",
    "fr": "Copier",
    "de": "Kopieren",
    "pt": "Copiar",
    "ru": "Копировать",
    "zh": "复制",
    "ja": "コピー",
    "ar": "نسخ"
  },
  "Scheduled Tasks": {
    "tr": "Zamanlanmış Görevler",
    "es": "Tareas programadas",
    "fr": "Tâches planifiées",
    "de": "Geplante Aufgaben",
    "pt": "Tarefas agendadas",
    "ru": "Запланированные задачи",
    "zh": "计划任务",
    "ja": "スケジュールタスク",
    "ar": "المهام المجدولة"
  },
  "next": {
    "tr": "sonraki",
    "es": "próxima",
    "fr": "prochaine",
    "de": "nächste",
    "pt": "próxima",
    "ru": "далее",
    "zh": "下次运行",
    "ja": "次回",
    "ar": "التالي"
  },
  "label (e.g. Dependency check)": {
    "tr": "etiket (örn. Bağımlılık kontrolü)",
    "es": "etiqueta (p. ej. Revisión de dependencias)",
    "fr": "libellé (ex. Vérification des dépendances)",
    "de": "Bezeichnung (z. B. Abhängigkeitsprüfung)",
    "pt": "etiqueta (ex.: Verificação de dependências)",
    "ru": "метка (напр. Проверка зависимостей)",
    "zh": "标签（如 依赖检查）",
    "ja": "ラベル（例: 依存関係チェック）",
    "ar": "التسمية (مثل فحص التبعيات)"
  },
  "prompt (request sent to the engine)": {
    "tr": "istek (motora gönderilen komut)",
    "es": "prompt (solicitud enviada al motor)",
    "fr": "prompt (requête envoyée au moteur)",
    "de": "Prompt (Anfrage an die Engine)",
    "pt": "prompt (pedido enviado ao motor)",
    "ru": "запрос (отправляется движку)",
    "zh": "提示词（发送给引擎的请求）",
    "ja": "プロンプト（エンジンへ送る内容）",
    "ar": "الطلب (المُرسل إلى المحرك)"
  },
  "Every": {
    "tr": "Her",
    "es": "Cada",
    "fr": "Toutes les",
    "de": "Alle",
    "pt": "A cada",
    "ru": "Каждые",
    "zh": "每隔",
    "ja": "間隔",
    "ar": "كل"
  },
  "min": {
    "tr": "dk",
    "es": "min",
    "fr": "min",
    "de": "Min.",
    "pt": "min",
    "ru": "мин",
    "zh": "分钟",
    "ja": "分",
    "ar": "د"
  },
  "Run once, then self-remove": {
    "tr": "Bir kez çalış, sonra kendini kaldır",
    "es": "Ejecutar una vez y autoeliminarse",
    "fr": "Exécuter une fois, puis se supprimer",
    "de": "Einmal ausführen, dann entfernen",
    "pt": "Executar uma vez e depois remover-se",
    "ru": "Выполнить один раз и удалить",
    "zh": "运行一次后自动移除",
    "ja": "1 回実行後、自動削除",
    "ar": "تشغيل مرة واحدة ثم الإزالة تلقائياً"
  },
  "once": {
    "tr": "tek sefer",
    "es": "una vez",
    "fr": "une fois",
    "de": "einmal",
    "pt": "uma vez",
    "ru": "один раз",
    "zh": "一次",
    "ja": "1 回のみ",
    "ar": "مرة"
  },
  "Add": {
    "tr": "Ekle",
    "es": "Añadir",
    "fr": "Ajouter",
    "de": "Hinzufügen",
    "pt": "Adicionar",
    "ru": "Добавить",
    "zh": "添加",
    "ja": "追加",
    "ar": "إضافة"
  },
  "fits": {
    "tr": "sığar",
    "es": "cabe",
    "fr": "tient",
    "de": "passt",
    "pt": "cabe",
    "ru": "помещается",
    "zh": "适配",
    "ja": "収まる",
    "ar": "مناسب"
  },
  "spills · slow": {
    "tr": "taşar · yavaş",
    "es": "desborda · lento",
    "fr": "déborde · lent",
    "de": "läuft über · langsam",
    "pt": "excede · lento",
    "ru": "не влезает · медленно",
    "zh": "溢出 · 慢",
    "ja": "はみ出し · 低速",
    "ar": "فائض · بطيء"
  },
  "too big": {
    "tr": "çok büyük",
    "es": "demasiado grande",
    "fr": "trop gros",
    "de": "zu groß",
    "pt": "grande demais",
    "ru": "слишком большая",
    "zh": "过大",
    "ja": "大きすぎ",
    "ar": "كبير جداً"
  },
  "Delete?": {
    "tr": "Silinsin mi?",
    "es": "¿Eliminar?",
    "fr": "Supprimer ?",
    "de": "Löschen?",
    "pt": "Eliminar?",
    "ru": "Удалить?",
    "zh": "删除？",
    "ja": "削除しますか？",
    "ar": "حذف؟"
  },
  "Delete": {
    "tr": "Sil",
    "es": "Eliminar",
    "fr": "Supprimer",
    "de": "Löschen",
    "pt": "Eliminar",
    "ru": "Удалить",
    "zh": "删除",
    "ja": "削除",
    "ar": "حذف"
  },
  "Delete this model": {
    "tr": "Bu modeli sil",
    "es": "Eliminar este modelo",
    "fr": "Supprimer ce modèle",
    "de": "Dieses Modell löschen",
    "pt": "Eliminar este modelo",
    "ru": "Удалить эту модель",
    "zh": "删除此模型",
    "ja": "このモデルを削除",
    "ar": "حذف هذا النموذج"
  },
  "to cloud": {
    "tr": "buluta",
    "es": "a la nube",
    "fr": "vers le cloud",
    "de": "in die Cloud",
    "pt": "para a nuvem",
    "ru": "в облако",
    "zh": "发送至云端",
    "ja": "クラウドへ送信",
    "ar": "إلى السحابة"
  },
  "fully on device": {
    "tr": "tamamen cihazda",
    "es": "totalmente en el dispositivo",
    "fr": "entièrement sur l'appareil",
    "de": "vollständig auf dem Gerät",
    "pt": "totalmente no dispositivo",
    "ru": "полностью на устройстве",
    "zh": "完全本地运行",
    "ja": "完全にデバイス内",
    "ar": "بالكامل على الجهاز"
  },
  "Your messages are sent to a cloud provider in this session.": {
    "tr": "Bu oturumda mesajlarınız bir bulut sağlayıcısına gönderilir.",
    "es": "En esta sesión, tus mensajes se envían a un proveedor en la nube.",
    "fr": "Vos messages sont envoyés à un fournisseur cloud dans cette session.",
    "de": "Deine Nachrichten werden in dieser Sitzung an einen Cloud-Anbieter gesendet.",
    "pt": "As suas mensagens são enviadas para um fornecedor na nuvem nesta sessão.",
    "ru": "В этом сеансе ваши сообщения отправляются облачному провайдеру.",
    "zh": "本次会话中，你的消息会发送给云端服务商。",
    "ja": "このセッションでは、メッセージがクラウドプロバイダーに送信されます。",
    "ar": "تُرسَل رسائلك إلى مزوّد سحابي في هذه الجلسة."
  },
  "This session runs entirely on your device — no data leaves your computer.": {
    "tr": "Bu oturum tamamen cihazınızda çalışır — hiçbir veri bilgisayarınızdan çıkmaz.",
    "es": "Esta sesión se ejecuta por completo en tu dispositivo — ningún dato sale de tu equipo.",
    "fr": "Cette session s'exécute entièrement sur votre appareil — aucune donnée ne quitte votre ordinateur.",
    "de": "Diese Sitzung läuft vollständig auf deinem Gerät — keine Daten verlassen deinen Computer.",
    "pt": "Esta sessão é executada inteiramente no seu dispositivo — nenhum dado sai do seu computador.",
    "ru": "Этот сеанс работает полностью на вашем устройстве — данные не покидают компьютер.",
    "zh": "本次会话完全在本地设备运行 — 没有数据离开你的电脑。",
    "ja": "このセッションはすべてデバイス内で実行されます — データがコンピューターの外に出ることはありません。",
    "ar": "تعمل هذه الجلسة بالكامل على جهازك — لا تغادر أي بيانات حاسوبك."
  },
  "Download project as a single .zip (share / Netlify)": {
    "tr": "Projeyi tek bir .zip olarak indir (paylaş / Netlify)",
    "es": "Descargar el proyecto como un único .zip (compartir / Netlify)",
    "fr": "Télécharger le projet en un seul .zip (partage / Netlify)",
    "de": "Projekt als einzelne .zip herunterladen (teilen / Netlify)",
    "pt": "Transferir o projeto como um único .zip (partilhar / Netlify)",
    "ru": "Скачать проект одним .zip (поделиться / Netlify)",
    "zh": "将项目下载为单个 .zip（分享 / Netlify）",
    "ja": "プロジェクトを 1 つの .zip でダウンロード（共有 / Netlify）",
    "ar": "تنزيل المشروع كملف .zip واحد (مشاركة / Netlify)"
  },
  "files": {
    "tr": "dosya",
    "es": "archivos",
    "fr": "fichiers",
    "de": "Dateien",
    "pt": "ficheiros",
    "ru": "файлы",
    "zh": "文件",
    "ja": "ファイル",
    "ar": "ملفات"
  },
  "Rename": {
    "tr": "Yeniden Adlandır",
    "es": "Cambiar nombre",
    "fr": "Renommer",
    "de": "Umbenennen",
    "pt": "Mudar o nome",
    "ru": "Переименовать",
    "zh": "重命名",
    "ja": "名前を変更",
    "ar": "إعادة تسمية"
  },
  "Double-click to rename": {
    "tr": "Yeniden adlandırmak için çift tıklayın",
    "es": "Doble clic para cambiar el nombre",
    "fr": "Double-cliquez pour renommer",
    "de": "Zum Umbenennen doppelklicken",
    "pt": "Clique duas vezes para mudar o nome",
    "ru": "Двойной клик для переименования",
    "zh": "双击重命名",
    "ja": "ダブルクリックで名前を変更",
    "ar": "انقر نقراً مزدوجاً لإعادة التسمية"
  },
  "Code": {
    "tr": "Kod",
    "es": "Código",
    "fr": "Code",
    "de": "Code",
    "pt": "Código",
    "ru": "Код",
    "zh": "代码",
    "ja": "コード",
    "ar": "الكود"
  },
  "Tree": {
    "tr": "Ağaç",
    "es": "Árbol",
    "fr": "Arborescence",
    "de": "Baum",
    "pt": "Árvore",
    "ru": "Дерево",
    "zh": "目录树",
    "ja": "ツリー",
    "ar": "الشجرة"
  },
  "History": {
    "tr": "Geçmiş",
    "es": "Historial",
    "fr": "Historique",
    "de": "Verlauf",
    "pt": "Histórico",
    "ru": "История",
    "zh": "历史",
    "ja": "履歴",
    "ar": "السجل"
  },
  "Engine": {
    "tr": "Motor",
    "es": "Motor",
    "fr": "Moteur",
    "de": "Engine",
    "pt": "Motor",
    "ru": "Движок",
    "zh": "引擎",
    "ja": "エンジン",
    "ar": "المحرّك"
  },
  "Docs": {
    "tr": "Belgeler",
    "es": "Documentos",
    "fr": "Docs",
    "de": "Docs",
    "pt": "Documentos",
    "ru": "Документы",
    "zh": "文档",
    "ja": "ドキュメント",
    "ar": "المستندات"
  },
  "Export error": {
    "tr": "Dışa aktarma hatası",
    "es": "Error de exportación",
    "fr": "Erreur d'exportation",
    "de": "Exportfehler",
    "pt": "Erro de exportação",
    "ru": "Ошибка экспорта",
    "zh": "导出错误",
    "ja": "エクスポートエラー",
    "ar": "خطأ في التصدير"
  },
  "Scan report added to chat": {
    "tr": "Tarama raporu sohbete eklendi",
    "es": "Informe de escaneo añadido al chat",
    "fr": "Rapport d'analyse ajouté à la discussion",
    "de": "Scan-Bericht zum Chat hinzugefügt",
    "pt": "Relatório de análise adicionado ao chat",
    "ru": "Отчёт о сканировании добавлен в чат",
    "zh": "扫描报告已添加到对话",
    "ja": "スキャンレポートをチャットに追加しました",
    "ar": "أُضيف تقرير الفحص إلى المحادثة"
  },
  "Dev server stopped": {
    "tr": "Dev sunucusu durduruldu",
    "es": "Servidor dev detenido",
    "fr": "Serveur de dev arrêté",
    "de": "Dev-Server gestoppt",
    "pt": "Servidor dev parado",
    "ru": "Dev-сервер остановлен",
    "zh": "开发服务器已停止",
    "ja": "開発サーバーを停止しました",
    "ar": "أُوقِف خادم التطوير"
  },
  "Preparing project (npm install + dev server)…": {
    "tr": "Proje hazırlanıyor (npm install + dev sunucusu)…",
    "es": "Preparando proyecto (npm install + servidor dev)…",
    "fr": "Préparation du projet (npm install + serveur de dev)…",
    "de": "Projekt wird vorbereitet (npm install + Dev-Server)…",
    "pt": "Preparando projeto (npm install + servidor dev)…",
    "ru": "Подготовка проекта (npm install + dev-сервер)…",
    "zh": "正在准备项目（npm install + 开发服务器）…",
    "ja": "プロジェクトを準備中（npm install + 開発サーバー）…",
    "ar": "جارٍ تجهيز المشروع (npm install + خادم التطوير)…"
  },
  "Running: ": {
    "tr": "Çalışıyor: ",
    "es": "Ejecutando: ",
    "fr": "En cours : ",
    "de": "Läuft: ",
    "pt": "Executando: ",
    "ru": "Выполняется: ",
    "zh": "正在运行：",
    "ja": "実行中： ",
    "ar": "قيد التشغيل: "
  },
  "Failed to start": {
    "tr": "Başlatılamadı",
    "es": "No se pudo iniciar",
    "fr": "Échec du démarrage",
    "de": "Start fehlgeschlagen",
    "pt": "Falha ao iniciar",
    "ru": "Не удалось запустить",
    "zh": "启动失败",
    "ja": "起動に失敗しました",
    "ar": "فشل البدء"
  },
  "Live scan on — no findings": {
    "tr": "Canlı tarama açık — bulgu yok",
    "es": "Escaneo en vivo activo — sin hallazgos",
    "fr": "Analyse en direct activée — aucun résultat",
    "de": "Live-Scan aktiv — keine Funde",
    "pt": "Análise ao vivo ativada — nenhuma ocorrência",
    "ru": "Живое сканирование включено — находок нет",
    "zh": "实时扫描已开启 — 无发现",
    "ja": "ライブスキャン中 — 検出なし",
    "ar": "الفحص المباشر مفعّل — لا نتائج"
  },
  "Live scan: scan in the background as you type (never edits files)": {
    "tr": "Canlı tarama: sen yazarken arka planda tara (dosya değiştirmez)",
    "es": "Escaneo en vivo: analiza en segundo plano mientras escribes (nunca edita archivos)",
    "fr": "Analyse en direct : analyse en arrière-plan pendant la frappe (ne modifie jamais les fichiers)",
    "de": "Live-Scan: im Hintergrund scannen, während du tippst (ändert nie Dateien)",
    "pt": "Análise ao vivo: analisa em segundo plano enquanto você digita (nunca edita arquivos)",
    "ru": "Живое сканирование: проверяет в фоне, пока вы печатаете (файлы не меняет)",
    "zh": "实时扫描：在你输入时于后台扫描（绝不修改文件）",
    "ja": "ライブスキャン：入力中にバックグラウンドでスキャン（ファイルは変更しません）",
    "ar": "الفحص المباشر: يفحص في الخلفية أثناء كتابتك (لا يعدّل الملفات أبدًا)"
  },
  "Live": {
    "tr": "Canlı",
    "es": "En vivo",
    "fr": "En direct",
    "de": "Live",
    "pt": "Ao vivo",
    "ru": "Живое",
    "zh": "实时",
    "ja": "ライブ",
    "ar": "مباشر"
  },
  "Scan without running: find faulty code, repair deterministically": {
    "tr": "Projeyi çalıştırmadan tara: hatalı kodu bul, bulunanı modelsiz onar",
    "es": "Escanear sin ejecutar: encuentra código defectuoso y repáralo de forma determinista",
    "fr": "Analyser sans exécuter : trouve le code défectueux, le répare de façon déterministe",
    "de": "Ohne Ausführen scannen: fehlerhaften Code finden, deterministisch reparieren",
    "pt": "Analisar sem executar: encontra código com defeito e repara de forma determinística",
    "ru": "Сканировать без запуска: найти ошибочный код, исправить детерминированно",
    "zh": "无需运行即可扫描：找出问题代码，确定性修复",
    "ja": "実行せずにスキャン：不具合のあるコードを見つけ、確定的に修復",
    "ar": "افحص دون تشغيل: اعثر على الكود المعطوب وأصلحه بشكل حتمي"
  },
  "Scan": {
    "tr": "Tara",
    "es": "Escanear",
    "fr": "Analyser",
    "de": "Scannen",
    "pt": "Analisar",
    "ru": "Сканировать",
    "zh": "扫描",
    "ja": "スキャン",
    "ar": "فحص"
  },
  "Stop dev server": {
    "tr": "Dev sunucusunu durdur",
    "es": "Detener servidor dev",
    "fr": "Arrêter le serveur de dev",
    "de": "Dev-Server stoppen",
    "pt": "Parar servidor dev",
    "ru": "Остановить dev-сервер",
    "zh": "停止开发服务器",
    "ja": "開発サーバーを停止",
    "ar": "إيقاف خادم التطوير"
  },
  "Run project on localhost": {
    "tr": "Projeyi localhost'ta çalıştır",
    "es": "Ejecutar proyecto en localhost",
    "fr": "Exécuter le projet sur localhost",
    "de": "Projekt auf localhost ausführen",
    "pt": "Executar projeto no localhost",
    "ru": "Запустить проект на localhost",
    "zh": "在 localhost 上运行项目",
    "ja": "localhostでプロジェクトを実行",
    "ar": "تشغيل المشروع على localhost"
  },
  "Stop": {
    "tr": "Durdur",
    "es": "Detener",
    "fr": "Arrêter",
    "de": "Stopp",
    "pt": "Parar",
    "ru": "Стоп",
    "zh": "停止",
    "ja": "停止",
    "ar": "إيقاف"
  },
  "Run": {
    "tr": "Çalıştır",
    "es": "Ejecutar",
    "fr": "Exécuter",
    "de": "Ausführen",
    "pt": "Executar",
    "ru": "Запустить",
    "zh": "运行",
    "ja": "実行",
    "ar": "تشغيل"
  },
  "Search files…": {
    "tr": "Dosyalarda ara…",
    "es": "Buscar archivos…",
    "fr": "Rechercher des fichiers…",
    "de": "Dateien durchsuchen…",
    "pt": "Buscar arquivos…",
    "ru": "Поиск файлов…",
    "zh": "搜索文件…",
    "ja": "ファイルを検索…",
    "ar": "بحث في الملفات…"
  },
  "No matches": {
    "tr": "Eşleşme yok",
    "es": "Sin coincidencias",
    "fr": "Aucune correspondance",
    "de": "Keine Treffer",
    "pt": "Nenhuma correspondência",
    "ru": "Совпадений нет",
    "zh": "无匹配项",
    "ja": "一致なし",
    "ar": "لا توجد تطابقات"
  },
  "ready": {
    "tr": "hazır",
    "es": "listo",
    "fr": "prêt",
    "de": "bereit",
    "pt": "pronto",
    "ru": "готово",
    "zh": "就绪",
    "ja": "準備完了",
    "ar": "جاهز"
  },
  "NEW": {
    "tr": "YENİ",
    "es": "NUEVO",
    "fr": "NOUV.",
    "de": "NEU",
    "pt": "NOVO",
    "ru": "НОВОЕ",
    "zh": "新",
    "ja": "NEW",
    "ar": "جديد"
  },
  "s": {
    "tr": "sn",
    "es": "s",
    "fr": "s",
    "de": "s",
    "pt": "s",
    "ru": "с",
    "zh": "秒",
    "ja": "秒",
    "ar": "ث"
  },
  "m": {
    "tr": "dk",
    "es": "min",
    "fr": "min",
    "de": "m",
    "pt": "min",
    "ru": "м",
    "zh": "分",
    "ja": "分",
    "ar": "د"
  },
  "h": {
    "tr": "sa",
    "es": "h",
    "fr": "h",
    "de": "h",
    "pt": "h",
    "ru": "ч",
    "zh": "时",
    "ja": "時間",
    "ar": "س"
  },
  "Describe an image…": {
    "tr": "Bir görsel tarif et…",
    "es": "Describe una imagen…",
    "fr": "Décrivez une image…",
    "de": "Beschreibe ein Bild…",
    "pt": "Descreva uma imagem…",
    "ru": "Опишите изображение…",
    "zh": "描述一张图片…",
    "ja": "画像を説明…",
    "ar": "صِف صورة…"
  },
  "Tasks": {
    "tr": "Görevler",
    "es": "Tareas",
    "fr": "Tâches",
    "de": "Aufgaben",
    "pt": "Tarefas",
    "ru": "Задачи",
    "zh": "任务",
    "ja": "タスク",
    "ar": "المهام"
  },
  "queued": {
    "tr": "sırada",
    "es": "en cola",
    "fr": "en file",
    "de": "in Warteschlange",
    "pt": "na fila",
    "ru": "в очереди",
    "zh": "排队中",
    "ja": "待機中",
    "ar": "في الطابور"
  },
  "running": {
    "tr": "koşuyor",
    "es": "en curso",
    "fr": "en cours",
    "de": "läuft",
    "pt": "executando",
    "ru": "выполняется",
    "zh": "运行中",
    "ja": "実行中",
    "ar": "قيد التشغيل"
  },
  "⚠ review": {
    "tr": "⚠ incele",
    "es": "⚠ revisar",
    "fr": "⚠ à examiner",
    "de": "⚠ prüfen",
    "pt": "⚠ revisar",
    "ru": "⚠ проверить",
    "zh": "⚠ 待查",
    "ja": "⚠ 要確認",
    "ar": "⚠ مراجعة"
  },
  "failed": {
    "tr": "başarısız",
    "es": "fallida",
    "fr": "échoué",
    "de": "fehlgeschlagen",
    "pt": "falhou",
    "ru": "ошибка",
    "zh": "失败",
    "ja": "失敗",
    "ar": "فشل"
  },
  "cancelled": {
    "tr": "iptal",
    "es": "cancelada",
    "fr": "annulé",
    "de": "abgebrochen",
    "pt": "cancelado",
    "ru": "отменено",
    "zh": "已取消",
    "ja": "キャンセル済み",
    "ar": "أُلغي"
  },
  "Cancel": {
    "tr": "İptal",
    "es": "Cancelar",
    "fr": "Annuler",
    "de": "Abbrechen",
    "pt": "Cancelar",
    "ru": "Отмена",
    "zh": "取消",
    "ja": "キャンセル",
    "ar": "إلغاء"
  },
  "Review": {
    "tr": "İncele",
    "es": "Revisar",
    "fr": "Examiner",
    "de": "Prüfen",
    "pt": "Revisar",
    "ru": "Проверить",
    "zh": "查看",
    "ja": "確認",
    "ar": "مراجعة"
  },
  "queued ": {
    "tr": "sırada ",
    "es": "en cola ",
    "fr": "en file ",
    "de": "in Warteschlange ",
    "pt": "na fila ",
    "ru": "в очереди ",
    "zh": "排队中 ",
    "ja": "待機中 ",
    "ar": "في الطابور "
  },
  "running ": {
    "tr": "koşuyor ",
    "es": "en curso ",
    "fr": "en cours ",
    "de": "läuft ",
    "pt": "executando ",
    "ru": "выполняется ",
    "zh": "运行中 ",
    "ja": "実行中 ",
    "ar": "قيد التشغيل "
  },
  "Clear finished": {
    "tr": "Bitmişleri temizle",
    "es": "Limpiar terminadas",
    "fr": "Effacer les terminées",
    "de": "Fertige löschen",
    "pt": "Limpar concluídas",
    "ru": "Очистить завершённые",
    "zh": "清除已完成",
    "ja": "完了分をクリア",
    "ar": "مسح المكتملة"
  },
  "Attach reference image": {
    "tr": "Referans görsel ekle",
    "es": "Adjuntar imagen de referencia",
    "fr": "Joindre une image de référence",
    "de": "Referenzbild anhängen",
    "pt": "Anexar imagem de referência",
    "ru": "Прикрепить референсное изображение",
    "zh": "附加参考图片",
    "ja": "参照画像を添付",
    "ar": "إرفاق صورة مرجعية"
  },
  "Modern landing page with clean animations and Tailwind.": {
    "tr": "Temiz animasyonlar ve Tailwind ile modern landing page.",
    "es": "Landing page moderna con animaciones limpias y Tailwind.",
    "fr": "Landing page moderne avec animations épurées et Tailwind.",
    "de": "Moderne Landing Page mit sauberen Animationen und Tailwind.",
    "pt": "Landing page moderna com animações elegantes e Tailwind.",
    "ru": "Современный лендинг с плавными анимациями и Tailwind.",
    "zh": "简洁动画、Tailwind 打造的现代落地页。",
    "ja": "クリーンなアニメーションとTailwindを使ったモダンなランディングページ。",
    "ar": "صفحة هبوط عصرية برسوم متحركة أنيقة وTailwind."
  },
  "Clean management dashboard with cards, charts, and filters.": {
    "tr": "Kartlar, grafikler ve filtrelerle temiz yönetim paneli.",
    "es": "Dashboard de gestión limpio con tarjetas, gráficos y filtros.",
    "fr": "Dashboard de gestion épuré avec cartes, graphiques et filtres.",
    "de": "Übersichtliches Management-Dashboard mit Karten, Diagrammen und Filtern.",
    "pt": "Dashboard de gestão limpo com cards, gráficos e filtros.",
    "ru": "Аккуратный дашборд управления с карточками, графиками и фильтрами.",
    "zh": "含卡片、图表和筛选器的简洁管理仪表盘。",
    "ja": "カード、チャート、フィルター付きのすっきりした管理ダッシュボード。",
    "ar": "لوحة إدارة أنيقة ببطاقات ورسوم بيانية ومرشّحات."
  },
  "Aesthetic portfolio showcasing CV and projects.": {
    "tr": "CV ve projelerini sergileyen estetik web sitesi.",
    "es": "Portafolio estético que muestra tu CV y proyectos.",
    "fr": "Portfolio esthétique présentant CV et projets.",
    "de": "Ästhetisches Portfolio, das Lebenslauf und Projekte präsentiert.",
    "pt": "Portfólio estético exibindo currículo e projetos.",
    "ru": "Эстетичное портфолио с резюме и проектами.",
    "zh": "展示简历与项目的美观作品集。",
    "ja": "職務経歴とプロジェクトを見せる洗練されたポートフォリオ。",
    "ar": "معرض أعمال جمالي يعرض السيرة الذاتية والمشاريع."
  },
  "Modern login page with animations and form validation.": {
    "tr": "Animasyonlu ve doğrulamalı modern giriş arayüzü.",
    "es": "Página de inicio de sesión moderna con animaciones y validación de formulario.",
    "fr": "Page de connexion moderne avec animations et validation de formulaire.",
    "de": "Moderne Login-Seite mit Animationen und Formularvalidierung.",
    "pt": "Página de login moderna com animações e validação de formulário.",
    "ru": "Современная страница входа с анимациями и валидацией формы.",
    "zh": "带动画和表单校验的现代登录页。",
    "ja": "アニメーションとフォームバリデーション付きのモダンなログインページ。",
    "ar": "صفحة تسجيل دخول عصرية برسوم متحركة والتحقق من النموذج."
  },
  "Design a modern, minimalist technology landing page with light/dark support using React and Tailwind CSS. Add nice animations and responsive design.": {
    "tr": "React ve Tailwind CSS kullanarak modern, minimalist ve karanlık mod destekli bir teknoloji landing page tasarla. Harika animasyonlar ve responsive tasarım olsun.",
    "es": "Diseña una landing page de tecnología moderna y minimalista con soporte claro/oscuro usando React y Tailwind CSS. Añade buenas animaciones y diseño responsivo.",
    "fr": "Conçois une landing page techno moderne et minimaliste avec prise en charge clair/sombre en React et Tailwind CSS. Ajoute de belles animations et un design responsive.",
    "de": "Gestalte eine moderne, minimalistische Technologie-Landing-Page mit Hell-/Dunkel-Unterstützung mit React und Tailwind CSS. Füge schöne Animationen und responsives Design hinzu.",
    "pt": "Crie uma landing page de tecnologia moderna e minimalista com suporte a tema claro/escuro usando React e Tailwind CSS. Adicione animações bonitas e design responsivo.",
    "ru": "Создай современный минималистичный технологический лендинг с поддержкой светлой/тёмной темы на React и Tailwind CSS. Добавь красивые анимации и адаптивный дизайн.",
    "zh": "用 React 和 Tailwind CSS 设计一个现代、极简、支持浅色/深色的科技落地页。加入精美动画和响应式设计。",
    "ja": "ReactとTailwind CSSを使い、ライト/ダーク対応のモダンでミニマルなテクノロジー系ランディングページをデザインして。素敵なアニメーションとレスポンシブデザインを加えて。",
    "ar": "صمّم صفحة هبوط تقنية عصرية بسيطة بدعم للوضعين الفاتح/الداكن باستخدام React وTailwind CSS. أضف رسومًا متحركة أنيقة وتصميمًا متجاوبًا."
  },
  "Design a clean data management dashboard interface with cards, filters, and mock data.": {
    "tr": "Güzel kartlar, filtre kontrolleri ve mock veri içeren temiz bir veri yönetim paneli (dashboard) arayüzü tasarla.",
    "es": "Diseña una interfaz de dashboard de gestión de datos limpia con tarjetas, filtros y datos de prueba.",
    "fr": "Conçois une interface de dashboard de gestion de données épurée avec cartes, filtres et données fictives.",
    "de": "Gestalte eine übersichtliche Dashboard-Oberfläche zur Datenverwaltung mit Karten, Filtern und Beispieldaten.",
    "pt": "Crie uma interface de dashboard de gestão de dados limpa com cards, filtros e dados fictícios.",
    "ru": "Создай аккуратный интерфейс дашборда управления данными с карточками, фильтрами и тестовыми данными.",
    "zh": "设计一个简洁的数据管理仪表盘界面，包含卡片、筛选器和模拟数据。",
    "ja": "カード、フィルター、モックデータを備えたすっきりしたデータ管理ダッシュボード画面をデザインして。",
    "ar": "صمّم واجهة لوحة إدارة بيانات أنيقة ببطاقات ومرشّحات وبيانات وهمية."
  },
  "Design a sleek personal portfolio page showcasing works, skills, and a contact form.": {
    "tr": "Çalışmalarımı, yeteneklerimi ve iletişim formunu içeren şık ve modern bir kişisel portfolyo sayfası tasarla.",
    "es": "Diseña una página de portafolio personal elegante que muestre trabajos, habilidades y un formulario de contacto.",
    "fr": "Conçois une page de portfolio personnel élégante présentant travaux, compétences et un formulaire de contact.",
    "de": "Gestalte eine elegante persönliche Portfolio-Seite, die Arbeiten, Fähigkeiten und ein Kontaktformular präsentiert.",
    "pt": "Crie uma página de portfólio pessoal elegante exibindo trabalhos, habilidades e um formulário de contato.",
    "ru": "Создай элегантную страницу личного портфолио с работами, навыками и формой обратной связи.",
    "zh": "设计一个精致的个人作品集页面，展示作品、技能和联系表单。",
    "ja": "作品、スキル、お問い合わせフォームを見せる洗練されたパーソナルポートフォリオページをデザインして。",
    "ar": "صمّم صفحة معرض أعمال شخصي أنيقة تعرض الأعمال والمهارات ونموذج تواصل."
  },
  "Design a sleek login screen with social auth integration and input validation utilizing a glassmorphism style.": {
    "tr": "Sosyal medya girişleri ve form doğrulaması bulunan, cam morumsu (glassmorphism) efektli şık bir Login ekranı tasarla.",
    "es": "Diseña una pantalla de inicio de sesión elegante con integración de autenticación social y validación de entradas, usando un estilo glassmorphism.",
    "fr": "Conçois un écran de connexion élégant avec authentification sociale et validation des champs, dans un style glassmorphism.",
    "de": "Gestalte einen eleganten Login-Screen mit Social-Auth-Integration und Eingabevalidierung im Glassmorphism-Stil.",
    "pt": "Crie uma tela de login elegante com integração de autenticação social e validação de entrada, usando estilo glassmorphism.",
    "ru": "Создай стильный экран входа с интеграцией входа через соцсети и валидацией полей в стиле glassmorphism.",
    "zh": "设计一个精致的登录界面，集成社交登录和输入校验，采用毛玻璃（glassmorphism）风格。",
    "ja": "ソーシャル認証連携と入力バリデーションを備え、グラスモーフィズムのスタイルを活かした洗練されたログイン画面をデザインして。",
    "ar": "صمّم شاشة تسجيل دخول أنيقة بتكامل مصادقة اجتماعية والتحقق من الإدخال بأسلوب glassmorphism."
  },
  "en-US": {
    "tr": "tr-TR",
    "es": "es-ES",
    "fr": "fr-FR",
    "de": "de-DE",
    "pt": "pt-BR",
    "ru": "ru-RU",
    "zh": "zh-CN",
    "ja": "ja-JP",
    "ar": "ar-SA"
  },
  "Remember this? ": {
    "tr": "Bunu hatırla? ",
    "es": "¿Recordar esto? ",
    "fr": "S'en souvenir ? ",
    "de": "Das merken? ",
    "pt": "Lembrar disso? ",
    "ru": "Запомнить это? ",
    "zh": "记住这个？ ",
    "ja": "これを覚えておく？ ",
    "ar": "أتتذكر هذا؟ "
  },
  "Approve": {
    "tr": "Onayla",
    "es": "Aprobar",
    "fr": "Approuver",
    "de": "Genehmigen",
    "pt": "Aprovar",
    "ru": "Одобрить",
    "zh": "批准",
    "ja": "承認",
    "ar": "موافقة"
  },
  "Dismiss": {
    "tr": "Yoksay",
    "es": "Descartar",
    "fr": "Ignorer",
    "de": "Verwerfen",
    "pt": "Descartar",
    "ru": "Пропустить",
    "zh": "忽略",
    "ja": "却下",
    "ar": "تجاهل"
  },
  "comment(s) queued": {
    "tr": "yorum sırada",
    "es": "comentario(s) en cola",
    "fr": "commentaire(s) en file",
    "de": "Kommentar(e) in Warteschlange",
    "pt": "comentário(s) na fila",
    "ru": "комментариев в очереди",
    "zh": "条评论已排队",
    "ja": "件のコメントが待機中",
    "ar": "تعليق(ات) في الطابور"
  },
  "attaches to the next turn": {
    "tr": "sonraki tura iliştirilecek",
    "es": "se adjunta al siguiente turno",
    "fr": "sera joint au prochain tour",
    "de": "wird an den nächsten Durchlauf angehängt",
    "pt": "anexa-se ao próximo turno",
    "ru": "прикрепится к следующему ходу",
    "zh": "将附加到下一轮",
    "ja": "次のターンに添付されます",
    "ar": "يُرفق بالدور التالي"
  },
  "Apply now": {
    "tr": "Şimdi uygula",
    "es": "Aplicar ahora",
    "fr": "Appliquer maintenant",
    "de": "Jetzt anwenden",
    "pt": "Aplicar agora",
    "ru": "Применить сейчас",
    "zh": "立即应用",
    "ja": "今すぐ適用",
    "ar": "طبّق الآن"
  },
  "Discard comments": {
    "tr": "Yorumları sil",
    "es": "Descartar comentarios",
    "fr": "Supprimer les commentaires",
    "de": "Kommentare verwerfen",
    "pt": "Descartar comentários",
    "ru": "Удалить комментарии",
    "zh": "丢弃评论",
    "ja": "コメントを破棄",
    "ar": "تجاهل التعليقات"
  },
  "will be analyzed with your message": {
    "tr": "mesajla birlikte analiz edilecek",
    "es": "se analizará junto con tu mensaje",
    "fr": "sera analysé avec votre message",
    "de": "wird mit deiner Nachricht analysiert",
    "pt": "será analisado junto com sua mensagem",
    "ru": "будет проанализировано вместе с вашим сообщением",
    "zh": "将与你的消息一起分析",
    "ja": "メッセージと一緒に分析されます",
    "ar": "سيُحلَّل مع رسالتك"
  },
  "turn running — Enter queues your text as a TASK": {
    "tr": "tur koşuyor — Enter yazdığını GÖREV olarak kuyruğa ekler",
    "es": "turno en curso — Enter pone tu texto en cola como TAREA",
    "fr": "tour en cours — Entrée met votre texte en file comme TÂCHE",
    "de": "Durchlauf läuft — Enter stellt deinen Text als AUFGABE in die Warteschlange",
    "pt": "turno em execução — Enter enfileira seu texto como TAREFA",
    "ru": "ход выполняется — Enter добавит текст как ЗАДАЧУ",
    "zh": "本轮运行中 — 按 Enter 将你的文本作为任务排队",
    "ja": "ターン実行中 — Enterで入力内容をタスクとしてキューに追加",
    "ar": "الدور قيد التشغيل — يضع Enter نصك في الطابور كمهمة"
  },
  "Search for models": {
    "tr": "Arama yapın",
    "es": "Buscar modelos",
    "fr": "Rechercher des modèles",
    "de": "Nach Modellen suchen",
    "pt": "Buscar modelos",
    "ru": "Поиск моделей",
    "zh": "搜索模型",
    "ja": "モデルを検索",
    "ar": "ابحث عن نماذج"
  },
  "downloads": {
    "tr": "indirme",
    "es": "descargas",
    "fr": "téléchargements",
    "de": "Downloads",
    "pt": "downloads",
    "ru": "загрузок",
    "zh": "下载量",
    "ja": "ダウンロード数",
    "ar": "تنزيلات"
  },
  "No downloaded models yet": {
    "tr": "Henüz indirilen model yok",
    "es": "Aún no hay modelos descargados",
    "fr": "Aucun modèle téléchargé",
    "de": "Noch keine heruntergeladenen Modelle",
    "pt": "Nenhum modelo baixado ainda",
    "ru": "Скачанных моделей пока нет",
    "zh": "尚无已下载的模型",
    "ja": "ダウンロード済みのモデルはまだありません",
    "ar": "لا توجد نماذج مُنزَّلة بعد"
  },
  "why asking: ": {
    "tr": "neden soruluyor: ",
    "es": "por qué se pregunta: ",
    "fr": "raison de la demande : ",
    "de": "warum gefragt: ",
    "pt": "por que perguntar: ",
    "ru": "почему спрашиваю: ",
    "zh": "询问原因： ",
    "ja": "確認理由： ",
    "ar": "سبب السؤال: "
  },
  "General": {
    "tr": "Genel",
    "es": "General",
    "fr": "Général",
    "de": "Allgemein",
    "pt": "Geral",
    "ru": "Общие",
    "zh": "通用",
    "ja": "一般",
    "ar": "عام"
  },
  "Providers": {
    "tr": "Sağlayıcılar",
    "es": "Proveedores",
    "fr": "Fournisseurs",
    "de": "Anbieter",
    "pt": "Provedores",
    "ru": "Провайдеры",
    "zh": "提供方",
    "ja": "プロバイダー",
    "ar": "المزوّدون"
  },
  "Models": {
    "tr": "Modeller",
    "es": "Modelos",
    "fr": "Modèles",
    "de": "Modelle",
    "pt": "Modelos",
    "ru": "Модели",
    "zh": "模型",
    "ja": "モデル",
    "ar": "النماذج"
  },
  "Trust & Permissions": {
    "tr": "Güven & İzinler",
    "es": "Confianza y permisos",
    "fr": "Confiance & Autorisations",
    "de": "Vertrauen & Berechtigungen",
    "pt": "Confiança e permissões",
    "ru": "Доверие и разрешения",
    "zh": "信任与权限",
    "ja": "信頼と権限",
    "ar": "الثقة والأذونات"
  },
  "Prompt & Rules": {
    "tr": "Prompt & Kurallar",
    "es": "Prompt y reglas",
    "fr": "Prompt & Règles",
    "de": "Prompt & Regeln",
    "pt": "Prompt e regras",
    "ru": "Промпт и правила",
    "zh": "提示词与规则",
    "ja": "プロンプトとルール",
    "ar": "الموجّه والقواعد"
  },
  "Knowledge": {
    "tr": "Bilgi Tabanı",
    "es": "Conocimiento",
    "fr": "Connaissances",
    "de": "Wissen",
    "pt": "Conhecimento",
    "ru": "База знаний",
    "zh": "知识库",
    "ja": "ナレッジ",
    "ar": "قاعدة المعرفة"
  },
  "Tools": {
    "tr": "Araçlar",
    "es": "Herramientas",
    "fr": "Outils",
    "de": "Werkzeuge",
    "pt": "Ferramentas",
    "ru": "Инструменты",
    "zh": "工具",
    "ja": "ツール",
    "ar": "الأدوات"
  },
  "Commands": {
    "tr": "Komutlar",
    "es": "Comandos",
    "fr": "Commandes",
    "de": "Befehle",
    "pt": "Comandos",
    "ru": "Команды",
    "zh": "命令",
    "ja": "コマンド",
    "ar": "الأوامر"
  },
  "Appearance": {
    "tr": "Görünüm",
    "es": "Apariencia",
    "fr": "Apparence",
    "de": "Erscheinungsbild",
    "pt": "Aparência",
    "ru": "Внешний вид",
    "zh": "外观",
    "ja": "外観",
    "ar": "المظهر"
  },
  "Theme": {
    "tr": "Tema",
    "es": "Tema",
    "fr": "Thème",
    "de": "Design",
    "pt": "Tema",
    "ru": "Тема",
    "zh": "主题",
    "ja": "テーマ",
    "ar": "السمة"
  },
  "Light": {
    "tr": "Açık",
    "es": "Claro",
    "fr": "Clair",
    "de": "Hell",
    "pt": "Claro",
    "ru": "Светлая",
    "zh": "浅色",
    "ja": "ライト",
    "ar": "فاتح"
  },
  "Dark": {
    "tr": "Koyu",
    "es": "Oscuro",
    "fr": "Sombre",
    "de": "Dunkel",
    "pt": "Escuro",
    "ru": "Тёмная",
    "zh": "深色",
    "ja": "ダーク",
    "ar": "داكن"
  },
  "Language": {
    "tr": "Dil",
    "es": "Idioma",
    "fr": "Langue",
    "de": "Sprache",
    "pt": "Idioma",
    "ru": "Язык",
    "zh": "语言",
    "ja": "言語",
    "ar": "اللغة"
  },
  "text-ink-dim hover:text-ink-mut": {
    "tr": "bg-ink-card text-ink-text shadow-sm",
    "es": "text-ink-dim hover:text-ink-mut",
    "fr": "text-ink-dim hover:text-ink-mut",
    "de": "text-ink-dim hover:text-ink-mut",
    "pt": "text-ink-dim hover:text-ink-mut",
    "ru": "text-ink-dim hover:text-ink-mut",
    "zh": "text-ink-dim hover:text-ink-mut",
    "ja": "bg-ink-card text-ink-text shadow-sm",
    "ar": "text-ink-dim hover:text-ink-mut"
  },
  "Interface Size": {
    "tr": "Arayüz Boyutu",
    "es": "Tamaño de interfaz",
    "fr": "Taille de l'interface",
    "de": "Oberflächengröße",
    "pt": "Tamanho da interface",
    "ru": "Размер интерфейса",
    "zh": "界面大小",
    "ja": "インターフェースのサイズ",
    "ar": "حجم الواجهة"
  },
  "Enlarge if text and the whole UI (sidebar, chat, tabs) feel too small. Shortcut: Ctrl with + / − / 0.": {
    "tr": "Yazılar ve tüm arayüz (sidebar, sohbet, sekmeler) küçük geliyorsa büyüt. Kısayol: Ctrl ile + / − / 0.",
    "es": "Amplía si el texto y toda la interfaz (barra lateral, chat, pestañas) se ven demasiado pequeños. Atajo: Ctrl con + / − / 0.",
    "fr": "Agrandissez si le texte et toute l'interface (barre latérale, discussion, onglets) semblent trop petits. Raccourci : Ctrl avec + / − / 0.",
    "de": "Vergrößern, wenn Text und die gesamte Oberfläche (Seitenleiste, Chat, Tabs) zu klein wirken. Kürzel: Strg mit + / − / 0.",
    "pt": "Aumente se o texto e toda a interface (barra lateral, chat, abas) parecerem pequenos demais. Atalho: Ctrl com + / − / 0.",
    "ru": "Увеличьте, если текст и весь интерфейс (боковая панель, чат, вкладки) кажутся мелкими. Горячие клавиши: Ctrl с + / − / 0.",
    "zh": "若文字和整个界面（侧栏、对话、标签页）显得太小，可放大。快捷键：Ctrl 加 + / − / 0。",
    "ja": "文字やUI全体（サイドバー、チャット、タブ）が小さすぎると感じたら拡大してください。ショートカット：Ctrl と + / − / 0。",
    "ar": "كبّر إذا بدا النص وكامل الواجهة (الشريط الجانبي، المحادثة، الألسنة) صغيرًا جدًا. الاختصار: Ctrl مع + / − / 0."
  },
  "Smaller (Ctrl −)": {
    "tr": "Küçült (Ctrl −)",
    "es": "Reducir (Ctrl −)",
    "fr": "Réduire (Ctrl −)",
    "de": "Kleiner (Strg −)",
    "pt": "Menor (Ctrl −)",
    "ru": "Меньше (Ctrl −)",
    "zh": "缩小（Ctrl −）",
    "ja": "小さく（Ctrl −）",
    "ar": "أصغر (Ctrl −)"
  },
  "Larger (Ctrl +)": {
    "tr": "Büyüt (Ctrl +)",
    "es": "Ampliar (Ctrl +)",
    "fr": "Agrandir (Ctrl +)",
    "de": "Größer (Strg +)",
    "pt": "Maior (Ctrl +)",
    "ru": "Больше (Ctrl +)",
    "zh": "放大（Ctrl +）",
    "ja": "大きく（Ctrl +）",
    "ar": "أكبر (Ctrl +)"
  },
  "Ask before sending to the API (confirm with \"fix api\")": {
    "tr": "API'ye göndermeden önce sor (\"düzelt api\" ile onayla)",
    "es": "Preguntar antes de enviar a la API (confirma con \"fix api\")",
    "fr": "Demander avant l'envoi à l'API (confirmer avec « fix api »)",
    "de": "Vor dem Senden an die API fragen (mit \"fix api\" bestätigen)",
    "pt": "Perguntar antes de enviar para a API (confirme com \"fix api\")",
    "ru": "Спрашивать перед отправкой в API (подтвердить командой \"fix api\")",
    "zh": "发送到 API 前询问（用“fix api”确认）",
    "ja": "APIに送信する前に確認する（「fix api」で承認）",
    "ar": "اسأل قبل الإرسال إلى API (أكّد بكتابة \"fix api\")"
  },
  "What the agent may execute. Hard denies (root-path deletion, sudo, pipe-to-shell) never run in ANY tier.": {
    "tr": "Ajanın komut çalıştırma yetkisi. Koşulsuz yasaklar (kök yolu silme, sudo, boru-ile-kabuk) HİÇBİR kipte çalışmaz.",
    "es": "Lo que el agente puede ejecutar. Los bloqueos absolutos (borrado de ruta raíz, sudo, pipe-a-shell) nunca se ejecutan en NINGÚN nivel.",
    "fr": "Ce que l'agent peut exécuter. Les interdictions strictes (suppression de chemin racine, sudo, pipe-vers-shell) ne s'exécutent dans AUCUN niveau.",
    "de": "Was der Agent ausführen darf. Absolute Verbote (Löschen von Root-Pfaden, sudo, Pipe-to-Shell) laufen in KEINER Stufe.",
    "pt": "O que o agente pode executar. Bloqueios rígidos (exclusão de caminho raiz, sudo, pipe-para-shell) nunca são executados em NENHUM nível.",
    "ru": "Что агент может выполнять. Жёсткие запреты (удаление корневого пути, sudo, pipe-to-shell) не работают НИ в одном режиме.",
    "zh": "智能体可执行的操作。硬性禁止项（删除根路径、sudo、管道到 shell）在任何等级下都不会运行。",
    "ja": "エージェントが実行できる範囲。絶対拒否（ルートパスの削除、sudo、パイプ経由のシェル実行）はどのティアでも実行されません。",
    "ar": "ما يُسمح للوكيل بتنفيذه. المنع القاطع (حذف المسار الجذري، sudo، التوجيه إلى الطرفية) لا يعمل أبدًا في أي مستوى."
  },
  "Read Only": {
    "tr": "Salt Okunur",
    "es": "Solo lectura",
    "fr": "Lecture seule",
    "de": "Nur Lesen",
    "pt": "Somente leitura",
    "ru": "Только чтение",
    "zh": "只读",
    "ja": "読み取り専用",
    "ar": "قراءة فقط"
  },
  "no command/download runs — the agent only proposes": {
    "tr": "hiçbir komut/indirme çalışmaz — ajan yalnız önerir",
    "es": "no se ejecuta ningún comando/descarga — el agente solo propone",
    "fr": "aucune commande/téléchargement ne s'exécute — l'agent se contente de proposer",
    "de": "kein Befehl/Download läuft — der Agent schlägt nur vor",
    "pt": "nenhum comando/download é executado — o agente apenas propõe",
    "ru": "команды/загрузки не выполняются — агент только предлагает",
    "zh": "不运行任何命令/下载 — 智能体仅提出建议",
    "ja": "コマンドやダウンロードは実行されず、エージェントは提案のみ",
    "ar": "لا يُنفَّذ أي أمر/تنزيل — يكتفي الوكيل بالاقتراح"
  },
  "Auto (recommended)": {
    "tr": "Otomatik (önerilen)",
    "es": "Automático (recomendado)",
    "fr": "Auto (recommandé)",
    "de": "Auto (empfohlen)",
    "pt": "Automático (recomendado)",
    "ru": "Авто (рекомендуется)",
    "zh": "自动（推荐）",
    "ja": "自動（推奨）",
    "ar": "تلقائي (موصى به)"
  },
  "safe in-workspace commands run free; everything at the boundary asks": {
    "tr": "çalışma alanı içi güvenli komutlar serbest; sınırda olan her şey sorulur",
    "es": "los comandos seguros dentro del espacio de trabajo se ejecutan libremente; todo lo que esté en el límite se pregunta",
    "fr": "les commandes sûres dans l'espace de travail passent librement ; tout ce qui touche la limite est soumis à confirmation",
    "de": "sichere Befehle im Arbeitsbereich laufen frei; alles an der Grenze wird nachgefragt",
    "pt": "comandos seguros dentro do espaço de trabalho rodam livremente; tudo que está no limite é perguntado",
    "ru": "безопасные команды внутри рабочей области выполняются свободно; всё на границе — по запросу",
    "zh": "工作区内的安全命令自由运行；边界上的一切都会询问",
    "ja": "ワークスペース内の安全なコマンドは自由に実行、境界にあるものはすべて確認",
    "ar": "تُنفَّذ الأوامر الآمنة داخل مساحة العمل بحرية؛ وكل ما على الحدود يُستأذن فيه"
  },
  "Full Access": {
    "tr": "Tam Erişim",
    "es": "Acceso total",
    "fr": "Accès complet",
    "de": "Vollzugriff",
    "pt": "Acesso total",
    "ru": "Полный доступ",
    "zh": "完全访问",
    "ja": "フルアクセス",
    "ar": "وصول كامل"
  },
  "boundary items run unasked — hard denies still never run": {
    "tr": "sınırdakiler de onaysız koşar — koşulsuz yasaklar yine çalışmaz",
    "es": "los elementos del límite se ejecutan sin preguntar — los bloqueos absolutos siguen sin ejecutarse nunca",
    "fr": "les éléments à la limite s'exécutent sans demande — les interdictions strictes restent bloquées",
    "de": "Grenzfälle laufen ohne Nachfrage — absolute Verbote laufen weiterhin nie",
    "pt": "itens no limite rodam sem perguntar — bloqueios rígidos ainda nunca são executados",
    "ru": "граничные действия выполняются без запроса — жёсткие запреты всё равно не работают",
    "zh": "边界项无需询问即运行 — 硬性禁止项仍绝不运行",
    "ja": "境界の項目も確認なしで実行 — 絶対拒否は依然として実行されません",
    "ar": "تُنفَّذ العناصر الحدّية دون سؤال — أما المنع القاطع فلا يعمل أبدًا"
  },
  "Allow list (one prefix per line)": {
    "tr": "İzin listesi (satır başına önek)",
    "es": "Lista de permitidos (un prefijo por línea)",
    "fr": "Liste d'autorisation (un préfixe par ligne)",
    "de": "Erlaubnisliste (ein Präfix pro Zeile)",
    "pt": "Lista de permissões (um prefixo por linha)",
    "ru": "Список разрешённых (один префикс на строку)",
    "zh": "允许列表（每行一个前缀）",
    "ja": "許可リスト（1行に1プレフィックス）",
    "ar": "قائمة السماح (بادئة واحدة لكل سطر)"
  },
  "Deny list (blocks in every tier)": {
    "tr": "Yasak listesi (her kipte engel)",
    "es": "Lista de bloqueados (bloquea en todos los niveles)",
    "fr": "Liste d'interdiction (bloque à tous les niveaux)",
    "de": "Verbotsliste (blockiert in jeder Stufe)",
    "pt": "Lista de bloqueios (bloqueia em todos os níveis)",
    "ru": "Список запрещённых (блокирует во всех режимах)",
    "zh": "拒绝列表（在所有等级下阻止）",
    "ja": "拒否リスト（すべてのティアでブロック）",
    "ar": "قائمة المنع (تحظر في كل مستوى)"
  },
  "Engine Scorecard": {
    "tr": "Motor Karnesi",
    "es": "Boletín del motor",
    "fr": "Bulletin du moteur",
    "de": "Engine-Zeugnis",
    "pt": "Boletim do motor",
    "ru": "Табель движка",
    "zh": "引擎成绩单",
    "ja": "エンジンスコアカード",
    "ar": "بطاقة أداء المحرّك"
  },
  "The Debug Engine's real field performance on this device (from repair telemetry).": {
    "tr": "Debug Engine'in bu cihazdaki gerçek saha performansı (onarım telemetrisinden).",
    "es": "Rendimiento real del Debug Engine en este dispositivo (según la telemetría de reparaciones).",
    "fr": "Performances réelles du Debug Engine sur cet appareil (d'après la télémétrie de réparation).",
    "de": "Die reale Praxisleistung der Debug-Engine auf diesem Gerät (aus der Reparatur-Telemetrie).",
    "pt": "O desempenho real do Debug Engine neste dispositivo (a partir da telemetria de reparos).",
    "ru": "Реальная полевая производительность Debug Engine на этом устройстве (по телеметрии ремонта).",
    "zh": "Debug 引擎在本设备上的真实实战表现（来自修复遥测数据）。",
    "ja": "このデバイスでのDebug Engineの実際のフィールド性能（修復テレメトリより）。",
    "ar": "الأداء الميداني الحقيقي لمحرّك التصحيح على هذا الجهاز (من قياسات الإصلاح)."
  },
  "Total repair events": {
    "tr": "Toplam onarım olayı",
    "es": "Total de eventos de reparación",
    "fr": "Total des événements de réparation",
    "de": "Reparaturereignisse insgesamt",
    "pt": "Total de eventos de reparo",
    "ru": "Всего событий ремонта",
    "zh": "修复事件总数",
    "ja": "修復イベント合計",
    "ar": "إجمالي أحداث الإصلاح"
  },
  "Model-free repair hit rate (rung 0)": {
    "tr": "Modelsiz onarım isabeti (Kat 0)",
    "es": "Tasa de acierto de reparación sin modelo (nivel 0)",
    "fr": "Taux de réparation sans modèle (niveau 0)",
    "de": "Trefferquote modellfreie Reparatur (Stufe 0)",
    "pt": "Taxa de acerto de reparos sem modelo (nível 0)",
    "ru": "Доля попаданий ремонта без модели (уровень 0)",
    "zh": "无模型修复命中率（第 0 级）",
    "ja": "モデル不使用での修復成功率（rung 0）",
    "ar": "معدّل نجاح الإصلاح دون نموذج (المستوى 0)"
  },
  "Repro verification rate": {
    "tr": "Repro doğrulama oranı",
    "es": "Tasa de verificación de reproducción",
    "fr": "Taux de vérification par repro",
    "de": "Repro-Verifizierungsrate",
    "pt": "Taxa de verificação de repro",
    "ru": "Доля подтверждения репро",
    "zh": "复现验证率",
    "ja": "再現検証率",
    "ar": "معدّل التحقق من إعادة الإنتاج"
  },
  "Behavior test pass": {
    "tr": "Davranış testi geçme",
    "es": "Pruebas de comportamiento superadas",
    "fr": "Réussite des tests de comportement",
    "de": "Verhaltenstest bestanden",
    "pt": "Aprovação em teste de comportamento",
    "ru": "Прохождение теста поведения",
    "zh": "行为测试通过",
    "ja": "動作テスト合格",
    "ar": "نجاح اختبار السلوك"
  },
  "No telemetry yet — this fills as the engine works.": {
    "tr": "Henüz telemetri yok — motor çalıştıkça burası dolacak.",
    "es": "Aún no hay telemetría — se irá llenando a medida que el motor trabaje.",
    "fr": "Aucune télémétrie — se remplira à mesure que le moteur travaille.",
    "de": "Noch keine Telemetrie — füllt sich, während die Engine arbeitet.",
    "pt": "Nenhuma telemetria ainda — isto se preenche à medida que o motor trabalha.",
    "ru": "Телеметрии пока нет — заполнится по мере работы движка.",
    "zh": "暂无遥测数据 — 引擎运行时此处会填充。",
    "ja": "テレメトリはまだありません — エンジンが動作するにつれてここが埋まります。",
    "ar": "لا توجد قياسات بعد — يمتلئ هذا كلما عمل المحرّك."
  },
  "GPU Acceleration (Experimental)": {
    "tr": "GPU Hızlandırması (Deneysel)",
    "es": "Aceleración por GPU (experimental)",
    "fr": "Accélération GPU (expérimental)",
    "de": "GPU-Beschleunigung (experimentell)",
    "pt": "Aceleração por GPU (Experimental)",
    "ru": "Ускорение GPU (экспериментально)",
    "zh": "GPU 加速（实验性）",
    "ja": "GPUアクセラレーション（実験的）",
    "ar": "تسريع بمعالج الرسومات (تجريبي)"
  },
  "Uses graphics card (CUDA/Vulkan) for model operations. Keep disabled if you experience app crashes or errors during load.": {
    "tr": "Model işlemlerinde ekran kartını (CUDA/Vulkan) kullanır. Eğer uygulama açılırken çöküyorsa veya hata alıyorsanız kapalı tutun.",
    "es": "Usa la tarjeta gráfica (CUDA/Vulkan) para las operaciones del modelo. Mantenla desactivada si la app se cierra o da errores durante la carga.",
    "fr": "Utilise la carte graphique (CUDA/Vulkan) pour les opérations du modèle. Laissez désactivé si l'app plante ou renvoie des erreurs au chargement.",
    "de": "Nutzt die Grafikkarte (CUDA/Vulkan) für Modelloperationen. Deaktiviert lassen, falls die App beim Laden abstürzt oder Fehler auftreten.",
    "pt": "Usa a placa de vídeo (CUDA/Vulkan) para as operações do modelo. Mantenha desativado se a aplicação travar ou apresentar erros durante o carregamento.",
    "ru": "Использует видеокарту (CUDA/Vulkan) для операций модели. Оставьте выключенным, если приложение вылетает или выдаёт ошибки при загрузке.",
    "zh": "在模型运算中使用显卡（CUDA/Vulkan）。若加载时出现应用崩溃或错误，请保持关闭。",
    "ja": "モデル処理にグラフィックカード（CUDA/Vulkan）を使用します。読み込み中にアプリがクラッシュしたりエラーが出る場合は無効のままにしてください。",
    "ar": "يستخدم بطاقة الرسومات (CUDA/Vulkan) لعمليات النموذج. أبقِه معطّلًا إذا واجهت أعطالًا أو أخطاء أثناء التحميل."
  },
  "GPU Layers": {
    "tr": "GPU Katmanları",
    "es": "Capas de GPU",
    "fr": "Couches GPU",
    "de": "GPU-Layer",
    "pt": "Camadas da GPU",
    "ru": "Слои GPU",
    "zh": "GPU 层数",
    "ja": "GPUレイヤー",
    "ar": "طبقات GPU"
  },
  "Auto": {
    "tr": "Otomatik",
    "es": "Automático",
    "fr": "Auto",
    "de": "Auto",
    "pt": "Automático",
    "ru": "Авто",
    "zh": "自动",
    "ja": "自動",
    "ar": "تلقائي"
  },
  "How many model layers to offload to the GPU. Auto measures free VRAM and offloads as many layers as fit — partial speedup even on small cards. Takes effect on the next model load.": {
    "tr": "Modelin kaç katmanı ekran kartına yüklensin? Otomatik: boş VRAM ölçülür, sığan kadar katman GPU’ya verilir — küçük kartlarda bile kısmi hızlanma sağlar. Yeni model yüklemesinde geçerli olur.",
    "es": "Cuántas capas del modelo descargar a la GPU. Automático mide la VRAM libre y descarga tantas capas como quepan — aceleración parcial incluso en tarjetas pequeñas. Se aplica en la próxima carga del modelo.",
    "fr": "Nombre de couches du modèle à décharger sur le GPU. Auto mesure la VRAM libre et décharge autant de couches que possible — accélération partielle même sur les petites cartes. Prend effet au prochain chargement du modèle.",
    "de": "Wie viele Modell-Layer auf die GPU ausgelagert werden. Auto misst den freien VRAM und lagert so viele Layer aus, wie passen — teilweise Beschleunigung selbst auf kleinen Karten. Wird beim nächsten Laden des Modells wirksam.",
    "pt": "Quantas camadas do modelo descarregar na GPU. O modo Automático mede a VRAM livre e descarrega quantas camadas couberem — aceleração parcial mesmo em placas pequenas. Aplica-se no próximo carregamento do modelo.",
    "ru": "Сколько слоёв модели выгрузить на GPU. Авто измеряет свободную VRAM и выгружает столько слоёв, сколько поместится — частичное ускорение даже на слабых картах. Применяется при следующей загрузке модели.",
    "zh": "将多少个模型层卸载到 GPU。自动模式会测量空闲显存并尽量卸载 — 即便小显卡也能部分加速。下次加载模型时生效。",
    "ja": "モデルのレイヤーをいくつGPUにオフロードするか。自動：空きVRAMを計測し、収まるだけのレイヤーをオフロード — 小さなカードでも部分的に高速化します。次回のモデル読み込み時に反映されます。",
    "ar": "عدد طبقات النموذج التي تُنقل إلى GPU. يقيس الوضع التلقائي ذاكرة VRAM المتاحة وينقل ما يتّسع من الطبقات — تسريع جزئي حتى على البطاقات الصغيرة. يسري عند تحميل النموذج التالي."
  },
  "Local Vision Model (analysis)": {
    "tr": "Yerel Görsel Modeli (analiz)",
    "es": "Modelo de visión local (análisis)",
    "fr": "Modèle de vision local (analyse)",
    "de": "Lokales Vision-Modell (Analyse)",
    "pt": "Modelo de visão local (análise)",
    "ru": "Локальная модель зрения (анализ)",
    "zh": "本地视觉模型（分析）",
    "ja": "ローカルビジョンモデル（分析）",
    "ar": "نموذج الرؤية المحلي (التحليل)"
  },
  "The model that analyzes attached images LOCALLY (local-model only; on an API model the image goes straight to the API). Not fixed to Qwen — any VL GGUF you download (model + mmproj) shows up here. Auto: the largest installed model that fits RAM.": {
    "tr": "İliştirilen görselleri YEREL olarak analiz eden model (yalnız yerel modelde; API modelinde görsel doğrudan API’ye gider). Qwen’e sabit değil — indirdiğin herhangi bir VL GGUF (model + mmproj) burada çıkar. Oto: RAM’e sığan en büyük yüklü model.",
    "es": "El modelo que analiza las imágenes adjuntas LOCALMENTE (solo con modelo local; con un modelo de API la imagen va directa a la API). No está fijado a Qwen — cualquier VL GGUF que descargues (modelo + mmproj) aparece aquí. Automático: el modelo instalado más grande que quepa en la RAM.",
    "fr": "Le modèle qui analyse LOCALEMENT les images jointes (modèle local uniquement ; sur un modèle API, l'image va directement à l'API). Non limité à Qwen — tout GGUF VL téléchargé (modèle + mmproj) apparaît ici. Auto : le plus grand modèle installé tenant en RAM.",
    "de": "Das Modell, das angehängte Bilder LOKAL analysiert (nur beim lokalen Modell; bei einem API-Modell geht das Bild direkt an die API). Nicht auf Qwen festgelegt — jedes von dir heruntergeladene VL-GGUF (Modell + mmproj) erscheint hier. Auto: das größte installierte Modell, das in den RAM passt.",
    "pt": "O modelo que analisa imagens anexadas LOCALMENTE (apenas no modelo local; em um modelo de API a imagem vai direto para a API). Não está fixo no Qwen — qualquer GGUF de VL que você baixe (modelo + mmproj) aparece aqui. Automático: o maior modelo instalado que couber na RAM.",
    "ru": "Модель, анализирующая прикреплённые изображения ЛОКАЛЬНО (только для локальной модели; на API-модели изображение идёт прямо в API). Не привязана к Qwen — любой скачанный VL GGUF (модель + mmproj) появится здесь. Авто: крупнейшая установленная модель, помещающаяся в RAM.",
    "zh": "在本地分析所附图片的模型（仅本地模型；使用 API 模型时图片会直接发送到 API）。不限于 Qwen — 你下载的任何 VL GGUF（模型 + mmproj）都会显示在此。自动：内存能容纳的最大已安装模型。",
    "ja": "添付画像をローカルで分析するモデル（ローカルモデルのみ。APIモデルでは画像は直接APIに送られます）。Qwenに固定されておらず、ダウンロードした任意のVL GGUF（モデル + mmproj）がここに表示されます。自動：RAMに収まる最大のインストール済みモデル。",
    "ar": "النموذج الذي يحلّل الصور المرفقة محليًا (في النموذج المحلي فقط؛ أما في نموذج API فتذهب الصورة مباشرةً إلى API). ليس مقيّدًا بـQwen — أي VL GGUF تُنزّله (النموذج + mmproj) يظهر هنا. تلقائي: أكبر نموذج مثبَّت يتّسع في الذاكرة."
  },
  "Auto (largest that fits RAM)": {
    "tr": "Otomatik (RAM’e sığan en büyük)",
    "es": "Automático (el más grande que quepa en la RAM)",
    "fr": "Auto (le plus grand tenant en RAM)",
    "de": "Auto (größtes, das in den RAM passt)",
    "pt": "Automático (o maior que couber na RAM)",
    "ru": "Авто (крупнейшая, что помещается в RAM)",
    "zh": "自动（内存能容纳的最大者）",
    "ja": "自動（RAMに収まる最大のもの）",
    "ar": "تلقائي (الأكبر الذي يتّسع في الذاكرة)"
  },
  "No installed vision model found. A device-appropriate Qwen-VL downloads on first image analysis; or drop your own VL GGUF (model + mmproj) into the models folder.": {
    "tr": "Yüklü görsel modeli bulunamadı. İlk görsel analizinde cihazına uygun bir Qwen-VL otomatik iner; ya da models klasörüne kendi VL GGUF’unu (model + mmproj) koy.",
    "es": "No se encontró ningún modelo de visión instalado. Un Qwen-VL adecuado para tu dispositivo se descarga en el primer análisis de imagen; o coloca tu propio VL GGUF (modelo + mmproj) en la carpeta de modelos.",
    "fr": "Aucun modèle de vision installé. Un Qwen-VL adapté à l'appareil se télécharge lors de la première analyse d'image ; ou déposez votre propre GGUF VL (modèle + mmproj) dans le dossier des modèles.",
    "de": "Kein installiertes Vision-Modell gefunden. Bei der ersten Bildanalyse wird ein gerätepassendes Qwen-VL heruntergeladen; oder leg dein eigenes VL-GGUF (Modell + mmproj) in den Modellordner.",
    "pt": "Nenhum modelo de visão instalado encontrado. Um Qwen-VL adequado ao dispositivo é baixado na primeira análise de imagem; ou coloque seu próprio GGUF de VL (modelo + mmproj) na pasta de modelos.",
    "ru": "Установленная модель зрения не найдена. Подходящая устройству Qwen-VL скачается при первом анализе изображения; или поместите свой VL GGUF (модель + mmproj) в папку моделей.",
    "zh": "未找到已安装的视觉模型。首次图片分析时会自动下载适配设备的 Qwen-VL；或将你自己的 VL GGUF（模型 + mmproj）放入 models 文件夹。",
    "ja": "インストール済みのビジョンモデルが見つかりません。最初の画像分析時にデバイスに適したQwen-VLが自動でダウンロードされます。または独自のVL GGUF（モデル + mmproj）をmodelsフォルダーに配置してください。",
    "ar": "لم يُعثر على نموذج رؤية مثبّت. يُنزَّل Qwen-VL مناسب لجهازك عند أول تحليل صورة؛ أو ضع نموذج VL GGUF خاصًا بك (النموذج + mmproj) في مجلد النماذج."
  },
  "Global Rules": {
    "tr": "Global Kurallar",
    "es": "Reglas globales",
    "fr": "Règles globales",
    "de": "Globale Regeln",
    "pt": "Regras globais",
    "ru": "Глобальные правила",
    "zh": "全局规则",
    "ja": "グローバルルール",
    "ar": "القواعد العامة"
  },
  "Preferences that apply to EVERY project. On conflict the nearer (project) rule wins.": {
    "tr": "HER projede geçerli tercihler. Proje kuralıyla çelişirse yakın olan (proje) kazanır.",
    "es": "Preferencias que se aplican a TODOS los proyectos. En caso de conflicto, gana la regla más cercana (la del proyecto).",
    "fr": "Préférences appliquées à TOUS les projets. En cas de conflit, la règle la plus proche (projet) l'emporte.",
    "de": "Vorgaben, die für JEDES Projekt gelten. Bei Konflikt gewinnt die nähere (Projekt-)Regel.",
    "pt": "Preferências que se aplicam a TODOS os projetos. Em caso de conflito, a regra mais próxima (do projeto) prevalece.",
    "ru": "Предпочтения, применяемые к КАЖДОМУ проекту. При конфликте побеждает более близкое (проектное) правило.",
    "zh": "适用于每个项目的偏好。冲突时，更近的（项目）规则优先。",
    "ja": "すべてのプロジェクトに適用される設定。競合した場合はより近い（プロジェクトの）ルールが優先されます。",
    "ar": "تفضيلات تنطبق على كل مشروع. عند التعارض تفوز القاعدة الأقرب (قاعدة المشروع)."
  },
  "e.g. Always Turkish comments; never skip a11y labels": {
    "tr": "ör. Her zaman Türkçe yorum satırları; erişilebilirlik etiketlerini atlama",
    "es": "p. ej. Comentarios siempre en español; nunca omitas etiquetas de accesibilidad",
    "fr": "ex. Toujours des commentaires en français ; ne jamais omettre les libellés d'accessibilité",
    "de": "z. B. Kommentare immer auf Deutsch; a11y-Labels nie weglassen",
    "pt": "ex.: Sempre comentários em português; nunca omitir rótulos de acessibilidade",
    "ru": "напр.: Всегда комментарии на русском; никогда не пропускай метки доступности",
    "zh": "例如：注释始终用中文；切勿省略无障碍标签",
    "ja": "例：コメントは常に日本語で；アクセシビリティラベルを省略しない",
    "ar": "مثال: تعليقات بالعربية دائمًا؛ لا تتجاوز تسميات الوصول (a11y)"
  },
  "Project Knowledge Base": {
    "tr": "Proje Bilgi Tabanı",
    "es": "Base de conocimiento del proyecto",
    "fr": "Base de connaissances du projet",
    "de": "Projekt-Wissensbasis",
    "pt": "Base de conhecimento do projeto",
    "ru": "База знаний проекта",
    "zh": "项目知识库",
    "ja": "プロジェクトナレッジベース",
    "ar": "قاعدة معرفة المشروع"
  },
  "The engine records what it PROVED here (repair patterns, verified fixes, your review comments) and summarizes them into every turn. Refuted items retire automatically; delete any by hand.": {
    "tr": "Motor bu projede kanıtla öğrendiklerini buraya yazar (onarım kalıpları, doğrulanmış düzeltmeler, senin inceleme yorumların) ve her turun başına özetler. Yanlışlanan madde otomatik emekli olur; istediğini elle de silebilirsin.",
    "es": "El motor registra aquí lo que ha DEMOSTRADO (patrones de reparación, correcciones verificadas, tus comentarios de revisión) y los resume en cada turno. Los elementos refutados se retiran automáticamente; puedes eliminar cualquiera a mano.",
    "fr": "Le moteur consigne ici ce qu'il a PROUVÉ (schémas de réparation, correctifs vérifiés, vos commentaires d'examen) et les résume à chaque tour. Les éléments réfutés se retirent automatiquement ; supprimez-en manuellement au besoin.",
    "de": "Die Engine hält fest, was sie hier BEWIESEN hat (Reparaturmuster, verifizierte Fixes, deine Prüfkommentare) und fasst es in jeden Durchlauf ein. Widerlegte Einträge werden automatisch ausgemustert; einzelne kannst du von Hand löschen.",
    "pt": "O motor registra aqui o que COMPROVOU (padrões de reparo, correções verificadas, seus comentários de revisão) e os resume em cada turno. Itens refutados se aposentam automaticamente; exclua qualquer um manualmente.",
    "ru": "Движок записывает сюда то, что ДОКАЗАЛ (шаблоны ремонта, подтверждённые исправления, ваши комментарии из проверок) и включает это в каждый ход. Опровергнутые пункты выбывают автоматически; любой можно удалить вручную.",
    "zh": "引擎会把在此已验证的内容记录下来（修复模式、已验证的修复、你的评审评论），并在每一轮开头汇总。被推翻的条目会自动退役；也可手动删除任意条目。",
    "ja": "エンジンがこのプロジェクトで実証したこと（修復パターン、検証済みの修正、あなたのレビューコメント）をここに記録し、毎ターンの冒頭に要約します。反証された項目は自動的に引退します。手動で削除することもできます。",
    "ar": "يسجّل المحرّك هنا ما أثبته (أنماط الإصلاح، الإصلاحات المتحقَّق منها، تعليقات مراجعتك) ويلخّصها في كل دور. تتقاعد العناصر المدحوضة تلقائيًا؛ ويمكنك حذف أي عنصر يدويًا."
  },
  "No items yet — fills as the engine repairs and you comment.": {
    "tr": "Henüz madde yok — motor onardıkça ve sen yorumladıkça dolacak.",
    "es": "Aún no hay elementos — se llena a medida que el motor repara y tú comentas.",
    "fr": "Aucun élément — se remplit à mesure que le moteur répare et que vous commentez.",
    "de": "Noch keine Einträge — füllt sich, während die Engine repariert und du kommentierst.",
    "pt": "Nenhum item ainda — preenche-se à medida que o motor repara e você comenta.",
    "ru": "Пунктов пока нет — заполнится по мере ремонта движком и ваших комментариев.",
    "zh": "暂无条目 — 随引擎修复与你的评论逐渐填充。",
    "ja": "項目はまだありません — エンジンが修復し、あなたがコメントするにつれて埋まります。",
    "ar": "لا توجد عناصر بعد — يمتلئ كلما أصلح المحرّك وعلّقتَ أنت."
  },
  "Delete item": {
    "tr": "Maddeyi sil",
    "es": "Eliminar elemento",
    "fr": "Supprimer l'élément",
    "de": "Eintrag löschen",
    "pt": "Excluir item",
    "ru": "Удалить пункт",
    "zh": "删除条目",
    "ja": "項目を削除",
    "ar": "حذف العنصر"
  },
  "System": {
    "tr": "Sistem",
    "es": "Sistema",
    "fr": "Système",
    "de": "System",
    "pt": "Sistema",
    "ru": "Система",
    "zh": "系统",
    "ja": "システム",
    "ar": "النظام"
  },
  "Notify when a long run finishes (if backgrounded)": {
    "tr": "Uzun koşu bitince bildir (pencere arka plandaysa)",
    "es": "Notificar cuando termine una ejecución larga (si está en segundo plano)",
    "fr": "Notifier à la fin d'une exécution longue (si en arrière-plan)",
    "de": "Benachrichtigen, wenn ein langer Durchlauf endet (bei Fenster im Hintergrund)",
    "pt": "Notificar quando uma execução longa terminar (se em segundo plano)",
    "ru": "Уведомлять, когда завершится долгий запуск (если окно свёрнуто)",
    "zh": "长任务完成时通知（若窗口在后台）",
    "ja": "長い処理が完了したら通知（バックグラウンド時）",
    "ar": "أبلغني عند انتهاء عملية طويلة (إن كانت في الخلفية)"
  },
  "Keep the machine awake during runs": {
    "tr": "Koşarken makinenin uyumasını engelle",
    "es": "Mantener el equipo activo durante las ejecuciones",
    "fr": "Empêcher la mise en veille de la machine pendant les exécutions",
    "de": "Gerät während der Durchläufe wach halten",
    "pt": "Manter a máquina ativa durante as execuções",
    "ru": "Не давать компьютеру засыпать во время запусков",
    "zh": "运行期间保持机器唤醒",
    "ja": "処理中はマシンをスリープさせない",
    "ar": "أبقِ الجهاز مستيقظًا أثناء عمليات التشغيل"
  },
  "project": {
    "tr": "proje",
    "es": "proyecto",
    "fr": "projet",
    "de": "Projekt",
    "pt": "projeto",
    "ru": "проект",
    "zh": "项目",
    "ja": "プロジェクト",
    "ar": "مشروع"
  },
  "Untitled": {
    "tr": "Adsız",
    "es": "Sin título",
    "fr": "Sans titre",
    "de": "Ohne Titel",
    "pt": "Sem título",
    "ru": "Без названия",
    "zh": "未命名",
    "ja": "無題",
    "ar": "بلا عنوان"
  },
  "Open Project": {
    "tr": "Proje Aç",
    "es": "Abrir proyecto",
    "fr": "Ouvrir un projet",
    "de": "Projekt öffnen",
    "pt": "Abrir projeto",
    "ru": "Открыть проект",
    "zh": "打开项目",
    "ja": "プロジェクトを開く",
    "ar": "فتح مشروع"
  },
  "Projects": {
    "tr": "Projeler",
    "es": "Proyectos",
    "fr": "Projets",
    "de": "Projekte",
    "pt": "Projetos",
    "ru": "Проекты",
    "zh": "项目",
    "ja": "プロジェクト",
    "ar": "المشاريع"
  },
  "No projects yet": {
    "tr": "Henüz proje yok",
    "es": "Aún no hay proyectos",
    "fr": "Aucun projet",
    "de": "Noch keine Projekte",
    "pt": "Nenhum projeto ainda",
    "ru": "Проектов пока нет",
    "zh": "暂无项目",
    "ja": "プロジェクトはまだありません",
    "ar": "لا توجد مشاريع بعد"
  },
  "linked": {
    "tr": "bagli",
    "es": "vinculado",
    "fr": "lié",
    "de": "verknüpft",
    "pt": "vinculado",
    "ru": "связано",
    "zh": "已关联",
    "ja": "リンク済み",
    "ar": "مرتبط"
  },
  "New session in this project": {
    "tr": "Bu projede yeni oturum",
    "es": "Nueva sesión en este proyecto",
    "fr": "Nouvelle session dans ce projet",
    "de": "Neue Sitzung in diesem Projekt",
    "pt": "Nova sessão neste projeto",
    "ru": "Новая сессия в этом проекте",
    "zh": "在此项目中新建会话",
    "ja": "このプロジェクトで新規セッション",
    "ar": "جلسة جديدة في هذا المشروع"
  },
  "No sessions": {
    "tr": "Oturum yok",
    "es": "Sin sesiones",
    "fr": "Aucune session",
    "de": "Keine Sitzungen",
    "pt": "Sem sessões",
    "ru": "Сессий нет",
    "zh": "无会话",
    "ja": "セッションなし",
    "ar": "لا توجد جلسات"
  },
  "New session": {
    "tr": "Yeni oturum",
    "es": "Nueva sesión",
    "fr": "Nouvelle session",
    "de": "Neue Sitzung",
    "pt": "Nova sessão",
    "ru": "Новая сессия",
    "zh": "新建会话",
    "ja": "新規セッション",
    "ar": "جلسة جديدة"
  },
  "Drag to resize": {
    "tr": "Sürükle: bölümleri boyutlandır",
    "es": "Arrastra para redimensionar",
    "fr": "Glisser pour redimensionner",
    "de": "Ziehen zum Anpassen der Größe",
    "pt": "Arraste para redimensionar",
    "ru": "Потяните, чтобы изменить размер",
    "zh": "拖动以调整大小",
    "ja": "ドラッグしてサイズ変更",
    "ar": "اسحب لتغيير الحجم"
  },
  "Command palette": {
    "tr": "Komut paleti",
    "es": "Paleta de comandos",
    "fr": "Palette de commandes",
    "de": "Befehlspalette",
    "pt": "Paleta de comandos",
    "ru": "Палитра команд",
    "zh": "命令面板",
    "ja": "コマンドパレット",
    "ar": "لوحة الأوامر"
  },
  "Measured on this device (Mini-benchmark)": {
    "tr": "Bu cihazda ölçüldü (Mini-test)",
    "es": "Medido en este dispositivo (mini-benchmark)",
    "fr": "Mesuré sur cet appareil (Mini-benchmark)",
    "de": "Auf diesem Gerät gemessen (Mini-Benchmark)",
    "pt": "Medido neste dispositivo (Mini-benchmark)",
    "ru": "Измерено на этом устройстве (мини-тест)",
    "zh": "已在本设备上测量（迷你基准测试）",
    "ja": "このデバイスで計測（ミニベンチマーク）",
    "ar": "قِيس على هذا الجهاز (اختبار مصغّر)"
  },
  "Text": {
    "tr": "Metin",
    "es": "Texto",
    "fr": "Texte",
    "de": "Text",
    "pt": "Texto",
    "ru": "Текст",
    "zh": "文本",
    "ja": "テキスト",
    "ar": "نص"
  },
  "Image": {
    "tr": "Görsel",
    "es": "Imagen",
    "fr": "Image",
    "de": "Bild",
    "pt": "Imagem",
    "ru": "Изображение",
    "zh": "图像",
    "ja": "画像",
    "ar": "صورة"
  },
  "Local image generation (offline)": {
    "tr": "Yerel görsel üretimi (çevrimdışı)",
    "es": "Generación local de imágenes (sin conexión)",
    "fr": "Génération d'images locale (hors ligne)",
    "de": "Lokale Bilderzeugung (offline)",
    "pt": "Geração local de imagens (offline)",
    "ru": "Локальная генерация изображений (офлайн)",
    "zh": "本地图像生成（离线）",
    "ja": "ローカル画像生成（オフライン）",
    "ar": "توليد الصور محليًا (دون اتصال)"
  },
  "Generate images fully on-device with sd-server (stable-diffusion.cpp) — no API, no internet. When on, your chat prompts create images.": {
    "tr": "Görselleri tamamen cihazında sd-server (stable-diffusion.cpp) ile üret — API yok, internet yok. Açıkken sohbet istemlerin görsel üretir.",
    "es": "Genera imágenes totalmente en tu dispositivo con sd-server (stable-diffusion.cpp): sin API, sin internet. Al activarlo, tus mensajes del chat crean imágenes.",
    "fr": "Générez des images entièrement sur l'appareil avec sd-server (stable-diffusion.cpp) — sans API, sans internet. Une fois activé, vos messages du chat créent des images.",
    "de": "Erzeuge Bilder vollständig auf dem Gerät mit sd-server (stable-diffusion.cpp) — ohne API, ohne Internet. Wenn aktiviert, erzeugen deine Chat-Eingaben Bilder.",
    "pt": "Gere imagens totalmente no dispositivo com sd-server (stable-diffusion.cpp) — sem API, sem internet. Quando ativado, seus prompts do chat criam imagens.",
    "ru": "Создавайте изображения полностью на устройстве с sd-server (stable-diffusion.cpp) — без API и интернета. Когда включено, ваши запросы в чате создают изображения.",
    "zh": "使用 sd-server（stable-diffusion.cpp）完全在设备上生成图像——无需 API、无需联网。开启后，聊天提示词即可生成图像。",
    "ja": "sd-server（stable-diffusion.cpp）で完全にデバイス上で画像を生成 — APIもインターネットも不要。オンにすると、チャットのプロンプトが画像を生成します。",
    "ar": "أنشئ الصور بالكامل على جهازك عبر sd-server (stable-diffusion.cpp) — دون API ودون إنترنت. عند التفعيل، تُنشئ رسائل الدردشة صورًا."
  },
  "Download a model for your device": {
    "tr": "Cihazına uygun bir model indir",
    "es": "Descarga un modelo para tu dispositivo",
    "fr": "Téléchargez un modèle pour votre appareil",
    "de": "Lade ein Modell für dein Gerät",
    "pt": "Baixe um modelo para o seu dispositivo",
    "ru": "Скачайте модель для вашего устройства",
    "zh": "为你的设备下载模型",
    "ja": "デバイスに合ったモデルをダウンロード",
    "ar": "نزّل نموذجًا مناسبًا لجهازك"
  },
  "Detected GPU memory": {
    "tr": "Algılanan GPU belleği",
    "es": "Memoria GPU detectada",
    "fr": "Mémoire GPU détectée",
    "de": "Erkannter GPU-Speicher",
    "pt": "Memória de GPU detectada",
    "ru": "Обнаруженная память GPU",
    "zh": "检测到的显存",
    "ja": "検出されたGPUメモリ",
    "ar": "ذاكرة GPU المكتشفة"
  },
  "🟢 fits comfortably · 🔵 works but slower (CPU/offload)": {
    "tr": "🟢 rahat sığar · 🔵 çalışır ama yavaş (CPU/taşma)",
    "es": "🟢 cabe holgadamente · 🔵 funciona pero más lento (CPU/desborde)",
    "fr": "🟢 tient largement · 🔵 fonctionne mais plus lentement (CPU/délestage)",
    "de": "🟢 passt bequem · 🔵 läuft, aber langsamer (CPU/Auslagerung)",
    "pt": "🟢 cabe com folga · 🔵 funciona, mas mais lento (CPU/transbordo)",
    "ru": "🟢 помещается свободно · 🔵 работает, но медленнее (CPU/выгрузка)",
    "zh": "🟢 轻松容纳 · 🔵 可运行但较慢（CPU/溢出）",
    "ja": "🟢 余裕で収まる · 🔵 動くが遅い（CPU/オフロード）",
    "ar": "🟢 يتسع بسهولة · 🔵 يعمل لكن أبطأ (CPU/تفريغ)"
  },
  "One-click download. 🟢 fits · 🔵 works but slower. You can also drop your own SD/SDXL/Flux GGUF into the models folder.": {
    "tr": "Tek tıkla indir. 🟢 sığar · 🔵 çalışır ama yavaş. Kendi SD/SDXL/Flux GGUF'unu da models klasörüne atabilirsin.",
    "es": "Descarga con un clic. 🟢 cabe · 🔵 funciona pero más lento. También puedes soltar tu propio GGUF de SD/SDXL/Flux en la carpeta models.",
    "fr": "Téléchargement en un clic. 🟢 tient · 🔵 fonctionne mais plus lentement. Vous pouvez aussi déposer votre propre GGUF SD/SDXL/Flux dans le dossier models.",
    "de": "Download mit einem Klick. 🟢 passt · 🔵 läuft, aber langsamer. Du kannst auch dein eigenes SD/SDXL/Flux-GGUF in den models-Ordner legen.",
    "pt": "Download com um clique. 🟢 cabe · 🔵 funciona, mas mais lento. Você também pode colocar seu próprio GGUF SD/SDXL/Flux na pasta models.",
    "ru": "Загрузка в один клик. 🟢 помещается · 🔵 работает, но медленнее. Можно также положить свой GGUF SD/SDXL/Flux в папку models.",
    "zh": "一键下载。🟢 容纳 · 🔵 可运行但较慢。你也可以把自己的 SD/SDXL/Flux GGUF 放入 models 文件夹。",
    "ja": "ワンクリックでダウンロード。🟢 収まる · 🔵 動くが遅い。自分の SD/SDXL/Flux GGUF を models フォルダに入れることもできます。",
    "ar": "تنزيل بنقرة واحدة. 🟢 يتسع · 🔵 يعمل لكن أبطأ. يمكنك أيضًا وضع ملف GGUF الخاص بك (SD/SDXL/Flux) في مجلد models."
  },
  "🟢 fits": {
    "tr": "🟢 sığar",
    "es": "🟢 cabe",
    "fr": "🟢 tient",
    "de": "🟢 passt",
    "pt": "🟢 cabe",
    "ru": "🟢 помещается",
    "zh": "🟢 容纳",
    "ja": "🟢 収まる",
    "ar": "🟢 يتسع"
  },
  "🔵 spills": {
    "tr": "🔵 taşar",
    "es": "🔵 desborda",
    "fr": "🔵 déborde",
    "de": "🔵 lagert aus",
    "pt": "🔵 transborda",
    "ru": "🔵 не помещается",
    "zh": "🔵 溢出",
    "ja": "🔵 あふれる",
    "ar": "🔵 يفيض"
  },
  "Installed": {
    "tr": "Yüklü",
    "es": "Instalado",
    "fr": "Installé",
    "de": "Installiert",
    "pt": "Instalado",
    "ru": "Установлено",
    "zh": "已安装",
    "ja": "インストール済み",
    "ar": "مثبّت"
  },
  "Download": {
    "tr": "İndir",
    "es": "Descargar",
    "fr": "Télécharger",
    "de": "Herunterladen",
    "pt": "Baixar",
    "ru": "Скачать",
    "zh": "下载",
    "ja": "ダウンロード",
    "ar": "تنزيل"
  },
  "Installed image models": {
    "tr": "Yüklü görsel modelleri",
    "es": "Modelos de imagen instalados",
    "fr": "Modèles d'image installés",
    "de": "Installierte Bildmodelle",
    "pt": "Modelos de imagem instalados",
    "ru": "Установленные модели изображений",
    "zh": "已安装的图像模型",
    "ja": "インストール済み画像モデル",
    "ar": "نماذج الصور المثبتة"
  },
  "Search any model (HuggingFace)": {
    "tr": "Herhangi bir modeli ara (HuggingFace)",
    "es": "Busca cualquier modelo (HuggingFace)",
    "fr": "Recherchez n'importe quel modèle (HuggingFace)",
    "de": "Beliebiges Modell suchen (HuggingFace)",
    "pt": "Pesquise qualquer modelo (HuggingFace)",
    "ru": "Ищите любую модель (HuggingFace)",
    "zh": "搜索任何模型（HuggingFace）",
    "ja": "任意のモデルを検索（HuggingFace）",
    "ar": "ابحث عن أي نموذج (HuggingFace)"
  },
  "Find ANY on-device image model in the world — search HuggingFace like you search for GGUF. Single-file .gguf / .safetensors download straight into your models folder.": {
    "tr": "Dünyadaki HERHANGİ bir cihaz-içi görsel modelini bul — GGUF arar gibi HuggingFace'te ara. Tek dosyalık .gguf / .safetensors doğrudan models klasörüne iner.",
    "es": "Encuentra CUALQUIER modelo de imagen local del mundo: busca en HuggingFace como buscas GGUF. Los .gguf / .safetensors de un solo archivo se descargan directo a tu carpeta models.",
    "fr": "Trouvez N'IMPORTE QUEL modèle d'image local au monde — cherchez sur HuggingFace comme pour un GGUF. Les .gguf / .safetensors à fichier unique se téléchargent directement dans votre dossier models.",
    "de": "Finde JEDES On-Device-Bildmodell der Welt — durchsuche HuggingFace wie bei GGUF. Einzeldatei-.gguf/.safetensors landen direkt in deinem models-Ordner.",
    "pt": "Encontre QUALQUER modelo de imagem local do mundo — pesquise no HuggingFace como você pesquisa GGUF. Arquivos únicos .gguf / .safetensors baixam direto para a pasta models.",
    "ru": "Найдите ЛЮБУЮ локальную модель изображений — ищите на HuggingFace, как ищете GGUF. Однофайловые .gguf / .safetensors скачиваются прямо в папку models.",
    "zh": "找到世界上任何本地图像模型——像搜索 GGUF 一样搜索 HuggingFace。单文件 .gguf / .safetensors 直接下载到你的 models 文件夹。",
    "ja": "世界中のあらゆるオンデバイス画像モデルを探せます — GGUF と同じように HuggingFace を検索。単一ファイルの .gguf / .safetensors が models フォルダに直接ダウンロードされます。",
    "ar": "اعثر على أي نموذج صور محلي في العالم — ابحث في HuggingFace كما تبحث عن GGUF. تُنزَّل ملفات .gguf / .safetensors المفردة مباشرة إلى مجلد models."
  },
  "e.g. dreamshaper, sdxl, realistic vision, sd-turbo…": {
    "tr": "örn. dreamshaper, sdxl, realistic vision, sd-turbo…",
    "es": "p. ej. dreamshaper, sdxl, realistic vision, sd-turbo…",
    "fr": "p. ex. dreamshaper, sdxl, realistic vision, sd-turbo…",
    "de": "z. B. dreamshaper, sdxl, realistic vision, sd-turbo…",
    "pt": "ex.: dreamshaper, sdxl, realistic vision, sd-turbo…",
    "ru": "напр. dreamshaper, sdxl, realistic vision, sd-turbo…",
    "zh": "例如 dreamshaper、sdxl、realistic vision、sd-turbo…",
    "ja": "例：dreamshaper、sdxl、realistic vision、sd-turbo…",
    "ar": "مثل dreamshaper وsdxl وrealistic vision وsd-turbo…"
  },
  "Searching…": {
    "tr": "Aranıyor…",
    "es": "Buscando…",
    "fr": "Recherche…",
    "de": "Suche…",
    "pt": "Pesquisando…",
    "ru": "Поиск…",
    "zh": "搜索中…",
    "ja": "検索中…",
    "ar": "جارٍ البحث…"
  },
  "Search": {
    "tr": "Ara",
    "es": "Buscar",
    "fr": "Rechercher",
    "de": "Suchen",
    "pt": "Pesquisar",
    "ru": "Поиск",
    "zh": "搜索",
    "ja": "検索",
    "ar": "بحث"
  },
  "No downloadable single-file models found. Try another term.": {
    "tr": "İndirilebilir tek dosyalık model bulunamadı. Başka bir terim dene.",
    "es": "No se encontraron modelos de un solo archivo descargables. Prueba otro término.",
    "fr": "Aucun modèle à fichier unique téléchargeable trouvé. Essayez un autre terme.",
    "de": "Keine herunterladbaren Einzeldatei-Modelle gefunden. Versuche einen anderen Begriff.",
    "pt": "Nenhum modelo de arquivo único para download encontrado. Tente outro termo.",
    "ru": "Не найдено однофайловых моделей для скачивания. Попробуйте другой запрос.",
    "zh": "未找到可下载的单文件模型。请尝试其他关键词。",
    "ja": "ダウンロード可能な単一ファイルモデルが見つかりません。別のキーワードをお試しください。",
    "ar": "لم يُعثر على نماذج أحادية الملف قابلة للتنزيل. جرّب مصطلحًا آخر."
  },
  "Starting…": {
    "tr": "Başlatılıyor…",
    "es": "Iniciando…",
    "fr": "Démarrage…",
    "de": "Starte…",
    "pt": "Iniciando…",
    "ru": "Запуск…",
    "zh": "启动中…",
    "ja": "開始中…",
    "ar": "جارٍ البدء…"
  },
  "Download failed": {
    "tr": "İndirme başarısız",
    "es": "Error de descarga",
    "fr": "Échec du téléchargement",
    "de": "Download fehlgeschlagen",
    "pt": "Falha no download",
    "ru": "Ошибка загрузки",
    "zh": "下载失败",
    "ja": "ダウンロード失敗",
    "ar": "فشل التنزيل"
  },
  "Fast and light — runs on any device (CPU included). Recommended starting point.": {
    "tr": "Hızlı ve hafif — her cihazda (CPU dahil) çalışır. Başlangıç için önerilen.",
    "es": "Rápido y ligero: funciona en cualquier dispositivo (incluida la CPU). Punto de partida recomendado.",
    "fr": "Rapide et léger — fonctionne sur tout appareil (CPU compris). Point de départ recommandé.",
    "de": "Schnell und leicht — läuft auf jedem Gerät (auch CPU). Empfohlener Einstieg.",
    "pt": "Rápido e leve — roda em qualquer dispositivo (inclusive CPU). Ponto de partida recomendado.",
    "ru": "Быстрая и лёгкая — работает на любом устройстве (включая CPU). Рекомендуется для начала.",
    "zh": "快速轻量——任何设备（含 CPU）都能运行。推荐入门。",
    "ja": "高速・軽量 — どのデバイス（CPU含む）でも動作。最初におすすめ。",
    "ar": "سريع وخفيف — يعمل على أي جهاز (حتى CPU). نقطة البداية الموصى بها."
  },
  "Higher quality, a bit more VRAM. Good for 4GB+ GPUs.": {
    "tr": "Daha yüksek kalite, biraz daha fazla VRAM. 4GB+ kartlar için iyi.",
    "es": "Mayor calidad, algo más de VRAM. Ideal para GPUs de 4GB+.",
    "fr": "Meilleure qualité, un peu plus de VRAM. Bien pour les GPU 4 Go et plus.",
    "de": "Höhere Qualität, etwas mehr VRAM. Gut für GPUs ab 4 GB.",
    "pt": "Qualidade maior, um pouco mais de VRAM. Bom para GPUs de 4GB+.",
    "ru": "Выше качество, чуть больше VRAM. Подходит для GPU от 4 ГБ.",
    "zh": "质量更高，显存占用稍多。适合 4GB+ 显卡。",
    "ja": "より高品質、VRAMは少し多め。4GB以上のGPU向け。",
    "ar": "جودة أعلى مع ذاكرة أكبر قليلًا. مناسب لبطاقات 4GB فأكثر."
  },
  "Uncompressed SD1.5 — best SD1.5 quality. 6GB+ GPU recommended.": {
    "tr": "Sıkıştırmasız SD1.5 — en iyi SD1.5 kalitesi. 6GB+ kart önerilir.",
    "es": "SD1.5 sin comprimir: la mejor calidad SD1.5. Se recomienda GPU de 6GB+.",
    "fr": "SD1.5 non compressé — la meilleure qualité SD1.5. GPU 6 Go+ recommandé.",
    "de": "Unkomprimiertes SD1.5 — beste SD1.5-Qualität. GPU ab 6 GB empfohlen.",
    "pt": "SD1.5 sem compressão — a melhor qualidade SD1.5. GPU de 6GB+ recomendada.",
    "ru": "Несжатая SD1.5 — лучшее качество SD1.5. Рекомендуется GPU от 6 ГБ.",
    "zh": "未压缩的 SD1.5——最佳 SD1.5 质量。建议 6GB+ 显卡。",
    "ja": "非圧縮のSD1.5 — 最高のSD1.5品質。6GB以上のGPU推奨。",
    "ar": "‏SD1.5 غير مضغوط — أفضل جودة SD1.5. يُنصح ببطاقة 6GB فأكثر."
  },
  "OpenRAIL-M (commercial OK)": {
    "tr": "OpenRAIL-M (ticari OK)",
    "es": "OpenRAIL-M (uso comercial OK)",
    "fr": "OpenRAIL-M (commercial OK)",
    "de": "OpenRAIL-M (kommerziell OK)",
    "pt": "OpenRAIL-M (comercial OK)",
    "ru": "OpenRAIL-M (коммерческое использование разрешено)",
    "zh": "OpenRAIL-M（可商用）",
    "ja": "OpenRAIL-M（商用可）",
    "ar": "OpenRAIL-M (تجاري مسموح)"
  },
  "Stable Diffusion 1.5 · Q8 (higher quality)": {
    "tr": "Stable Diffusion 1.5 · Q8 (daha kaliteli)",
    "es": "Stable Diffusion 1.5 · Q8 (más calidad)",
    "fr": "Stable Diffusion 1.5 · Q8 (qualité supérieure)",
    "de": "Stable Diffusion 1.5 · Q8 (höhere Qualität)",
    "pt": "Stable Diffusion 1.5 · Q8 (mais qualidade)",
    "ru": "Stable Diffusion 1.5 · Q8 (выше качество)",
    "zh": "Stable Diffusion 1.5 · Q8（更高质量）",
    "ja": "Stable Diffusion 1.5 · Q8（高品質）",
    "ar": "Stable Diffusion 1.5 · Q8 (جودة أعلى)"
  },
  "Stable Diffusion 1.5 · F16 (full quality)": {
    "tr": "Stable Diffusion 1.5 · F16 (tam kalite)",
    "es": "Stable Diffusion 1.5 · F16 (calidad completa)",
    "fr": "Stable Diffusion 1.5 · F16 (pleine qualité)",
    "de": "Stable Diffusion 1.5 · F16 (volle Qualität)",
    "pt": "Stable Diffusion 1.5 · F16 (qualidade total)",
    "ru": "Stable Diffusion 1.5 · F16 (полное качество)",
    "zh": "Stable Diffusion 1.5 · F16（完整质量）",
    "ja": "Stable Diffusion 1.5 · F16（フル品質）",
    "ar": "Stable Diffusion 1.5 · F16 (جودة كاملة)"
  },
  "Device-picked by default — but you can choose any VL model in Settings → Models, and search / download an offline image-generation model from the model picker on the chat screen.": {
    "tr": "Varsayılan cihaza göre seçilir — ama Ayarlar → Modeller'den istediğin VL modelini seçebilir, sohbet ekranındaki model seçicisinden çevrimdışı görsel-üretim modeli arayıp indirebilirsin.",
    "es": "Elegido según el dispositivo por defecto, pero puedes elegir cualquier modelo VL en Ajustes → Modelos y buscar/descargar un modelo de generación de imágenes sin conexión desde el selector de modelos del chat.",
    "fr": "Choisi selon l'appareil par défaut — mais vous pouvez choisir n'importe quel modèle VL dans Paramètres → Modèles, et chercher/télécharger un modèle de génération d'images hors ligne depuis le sélecteur de modèles du chat.",
    "de": "Standardmäßig geräteabhängig gewählt — aber du kannst in Einstellungen → Modelle jedes VL-Modell wählen und im Modell-Picker des Chats ein Offline-Bildmodell suchen/herunterladen.",
    "pt": "Escolhido pelo dispositivo por padrão — mas você pode escolher qualquer modelo VL em Configurações → Modelos e pesquisar/baixar um modelo de geração de imagens offline no seletor de modelos do chat.",
    "ru": "По умолчанию выбирается под устройство — но вы можете выбрать любую VL-модель в Настройки → Модели и найти/скачать офлайн-модель генерации изображений в селекторе моделей на экране чата.",
    "zh": "默认按设备选择——但你可以在 设置 → 模型 中选择任意 VL 模型，并在聊天界面的模型选择器中搜索/下载离线图像生成模型。",
    "ja": "デフォルトではデバイスに合わせて選択されます — ただし 設定 → モデル で任意のVLモデルを選べ、チャット画面のモデルピッカーからオフライン画像生成モデルを検索/ダウンロードできます。",
    "ar": "يُختار افتراضيًا حسب الجهاز — لكن يمكنك اختيار أي نموذج VL من الإعدادات ← النماذج، والبحث عن نموذج توليد صور دون اتصال وتنزيله من منتقي النماذج في شاشة الدردشة."
  }
}
