/**
 * Walkthrough bileştiricisi (roadmap 7.2) — "doğrulandı" bir İDDİA değil,
 * OKUNABİLİR BELGE olsun: ne değişti, nasıl test edilir, kanıt nerede.
 *
 * Saf modül: girdiler motorun zaten ürettiği veriler (görev kartı, üretim
 * sonrası doğrulama, davranış testi + ekran şeridi), çıktı markdown.
 * Store'a/pencereye dokunmaz — `npm run test:walkthrough` doğrudan koşar.
 */
import type { TaskStep } from '@shared/ipc'
import type { VerificationOutcome } from './verificationResult'

export interface WalkthroughInput {
  /** Kullanıcının görünür isteği (walkthrough başlığının bağlamı). */
  request: string
  /** ISO zaman damgası — çağıran verir (test determinizmi). */
  when: string
  /** Görev kartından: dosya adımları + açıklamaları. */
  files: Array<{ path: string; desc?: string; status: TaskStep['status']; detail?: string }>
  /** Üretim sonrası doğrulama (2.3/postGenVerify) sonucu. */
  verify?: { outcome: VerificationOutcome; detail?: string }
  /** Davranış testi (6.5): satırlar, kusurlar, ekran kareleri. */
  behavior?: { rows: string[]; fails: string[]; shots: string[] }
  /** Repro mührü hükümleri (6.6) — logRepair boğaz noktasından akar (7.7). */
  repro?: string[]
  /** Dil: tr | en (uygulamanın o anki dili). */
  lang?: 'tr' | 'en'
}

function checkbox(status: TaskStep['status']): string {
  return status === 'done' ? '[x]' : status === 'failed' ? '[!]' : '[ ]'
}

export function composeWalkthrough(i: WalkthroughInput): string {
  const tr = i.lang !== 'en'
  const L = tr
    ? {
        title: 'Walkthrough',
        req: 'İstek',
        built: 'Üretilen dosyalar',
        features: 'Özellikler',
        test: 'Nasıl test edilir',
        testBody:
          '1. **Çalıştır** düğmesine bas — proje gerçek vite dev sunucusunda açılır.\n' +
          '2. Menü bağlantılarına tıkla: her bölüm kaydırarak gelmeli.\n' +
          '3. Formu doldurup gönder; konsolda hata olmamalı.\n' +
          '4. Motor 12 sn sonra aynı gezintiyi kendisi de yapar (davranış testi) — raporu sohbete düşer.',
        evidence: 'Doğrulama Kanıtı',
        verifyClean: '✅ Üretim sonrası denetim: sözdizimi + derleme temiz.',
        verifyDirty: '⚠️ Üretim sonrası denetim hata bıraktı:',
        verifyUnverified: 'ℹ️ Üretim sonrası denetim kanıt üretemedi:',
        verifyPending: 'ℹ️ Derleme denetimi bu belgeye henüz işlenmedi.',
        behaviorTitle: 'Davranış testi (motor siteyi gezdi)',
        behaviorNone: 'ℹ️ Davranış testi henüz koşmadı — Çalıştır sonrası otomatik koşar ve bu belge güncellenir.',
        fails: 'Bulunan kusurlar',
        shots: 'Ekran kareleri',
        failedNote: 'üretilemedi',
        genBy: 'NexoraAI motoru tarafından üretildi'
      }
    : {
        title: 'Walkthrough',
        req: 'Request',
        built: 'Files produced',
        features: 'Features',
        test: 'How to test',
        testBody:
          '1. Press **Run** — the project opens on a real vite dev server.\n' +
          '2. Click every nav link: each section should scroll into view.\n' +
          '3. Fill and submit the form; the console must stay clean.\n' +
          '4. The engine repeats the same walk itself 12s after Run (behavior test) — the report lands in chat.',
        evidence: 'Verification Evidence',
        verifyClean: '✅ Post-generation check: syntax + build clean.',
        verifyDirty: '⚠️ Post-generation check left an error:',
        verifyUnverified: 'ℹ️ Post-generation verification did not produce sufficient evidence:',
        verifyPending: 'ℹ️ The build check has not reached this document yet.',
        behaviorTitle: 'Behavior test (the engine used the site)',
        behaviorNone: 'ℹ️ Behavior test not run yet — it runs automatically after Run and updates this document.',
        fails: 'Defects found',
        shots: 'Screenshots',
        failedNote: 'not produced',
        genBy: 'generated by the NexoraAI engine'
      }

  const lines: string[] = []
  lines.push(`# ${L.title} — ${i.request.split('\n')[0].slice(0, 80)}`)
  lines.push('')
  lines.push(`> ${L.req}: ${i.request.trim()}`)
  lines.push('')
  lines.push(`_${i.when} · ${L.genBy}_`)

  lines.push('', `## ${L.built}`, '')
  for (const f of i.files) {
    const note = f.detail ?? (f.status === 'failed' ? L.failedNote : '')
    lines.push(`- ${checkbox(f.status)} \`${f.path}\`${note ? ` — ${note}` : ''}`)
  }

  const features = i.files.filter((f) => f.desc && f.status === 'done')
  if (features.length > 0) {
    lines.push('', `## ${L.features}`, '')
    for (const f of features) {
      // Plan açıklamalarındaki iç etiketler ([şablon: x]) kullanıcı belgesine taşınmaz
      const desc = (f.desc ?? '').replace(/\s*\[şablon:[^\]]*\]/gi, '').trim()
      if (desc) lines.push(`- **${f.path.split('/').pop()}** — ${desc}`)
    }
  }

  lines.push('', `## ${L.test}`, '', L.testBody)

  lines.push('', `## ${L.evidence}`, '')
  if (i.verify) {
    if (i.verify.outcome === 'passed') lines.push(L.verifyClean)
    else if (i.verify.outcome === 'failed') {
      lines.push(L.verifyDirty, '', '```', (i.verify.detail ?? '').split('\n').slice(0, 8).join('\n'), '```')
    } else {
      lines.push(L.verifyUnverified)
      if (i.verify.detail) lines.push('', i.verify.detail)
    }
  } else {
    lines.push(L.verifyPending)
  }

  if (i.repro && i.repro.length > 0) {
    lines.push('', `### ${tr ? 'Repro mührü (onarım kanıtları)' : 'Repro seal (repair evidence)'}`, '')
    for (const r of i.repro) lines.push(`- ${r}`)
  }

  lines.push('', `### ${L.behaviorTitle}`, '')
  if (i.behavior) {
    lines.push(i.behavior.rows.map((r) => `- ${r}`).join('\n'))
    if (i.behavior.fails.length > 0) {
      lines.push('', `**${L.fails}:**`, '')
      lines.push(i.behavior.fails.map((f) => `- ⚠️ ${f}`).join('\n'))
    }
    if (i.behavior.shots.length > 0) {
      lines.push('', `### ${L.shots}`, '')
      for (const s of i.behavior.shots) {
        lines.push(`![${s.split('/').pop()}](${s})`)
      }
    }
  } else {
    lines.push(L.behaviorNone)
  }

  lines.push('')
  return lines.join('\n')
}

/** Görev kartını task.md olarak dök (7.1 kartının kalıcı hali). */
export function composeTaskDoc(
  title: string,
  steps: TaskStep[],
  note: string | undefined,
  when: string
): string {
  const lines = [`# ${title}`, '', `_${when}${note ? ` · ${note}` : ''}_`, '']
  for (const s of steps) {
    lines.push(`- ${checkbox(s.status)} \`${s.label}\`${s.detail ? ` — ${s.detail}` : ''}`)
  }
  lines.push('')
  return lines.join('\n')
}

/** Onaylanan planı implementation_plan.md olarak dök. */
export function composePlanDoc(request: string, planText: string, when: string, tr: boolean): string {
  return [
    `# ${tr ? 'Uygulama Planı' : 'Implementation Plan'}`,
    '',
    `> ${tr ? 'İstek' : 'Request'}: ${request.trim()}`,
    '',
    `_${when}_`,
    '',
    `## ${tr ? 'Dosya planı' : 'File plan'}`,
    '',
    planText.trim(),
    ''
  ].join('\n')
}
