/**
 * 10.9 — Sağlayıcı kataloğu (models.dev TAM listesinden üretilmiş, ÇEVRİMDIŞI gömülü).
 * ÜRETİLDİ: node scripts/gen-providers.mjs — ELLE DÜZENLEME (models.dev/api.json otoritedir).
 * Adapter: @ai-sdk/anthropic → native /v1/messages; geri kalanı OpenAI-uyumlu (/chat/completions).
 * base URL boş veya ${VAR} şablonlu olanlar kaynak-özel → kullanıcı doldurur. YEREL varsayılan, opt-in.
 */
export type ProviderAdapter = 'openai' | 'anthropic'

export interface ProviderInfo {
  id: string
  name: string
  baseUrl: string
  adapter: ProviderAdapter
  keyEnv?: string
  local?: boolean
  gateway?: boolean
  docs?: string
}

export const PROVIDERS: ProviderInfo[] = [
  { id: "openai", name: "OpenAI", baseUrl: "https://api.openai.com/v1", adapter: "openai", keyEnv: "OPENAI_API_KEY" },
  { id: "anthropic", name: "Anthropic", baseUrl: "https://api.anthropic.com/v1", adapter: "anthropic", keyEnv: "ANTHROPIC_API_KEY" },
  { id: "google", name: "Google", baseUrl: "https://generativelanguage.googleapis.com/v1beta/openai", adapter: "openai", keyEnv: "GOOGLE_API_KEY" },
  { id: "xai", name: "xAI", baseUrl: "https://api.x.ai/v1", adapter: "openai", keyEnv: "XAI_API_KEY" },
  { id: "mistral", name: "Mistral", baseUrl: "https://api.mistral.ai/v1", adapter: "openai", keyEnv: "MISTRAL_API_KEY" },
  { id: "deepseek", name: "DeepSeek", baseUrl: "https://api.deepseek.com", adapter: "openai", keyEnv: "DEEPSEEK_API_KEY" },
  { id: "groq", name: "Groq", baseUrl: "https://api.groq.com/openai/v1", adapter: "openai", keyEnv: "GROQ_API_KEY" },
  { id: "openrouter", name: "OpenRouter", baseUrl: "https://openrouter.ai/api/v1", adapter: "openai", keyEnv: "OPENROUTER_API_KEY", gateway: true },
  { id: "ollama", name: "Ollama (yerel)", baseUrl: "http://localhost:11434/v1", adapter: "openai", local: true },
  { id: "lmstudio", name: "LMStudio", baseUrl: "http://127.0.0.1:1234/v1", adapter: "openai", keyEnv: "LMSTUDIO_API_KEY", local: true },
  { id: "302ai", name: "302.AI", baseUrl: "https://api.302.ai/v1", adapter: "openai", keyEnv: "302AI_API_KEY", gateway: true },
  { id: "abacus", name: "Abacus", baseUrl: "https://routellm.abacus.ai/v1", adapter: "openai", keyEnv: "ABACUS_API_KEY" },
  { id: "abliteration-ai", name: "abliteration.ai", baseUrl: "https://api.abliteration.ai/v1", adapter: "openai", keyEnv: "ABLIT_KEY" },
  { id: "aihubmix", name: "AIHubMix", baseUrl: "", adapter: "openai", keyEnv: "AIHUBMIX_API_KEY", gateway: true },
  { id: "alibaba", name: "Alibaba", baseUrl: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1", adapter: "openai", keyEnv: "DASHSCOPE_API_KEY" },
  { id: "alibaba-cn", name: "Alibaba (China)", baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1", adapter: "openai", keyEnv: "DASHSCOPE_API_KEY" },
  { id: "alibaba-coding-plan", name: "Alibaba Coding Plan", baseUrl: "https://coding-intl.dashscope.aliyuncs.com/v1", adapter: "openai", keyEnv: "ALIBABA_CODING_PLAN_API_KEY" },
  { id: "alibaba-coding-plan-cn", name: "Alibaba Coding Plan (China)", baseUrl: "https://coding.dashscope.aliyuncs.com/v1", adapter: "openai", keyEnv: "ALIBABA_CODING_PLAN_API_KEY" },
  { id: "alibaba-token-plan", name: "Alibaba Token Plan", baseUrl: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1", adapter: "openai", keyEnv: "ALIBABA_TOKEN_PLAN_API_KEY" },
  { id: "alibaba-token-plan-cn", name: "Alibaba Token Plan (China)", baseUrl: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1", adapter: "openai", keyEnv: "ALIBABA_TOKEN_PLAN_API_KEY" },
  { id: "amazon-bedrock", name: "Amazon Bedrock", baseUrl: "", adapter: "openai", keyEnv: "AWS_ACCESS_KEY_ID" },
  { id: "ambient", name: "Ambient", baseUrl: "https://api.ambient.xyz/v1", adapter: "openai", keyEnv: "AMBIENT_API_KEY" },
  { id: "anyapi", name: "AnyAPI", baseUrl: "https://api.anyapi.ai/v1", adapter: "openai", keyEnv: "ANYAPI_API_KEY", gateway: true },
  { id: "atomic-chat", name: "Atomic Chat", baseUrl: "http://127.0.0.1:1337/v1", adapter: "openai", keyEnv: "ATOMIC_CHAT_API_KEY" },
  { id: "auriko", name: "Auriko", baseUrl: "https://api.auriko.ai/v1", adapter: "openai", keyEnv: "AURIKO_API_KEY" },
  { id: "azure", name: "Azure", baseUrl: "", adapter: "openai", keyEnv: "AZURE_RESOURCE_NAME" },
  { id: "azure-cognitive-services", name: "Azure Cognitive Services", baseUrl: "", adapter: "openai", keyEnv: "AZURE_COGNITIVE_SERVICES_RESOURCE_NAME" },
  { id: "bailing", name: "Bailing", baseUrl: "https://api.tbox.cn/api/llm/v1/chat/completions", adapter: "openai", keyEnv: "BAILING_API_TOKEN" },
  { id: "baseten", name: "Baseten", baseUrl: "https://inference.baseten.co/v1", adapter: "openai", keyEnv: "BASETEN_API_KEY" },
  { id: "berget", name: "Berget.AI", baseUrl: "https://api.berget.ai/v1", adapter: "openai", keyEnv: "BERGET_API_KEY" },
  { id: "cerebras", name: "Cerebras", baseUrl: "https://api.cerebras.ai/v1", adapter: "openai", keyEnv: "CEREBRAS_API_KEY" },
  { id: "chutes", name: "Chutes", baseUrl: "https://llm.chutes.ai/v1", adapter: "openai", keyEnv: "CHUTES_API_KEY" },
  { id: "clarifai", name: "Clarifai", baseUrl: "https://api.clarifai.com/v2/ext/openai/v1", adapter: "openai", keyEnv: "CLARIFAI_PAT" },
  { id: "claudinio", name: "Claudinio", baseUrl: "https://api.claudin.io/v1", adapter: "openai", keyEnv: "CLAUDINIO_API_KEY" },
  { id: "cloudferro-sherlock", name: "CloudFerro Sherlock", baseUrl: "https://api-sherlock.cloudferro.com/openai/v1/", adapter: "openai", keyEnv: "CLOUDFERRO_SHERLOCK_API_KEY" },
  { id: "cloudflare-ai-gateway", name: "Cloudflare AI Gateway", baseUrl: "", adapter: "openai", keyEnv: "CLOUDFLARE_API_TOKEN", gateway: true },
  { id: "cloudflare-workers-ai", name: "Cloudflare Workers AI", baseUrl: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1", adapter: "openai", keyEnv: "CLOUDFLARE_ACCOUNT_ID" },
  { id: "cohere", name: "Cohere", baseUrl: "https://api.cohere.ai/compatibility/v1", adapter: "openai", keyEnv: "COHERE_API_KEY" },
  { id: "cortecs", name: "Cortecs", baseUrl: "https://api.cortecs.ai/v1", adapter: "openai", keyEnv: "CORTECS_API_KEY" },
  { id: "crof", name: "CrofAI", baseUrl: "https://crof.ai/v1", adapter: "openai", keyEnv: "CROF_API_KEY", gateway: true },
  { id: "drun", name: "D.Run (China)", baseUrl: "https://chat.d.run/v1", adapter: "openai", keyEnv: "DRUN_API_KEY" },
  { id: "databricks", name: "Databricks", baseUrl: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1", adapter: "openai", keyEnv: "DATABRICKS_HOST" },
  { id: "deepinfra", name: "Deep Infra", baseUrl: "https://api.deepinfra.com/v1/openai", adapter: "openai", keyEnv: "DEEPINFRA_API_KEY" },
  { id: "dinference", name: "DInference", baseUrl: "https://api.dinference.com/v1", adapter: "openai", keyEnv: "DINFERENCE_API_KEY" },
  { id: "digitalocean", name: "DigitalOcean", baseUrl: "https://inference.do-ai.run/v1", adapter: "openai", keyEnv: "DIGITALOCEAN_ACCESS_TOKEN" },
  { id: "evroc", name: "evroc", baseUrl: "https://models.think.evroc.com/v1", adapter: "openai", keyEnv: "EVROC_API_KEY" },
  { id: "fastrouter", name: "FastRouter", baseUrl: "https://go.fastrouter.ai/api/v1", adapter: "openai", keyEnv: "FASTROUTER_API_KEY", gateway: true },
  { id: "fireworks-ai", name: "Fireworks AI", baseUrl: "https://api.fireworks.ai/inference/v1/", adapter: "openai", keyEnv: "FIREWORKS_API_KEY" },
  { id: "freemodel", name: "FreeModel", baseUrl: "https://cc.freemodel.dev/v1", adapter: "anthropic", keyEnv: "FREEMODEL_API_KEY" },
  { id: "friendli", name: "Friendli", baseUrl: "https://api.friendli.ai/serverless/v1", adapter: "openai", keyEnv: "FRIENDLI_TOKEN" },
  { id: "frogbot", name: "FrogBot", baseUrl: "https://app.frogbot.ai/api/v1", adapter: "openai", keyEnv: "FROGBOT_API_KEY" },
  { id: "github-copilot", name: "GitHub Copilot", baseUrl: "https://api.githubcopilot.com", adapter: "openai", keyEnv: "GITHUB_TOKEN", gateway: true },
  { id: "github-models", name: "GitHub Models", baseUrl: "https://models.github.ai/inference", adapter: "openai", keyEnv: "GITHUB_TOKEN", gateway: true },
  { id: "gitlab", name: "GitLab Duo", baseUrl: "", adapter: "openai", keyEnv: "GITLAB_TOKEN" },
  { id: "gmicloud", name: "GMI Cloud", baseUrl: "https://api.gmi-serving.com/v1", adapter: "openai", keyEnv: "GMICLOUD_API_KEY" },
  { id: "helicone", name: "Helicone", baseUrl: "https://ai-gateway.helicone.ai/v1", adapter: "openai", keyEnv: "HELICONE_API_KEY", gateway: true },
  { id: "hpc-ai", name: "HPC-AI", baseUrl: "https://api.hpc-ai.com/inference/v1", adapter: "openai", keyEnv: "HPC_AI_API_KEY" },
  { id: "huggingface", name: "Hugging Face", baseUrl: "https://router.huggingface.co/v1", adapter: "openai", keyEnv: "HF_TOKEN", gateway: true },
  { id: "inception", name: "Inception", baseUrl: "https://api.inceptionlabs.ai/v1/", adapter: "openai", keyEnv: "INCEPTION_API_KEY" },
  { id: "inceptron", name: "Inceptron", baseUrl: "https://api.inceptron.io/v1", adapter: "openai", keyEnv: "INCEPTRON_API_KEY" },
  { id: "inference", name: "Inference", baseUrl: "https://inference.net/v1", adapter: "openai", keyEnv: "INFERENCE_API_KEY" },
  { id: "io-net", name: "IO.NET", baseUrl: "https://api.intelligence.io.solutions/api/v1", adapter: "openai", keyEnv: "IOINTELLIGENCE_API_KEY" },
  { id: "iflowcn", name: "iFlow", baseUrl: "https://apis.iflow.cn/v1", adapter: "openai", keyEnv: "IFLOW_API_KEY" },
  { id: "jan", name: "Jan (yerel)", baseUrl: "http://localhost:1337/v1", adapter: "openai", local: true },
  { id: "jiekou", name: "Jiekou.AI", baseUrl: "https://api.jiekou.ai/openai", adapter: "openai", keyEnv: "JIEKOU_API_KEY" },
  { id: "kenari", name: "Kenari", baseUrl: "https://kenari.id/v1", adapter: "openai", keyEnv: "KENARI_API_KEY" },
  { id: "kilo", name: "Kilo Gateway", baseUrl: "https://api.kilo.ai/api/gateway", adapter: "openai", keyEnv: "KILO_API_KEY" },
  { id: "kimi-for-coding", name: "Kimi For Coding", baseUrl: "https://api.kimi.com/coding/v1", adapter: "anthropic", keyEnv: "KIMI_API_KEY" },
  { id: "kuae-cloud-coding-plan", name: "KUAE Cloud Coding Plan", baseUrl: "https://coding-plan-endpoint.kuaecloud.net/v1", adapter: "openai", keyEnv: "KUAE_API_KEY" },
  { id: "lilac", name: "Lilac", baseUrl: "https://api.getlilac.com/v1", adapter: "openai", keyEnv: "LILAC_API_KEY" },
  { id: "llama", name: "Llama", baseUrl: "https://api.llama.com/compat/v1/", adapter: "openai", keyEnv: "LLAMA_API_KEY" },
  { id: "llamacpp", name: "llama.cpp server (yerel)", baseUrl: "http://localhost:8080/v1", adapter: "openai", local: true },
  { id: "llmgateway", name: "LLM Gateway", baseUrl: "https://api.llmgateway.io/v1", adapter: "openai", keyEnv: "LLMGATEWAY_API_KEY", gateway: true },
  { id: "llmtr", name: "LLMTR", baseUrl: "https://llmtr.com/v1", adapter: "openai", keyEnv: "LLMTR_API_KEY", gateway: true },
  { id: "longcat", name: "LongCat", baseUrl: "https://api.longcat.chat/openai", adapter: "openai", keyEnv: "LONGCAT_API_KEY" },
  { id: "lucidquery", name: "LucidQuery", baseUrl: "https://api.lucidquery.com/v1", adapter: "openai", keyEnv: "LUCIDQUERY_API_KEY" },
  { id: "meganova", name: "Meganova", baseUrl: "https://api.meganova.ai/v1", adapter: "openai", keyEnv: "MEGANOVA_API_KEY" },
  { id: "merge-gateway", name: "Merge Gateway", baseUrl: "", adapter: "openai", keyEnv: "MERGE_GATEWAY_API_KEY", gateway: true },
  { id: "minimax", name: "MiniMax (minimax.io)", baseUrl: "https://api.minimax.io/anthropic/v1", adapter: "anthropic", keyEnv: "MINIMAX_API_KEY" },
  { id: "minimax-cn", name: "MiniMax (minimaxi.com)", baseUrl: "https://api.minimaxi.com/anthropic/v1", adapter: "anthropic", keyEnv: "MINIMAX_API_KEY" },
  { id: "minimax-coding-plan", name: "MiniMax Token Plan (minimax.io)", baseUrl: "https://api.minimax.io/anthropic/v1", adapter: "anthropic", keyEnv: "MINIMAX_API_KEY" },
  { id: "minimax-cn-coding-plan", name: "MiniMax Token Plan (minimaxi.com)", baseUrl: "https://api.minimaxi.com/anthropic/v1", adapter: "anthropic", keyEnv: "MINIMAX_API_KEY" },
  { id: "mixlayer", name: "Mixlayer", baseUrl: "https://models.mixlayer.ai/v1", adapter: "openai", keyEnv: "MIXLAYER_API_KEY" },
  { id: "moark", name: "Moark", baseUrl: "https://moark.com/v1", adapter: "openai", keyEnv: "MOARK_API_KEY" },
  { id: "modelscope", name: "ModelScope", baseUrl: "https://api-inference.modelscope.cn/v1", adapter: "openai", keyEnv: "MODELSCOPE_API_KEY" },
  { id: "moonshotai", name: "Moonshot AI", baseUrl: "https://api.moonshot.ai/v1", adapter: "openai", keyEnv: "MOONSHOT_API_KEY" },
  { id: "moonshotai-cn", name: "Moonshot AI (China)", baseUrl: "https://api.moonshot.cn/v1", adapter: "openai", keyEnv: "MOONSHOT_API_KEY" },
  { id: "morph", name: "Morph", baseUrl: "https://api.morphllm.com/v1", adapter: "openai", keyEnv: "MORPH_API_KEY" },
  { id: "nano-gpt", name: "NanoGPT", baseUrl: "https://nano-gpt.com/api/v1", adapter: "openai", keyEnv: "NANO_GPT_API_KEY", gateway: true },
  { id: "nearai", name: "NEAR AI Cloud", baseUrl: "https://cloud-api.near.ai/v1", adapter: "openai", keyEnv: "NEARAI_API_KEY" },
  { id: "nebius", name: "Nebius Token Factory", baseUrl: "https://api.tokenfactory.nebius.com/v1", adapter: "openai", keyEnv: "NEBIUS_API_KEY" },
  { id: "neon", name: "Neon", baseUrl: "${NEON_AI_GATEWAY_BASE_URL}/ai-gateway/mlflow/v1", adapter: "openai", keyEnv: "NEON_AI_GATEWAY_BASE_URL" },
  { id: "neuralwatt", name: "Neuralwatt", baseUrl: "https://api.neuralwatt.com/v1", adapter: "openai", keyEnv: "NEURALWATT_API_KEY" },
  { id: "nova", name: "Nova", baseUrl: "https://api.nova.amazon.com/v1", adapter: "openai", keyEnv: "NOVA_API_KEY" },
  { id: "novita-ai", name: "NovitaAI", baseUrl: "https://api.novita.ai/openai", adapter: "openai", keyEnv: "NOVITA_API_KEY" },
  { id: "nvidia", name: "Nvidia", baseUrl: "https://integrate.api.nvidia.com/v1", adapter: "openai", keyEnv: "NVIDIA_API_KEY" },
  { id: "ollama-cloud", name: "Ollama Cloud", baseUrl: "https://ollama.com/v1", adapter: "openai", keyEnv: "OLLAMA_API_KEY" },
  { id: "opencode-go", name: "OpenCode Go", baseUrl: "https://opencode.ai/zen/go/v1", adapter: "openai", keyEnv: "OPENCODE_API_KEY", gateway: true },
  { id: "opencode", name: "OpenCode Zen", baseUrl: "https://opencode.ai/zen/v1", adapter: "openai", keyEnv: "OPENCODE_API_KEY", gateway: true },
  { id: "orcarouter", name: "OrcaRouter", baseUrl: "https://api.orcarouter.ai/v1", adapter: "openai", keyEnv: "ORCAROUTER_API_KEY", gateway: true },
  { id: "ovhcloud", name: "OVHcloud AI Endpoints", baseUrl: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1", adapter: "openai", keyEnv: "OVHCLOUD_API_KEY" },
  { id: "custom", name: "Özel (OpenAI-uyumlu)", baseUrl: "", adapter: "openai", keyEnv: "API_KEY" },
  { id: "perplexity", name: "Perplexity", baseUrl: "https://api.perplexity.ai", adapter: "openai", keyEnv: "PERPLEXITY_API_KEY" },
  { id: "perplexity-agent", name: "Perplexity Agent", baseUrl: "https://api.perplexity.ai/v1", adapter: "openai", keyEnv: "PERPLEXITY_API_KEY" },
  { id: "poe", name: "Poe", baseUrl: "https://api.poe.com/v1", adapter: "openai", keyEnv: "POE_API_KEY" },
  { id: "poolside", name: "Poolside", baseUrl: "https://inference.poolside.ai/v1", adapter: "openai", keyEnv: "POOLSIDE_API_KEY" },
  { id: "privatemode-ai", name: "Privatemode AI", baseUrl: "http://localhost:8080/v1", adapter: "openai", keyEnv: "PRIVATEMODE_API_KEY" },
  { id: "qihang-ai", name: "QiHang", baseUrl: "https://api.qhaigc.net/v1", adapter: "openai", keyEnv: "QIHANG_API_KEY" },
  { id: "qiniu-ai", name: "Qiniu", baseUrl: "https://api.qnaigc.com/v1", adapter: "openai", keyEnv: "QINIU_API_KEY" },
  { id: "regolo-ai", name: "Regolo AI", baseUrl: "https://api.regolo.ai/v1", adapter: "openai", keyEnv: "REGOLO_API_KEY" },
  { id: "requesty", name: "Requesty", baseUrl: "https://router.requesty.ai/v1", adapter: "openai", keyEnv: "REQUESTY_API_KEY", gateway: true },
  { id: "routing-run", name: "routing.run", baseUrl: "https://ai.routing.sh/v1", adapter: "openai", keyEnv: "ROUTING_RUN_API_KEY", gateway: true },
  { id: "sakana", name: "Sakana AI", baseUrl: "https://api.sakana.ai/v1", adapter: "openai", keyEnv: "SAKANA_API_KEY" },
  { id: "sap-ai-core", name: "SAP AI Core", baseUrl: "", adapter: "openai", keyEnv: "AICORE_SERVICE_KEY" },
  { id: "sarvam", name: "Sarvam AI", baseUrl: "https://api.sarvam.ai/v1", adapter: "openai", keyEnv: "SARVAM_API_KEY" },
  { id: "scaleway", name: "Scaleway", baseUrl: "https://api.scaleway.ai/v1", adapter: "openai", keyEnv: "SCALEWAY_API_KEY" },
  { id: "siliconflow", name: "SiliconFlow", baseUrl: "https://api.siliconflow.com/v1", adapter: "openai", keyEnv: "SILICONFLOW_API_KEY" },
  { id: "siliconflow-cn", name: "SiliconFlow (China)", baseUrl: "https://api.siliconflow.cn/v1", adapter: "openai", keyEnv: "SILICONFLOW_CN_API_KEY" },
  { id: "snowflake-cortex", name: "Snowflake Cortex", baseUrl: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1", adapter: "openai", keyEnv: "SNOWFLAKE_ACCOUNT" },
  { id: "stackit", name: "STACKIT", baseUrl: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1", adapter: "openai", keyEnv: "STACKIT_API_KEY" },
  { id: "stepfun", name: "StepFun", baseUrl: "https://api.stepfun.com/v1", adapter: "openai", keyEnv: "STEPFUN_API_KEY" },
  { id: "stepfun-ai", name: "StepFun AI", baseUrl: "https://api.stepfun.ai/step_plan/v1", adapter: "openai", keyEnv: "STEPFUN_API_KEY" },
  { id: "subconscious", name: "Subconscious", baseUrl: "https://api.subconscious.dev/v1", adapter: "anthropic", keyEnv: "SUBCONSCIOUS_API_KEY" },
  { id: "submodel", name: "submodel", baseUrl: "https://llm.submodel.ai/v1", adapter: "openai", keyEnv: "SUBMODEL_INSTAGEN_ACCESS_KEY" },
  { id: "synthetic", name: "Synthetic", baseUrl: "https://api.synthetic.new/openai/v1", adapter: "openai", keyEnv: "SYNTHETIC_API_KEY" },
  { id: "tencent-coding-plan", name: "Tencent Coding Plan (China)", baseUrl: "https://api.lkeap.cloud.tencent.com/coding/v3", adapter: "openai", keyEnv: "TENCENT_CODING_PLAN_API_KEY" },
  { id: "tencent-token-plan", name: "Tencent Token Plan", baseUrl: "https://api.lkeap.cloud.tencent.com/plan/v3", adapter: "openai", keyEnv: "TENCENT_TOKEN_PLAN_API_KEY" },
  { id: "tencent-tokenhub", name: "Tencent TokenHub", baseUrl: "https://tokenhub.tencentmaas.com/v1", adapter: "openai", keyEnv: "TENCENT_TOKENHUB_API_KEY" },
  { id: "the-grid-ai", name: "The Grid AI", baseUrl: "https://api.thegrid.ai/v1", adapter: "openai", keyEnv: "THEGRIDAI_API_KEY" },
  { id: "tinfoil", name: "Tinfoil", baseUrl: "https://inference.tinfoil.sh/v1", adapter: "openai", keyEnv: "TINFOIL_API_KEY" },
  { id: "togetherai", name: "Together AI", baseUrl: "https://api.together.xyz/v1", adapter: "openai", keyEnv: "TOGETHER_API_KEY" },
  { id: "trustedrouter", name: "TrustedRouter", baseUrl: "https://api.trustedrouter.com/v1", adapter: "openai", keyEnv: "TRUSTEDROUTER_API_KEY", gateway: true },
  { id: "umans-ai", name: "Umans AI", baseUrl: "https://api.code.umans.ai/v1", adapter: "openai", keyEnv: "UMANS_AI_API_KEY" },
  { id: "umans-ai-coding-plan", name: "Umans AI Coding Plan", baseUrl: "https://api.code.umans.ai/v1", adapter: "openai", keyEnv: "UMANS_AI_CODING_PLAN_API_KEY" },
  { id: "upstage", name: "Upstage", baseUrl: "https://api.upstage.ai/v1/solar", adapter: "openai", keyEnv: "UPSTAGE_API_KEY" },
  { id: "v0", name: "v0", baseUrl: "", adapter: "openai", keyEnv: "V0_API_KEY" },
  { id: "venice", name: "Venice AI", baseUrl: "https://api.venice.ai/api/v1", adapter: "openai", keyEnv: "VENICE_API_KEY" },
  { id: "vercel", name: "Vercel AI Gateway", baseUrl: "https://ai-gateway.vercel.sh/v1", adapter: "openai", keyEnv: "AI_GATEWAY_API_KEY", gateway: true },
  { id: "google-vertex", name: "Vertex", baseUrl: "", adapter: "openai", keyEnv: "GOOGLE_VERTEX_PROJECT" },
  { id: "google-vertex-anthropic", name: "Vertex (Anthropic)", baseUrl: "", adapter: "anthropic", keyEnv: "GOOGLE_VERTEX_PROJECT" },
  { id: "vivgrid", name: "Vivgrid", baseUrl: "https://api.vivgrid.com/v1", adapter: "openai", keyEnv: "VIVGRID_API_KEY" },
  { id: "vllm", name: "vLLM (yerel/self-host)", baseUrl: "http://localhost:8000/v1", adapter: "openai", local: true },
  { id: "vultr", name: "Vultr", baseUrl: "https://api.vultrinference.com/v1", adapter: "openai", keyEnv: "VULTR_API_KEY" },
  { id: "wafer.ai", name: "Wafer", baseUrl: "https://pass.wafer.ai/v1", adapter: "openai", keyEnv: "WAFER_API_KEY" },
  { id: "wandb", name: "Weights & Biases", baseUrl: "https://api.inference.wandb.ai/v1", adapter: "openai", keyEnv: "WANDB_API_KEY" },
  { id: "xiaomi", name: "Xiaomi", baseUrl: "https://api.xiaomimimo.com/v1", adapter: "openai", keyEnv: "XIAOMI_API_KEY" },
  { id: "xiaomi-token-plan-cn", name: "Xiaomi Token Plan (China)", baseUrl: "https://token-plan-cn.xiaomimimo.com/v1", adapter: "openai", keyEnv: "XIAOMI_API_KEY" },
  { id: "xiaomi-token-plan-ams", name: "Xiaomi Token Plan (Europe)", baseUrl: "https://token-plan-ams.xiaomimimo.com/v1", adapter: "openai", keyEnv: "XIAOMI_API_KEY" },
  { id: "xiaomi-token-plan-sgp", name: "Xiaomi Token Plan (Singapore)", baseUrl: "https://token-plan-sgp.xiaomimimo.com/v1", adapter: "openai", keyEnv: "XIAOMI_API_KEY" },
  { id: "xpersona", name: "Xpersona", baseUrl: "https://www.xpersona.co/v1", adapter: "openai", keyEnv: "XPERSONA_API_KEY" },
  { id: "zai", name: "Z.AI", baseUrl: "https://api.z.ai/api/paas/v4", adapter: "openai", keyEnv: "ZHIPU_API_KEY" },
  { id: "zai-coding-plan", name: "Z.AI Coding Plan", baseUrl: "https://api.z.ai/api/coding/paas/v4", adapter: "openai", keyEnv: "ZHIPU_API_KEY" },
  { id: "zeldoc", name: "Zeldoc", baseUrl: "https://api.zeldoc.ai/v1", adapter: "openai", keyEnv: "ZELDOC_API_KEY" },
  { id: "zenifra", name: "Zenifra", baseUrl: "https://ai.zenifra.com/v1", adapter: "openai", keyEnv: "ZENIFRA_AI_KEY" },
  { id: "zenmux", name: "ZenMux", baseUrl: "https://zenmux.ai/api/v1", adapter: "openai", keyEnv: "ZENMUX_API_KEY", gateway: true },
  { id: "zhipuai", name: "Zhipu AI", baseUrl: "https://open.bigmodel.cn/api/paas/v4", adapter: "openai", keyEnv: "ZHIPU_API_KEY" },
  { id: "zhipuai-coding-plan", name: "Zhipu AI Coding Plan", baseUrl: "https://open.bigmodel.cn/api/coding/paas/v4", adapter: "openai", keyEnv: "ZHIPU_API_KEY" }
]

export function findProvider(id: string): ProviderInfo | undefined {
  return PROVIDERS.find((p) => p.id === id)
}

export function dataDestinationNote(p: ProviderInfo, lang: 'tr' | 'en' = 'tr'): string {
  if (p.local) return lang === 'tr' ? 'Yerel süreç — veri makineden çıkmaz' : 'Local process — data stays on the machine'
  return lang === "tr" ? `Veri ${p.name} sunucularına gider` : `Data goes to ${p.name}`
}
